force-app/main/default/objects/leaseworks__Assembly_MR_Rate__c/leaseworks__Assembly_MR_Rate__c.object-meta.xml
<CustomObject>
    <description>Configure Maintenance Reserve funds by specifying links to assembly and maintenance events (optional), charge rates, ratio table, escalation, and fund validity period. When activated, the system starts producing MR invoices based on each lease utilization record.</description>
    <label>Supplemental Rent</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplemental Rent</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Assembly_MR_Rate__c/fields/leaseworks__Lease__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease__c</fullName>
    <description>Lease</description>
    <inlineHelpText>Lease</inlineHelpText>
    <label>Lease Name</label>
    <referenceTo>leaseworks__Lease__c</referenceTo>
    <relationshipLabel>Supplemental Rent</relationshipLabel>
    <relationshipName>Assembly_MR_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/leaseworks__Assembly_MR_Rate__c/fields/leaseworks__MR_Rate_End_Date__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__MR_Rate_End_Date__c</fullName>
    <description>Automatically set to the lease end date unless overridden for internal schedule generation.</description>
    <label>Z_Unused_2506 Rate Schedule End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Assembly_MR_Rate__c/fields/leaseworks__Ratio_Table__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Ratio_Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>As part of the MR 2.0 changes, this field will be deprecated shortly. However, due to its impact on forecasting, we will retain the field for now.</description>
    <label>[OLD MR]Ratio Table</label>
    <referenceTo>leaseworks__Ratio_Table__c</referenceTo>
    <relationshipLabel>Supplemental Rent</relationshipLabel>
    <relationshipName>Assembly_MR_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/leaseworks__Lease__c.object-meta.xml
<CustomObject>
    <description>Central table for Lease Agreement/contract headers, storing essential details like start/end dates, current status, and associated asset reference.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__MR_Rate__c/leaseworks__MR_Rate__c.object-meta.xml
<CustomObject>
    <description>Maintenance Reserve Schedule for Advanced Escalation: Define and manage historical and future MR rates with user-defined escalation rules. Supports manual creation within the UI or bulk upload via data loader.
[MODULE: Contract]
[LOAD: Optional]
[PREREQUISITES: Lease, Supplemental Rent]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Rate Schedule</label>
    <nameField>
        <label>MR Rate Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__MR_Rate__c/fields/leaseworks__Assembly_MR_Info__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Assembly_MR_Info__c</fullName>
    <label>Supplemental Rent</label>
    <referenceTo>leaseworks__Assembly_MR_Rate__c</referenceTo>
    <relationshipName>MR_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/leaseworks__MR_Rate__c/fields/leaseworks__MR_Rate__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__MR_Rate__c</fullName>
    <label>[OLD MR]MR Rate</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/leaseworks__MR_Rate__c/fields/leaseworks__MR_Rate_End_Date__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__MR_Rate_End_Date__c</fullName>
    <description>Automatically set to the lease end date unless overridden for internal schedule generation.</description>
    <inlineHelpText>Automatically set to the lease end date unless overridden for internal schedule generation</inlineHelpText>
    <label>Rate Schedule End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__MR_Rate__c/fields/leaseworks__Y_Hidden_Utilization__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Y_Hidden_Utilization__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Utilization exists in this period.</description>
    <inlineHelpText>Utilization exists in this period. **This hidden field is temporarily available to sysadmins, awaiting LW Engg opinion re: impact.</inlineHelpText>
    <label>_Utilization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/leaseworks__Ratio_Table__c/leaseworks__Ratio_Table__c.object-meta.xml
<CustomObject>
    <description>This container serves as a repository for the matrix table containing various rates and units. The matrix table will subsequently be utilized in MR calculation following its association with supplemental rent.</description>
    <label>Ratio/Matrix Table</label>
    <nameField>
        <label>Ratio / Matrix Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ratio/Matrix Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Supplemental_Rent_Rate__c/leaseworks__Supplemental_Rent_Rate__c.object-meta.xml
<CustomObject>
    <description>This placeholder stores all rate details for the MR calculations. Multiple MR charges can be defined for supplemental rent, and the utilization MR calculation will consider all of them. Based on the method defined in the supplemental rent, the total MR calculation for a particular component will be performed.</description>
    <label>Supplemental Rent Rate</label>
    <nameField>
        <label>Supplemental Rent Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplemental Rent Rate</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Supplemental_Rent_Rate__c/fields/leaseworks__MR_Rate_Schedule__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__MR_Rate_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MR Rate Schedule</label>
    <referenceTo>leaseworks__MR_Rate__c</referenceTo>
    <relationshipLabel>Supplemental Rent Rate</relationshipLabel>
    <relationshipName>Supplemental_Rent_Rate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Supplemental_Rent_Rate__c/fields/leaseworks__Rate_Based_On__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Rate_Based_On__c</fullName>
    <description>The &apos;Rate Based on&apos; field specifies which rate to use for the calculation. Selecting the &apos;Rate&apos; option will use the rate value for the MR calculation, while selecting the &apos;Ratio/Matrix Table&apos; option will use the interpolated value from the respective ratio/matrix table for the MR calculation. Either the rate or ratio/matrix table is mandatory, depending on the option chosen in this field.</description>
    <inlineHelpText>The &apos;Rate Based on&apos; field specifies which rate to use for the calculation. Selecting the &apos;Rate&apos; option will use the rate value for the MR calculation, while selecting the &apos;Ratio/Matrix Table&apos; option will use the interpolated value from the respective ratio/matrix table for the MR calculation. Either the rate or ratio/matrix table is mandatory, depending on the option chosen in this field.</inlineHelpText>
    <label>Rate Based On</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rate</fullName>
            </value>
            <value>
                <fullName>Ratio Table</fullName>
                <label>Ratio/Matrix Table</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Supplemental_Rent_Rate__c/fields/leaseworks__Ratio_Table__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Ratio_Table__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Look up to the &apos;Ratio/Matrix Table&apos; for this supplemental rent rate. It will be used for MR calculation when generating utilization.</description>
    <inlineHelpText>Kindly link the appropriate Ratio/Matrix Table with this supplemental rent rate. It will be used for MR calculation when generating utilization.</inlineHelpText>
    <label>Ratio/Matrix Table</label>
    <referenceTo>leaseworks__Ratio_Table__c</referenceTo>
    <relationshipLabel>Supplemental Rent Rate</relationshipLabel>
    <relationshipName>Supplemental_Rent_Rate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Supplemental_Rent_Rate__c/fields/leaseworks__Supplemental_Rent__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Supplemental_Rent__c</fullName>
    <description>Master relationship with Supplemental Rent</description>
    <inlineHelpText>Master relationship with Supplemental Rent</inlineHelpText>
    <label>Supplemental Rent</label>
    <referenceTo>leaseworks__Assembly_MR_Rate__c</referenceTo>
    <relationshipLabel>Supplemental Rent Rate</relationshipLabel>
    <relationshipName>Supplemental_Rent_Rate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/leaseworks__Supplemental_Rent_Rate__c/fields/leaseworks__Y_hidden_Base_Supplemental_Rent_Rate__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Y_hidden_Base_Supplemental_Rent_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the previous rate schedule related SRR record</description>
    <inlineHelpText>This field is used to store the previous rate schedule related SRR record</inlineHelpText>
    <label>_Base Supplemental Rent Rate</label>
    <referenceTo>leaseworks__Supplemental_Rent_Rate__c</referenceTo>
    <relationshipLabel>Supplemental Rent Rate</relationshipLabel>
    <relationshipName>Supplemental_Rent_Rate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SRScript_Local.cls
/**
 * @description This class is to get all impacted records due to v55 Json Task
 * Assana Link :https://app.asana.com/1/7934919496419/task/1212446068089874?focus=true
 */
public class SRScript_Local {

    static List<Map<String, String>> logRows = new List<Map<String, String>>();
    public static void ratioTableVerification(){
        List<leaseworks__Assembly_MR_Rate__c> listSR = [
            SELECT Id, Name, leaseworks__Lease__c,leaseworks__Lease__r.name,
                (SELECT Id, Name, leaseworks__Y_Hidden_Utilization__c
                 FROM leaseworks__MR_Rates__r
                 ORDER BY leaseworks__MR_Rate_End_Date__c desc),
                 (SELECT id, leaseworks__MR_Rate_Schedule__c, leaseworks__Ratio_Table__c, leaseworks__Rate_Based_On__c 
                 FROM leaseworks__Supplemental_Rent_Rate__r 
                 where leaseworks__Ratio_Table__c != null and leaseworks__Rate_Based_On__c ='Ratio Table'
                 and leaseworks__MR_Rate_Schedule__c != null)
            FROM leaseworks__Assembly_MR_Rate__c //where id ='a37Do0000009MgiIAE'
        ];

        map<id, list<leaseworks__Supplemental_Rent_Rate__c>> MapOfSRRwithRS = new map<id, list<leaseworks__Supplemental_Rent_Rate__c>>();

        for(leaseworks__Assembly_MR_Rate__c SR : listSR){
            for(leaseworks__Supplemental_Rent_Rate__c srr : SR.leaseworks__Supplemental_Rent_Rate__r ){
                if(MapOfSRRwithRS.containsKey(srr.leaseworks__MR_Rate_Schedule__c)){
                    MapOfSRRwithRS.get(srr.leaseworks__MR_Rate_Schedule__c).add(srr);
                }else{
                    MapOfSRRwithRS.put(srr.leaseworks__MR_Rate_Schedule__c, new list<leaseworks__Supplemental_Rent_Rate__c>{ srr });
                }
            }
        }
        for (leaseworks__Assembly_MR_Rate__c parentRate : listSR) {
            List<leaseworks__MR_Rate__c> children = parentRate.leaseworks__MR_Rates__r;
            if (children == null || children.isEmpty()) {
                continue;
            }

            for (Integer idx = 0; idx < children.size(); idx++) {

                leaseworks__MR_Rate__c current = children[idx];

                if (current.leaseworks__Y_Hidden_Utilization__c) {

                    leaseworks__MR_Rate__c previousRec = idx > 0 ? children[idx - 1] : null;
                    leaseworks__MR_Rate__c nextRec     = idx < children.size() - 1 ? children[idx + 1] : null;
                    // SRRs for current rate schedule
                    List<leaseworks__Supplemental_Rent_Rate__c> currentSRRs = MapOfSRRwithRS.containsKey(current.Id) ? MapOfSRRwithRS.get(current.Id) : null;
                    if(currentSRRs == null){
                        break;
                    }
                    Integer currentSRRCount = currentSRRs.size();
                    // If current schedule has more than 1 SRR
                    if (currentSRRCount > 1) {
						logRow(parentRate.leaseworks__Lease__r.name,parentRate.leaseworks__Lease__c,parentRate.Id, parentRate.Name,Null,Null,'Multiple SRRs found');
                    }
                    else {
                        // Compare with previous
                        if (previousRec != null) {

                            leaseworks__Supplemental_Rent_Rate__c currentSRR = currentSRRs[0];

                            // SRRs for previous rate schedule
                            List<leaseworks__Supplemental_Rent_Rate__c> previousSRRs = 
                                MapOfSRRwithRS.containsKey(previousRec.Id) ? 
                                MapOfSRRwithRS.get(previousRec.Id) : 
                                new List<leaseworks__Supplemental_Rent_Rate__c>();

                            Integer previousSRRCount = previousSRRs.size();

                            if (previousSRRCount == 1) {

                                leaseworks__Supplemental_Rent_Rate__c previousSRR = previousSRRs[0];
                                Boolean isMatch = false;

                                // Compare ratio table
                                if (currentSRR.leaseworks__Rate_Based_On__c == 'Ratio Table' && previousSRR.leaseworks__Rate_Based_On__c == 'Ratio Table' &&
                                    currentSRR.leaseworks__Ratio_Table__c ==previousSRR.leaseworks__Ratio_Table__c) 
                                {
                                    isMatch = true;
                                }

                                if (!isMatch) {
                                    logRow(parentRate.leaseworks__Lease__r.name,parentRate.leaseworks__Lease__c,parentRate.Id, parentRate.Name,current.Id,previousRec.Id,'Next');
                                }

                            } else {
                                logRow(parentRate.leaseworks__Lease__r.name,parentRate.leaseworks__Lease__c,parentRate.Id, parentRate.Name,currentSRRs[0].Id,previousRec.Id,'Multiple Next');
                                
                            }
                        }

                        // Compare with next
                        if (nextRec != null && currentSRRCount == 1) {

                            leaseworks__Supplemental_Rent_Rate__c currentSRR = currentSRRs[0];

                            // SRRs for next rate schedule
                            List<leaseworks__Supplemental_Rent_Rate__c> nextSRRs = MapOfSRRwithRS.containsKey(nextRec.Id) ? MapOfSRRwithRS.get(nextRec.Id) : new List<leaseworks__Supplemental_Rent_Rate__c>();

                            Integer nextSRRCount = nextSRRs.size();

                            if (nextSRRCount == 1) {

                                leaseworks__Supplemental_Rent_Rate__c nextSRR = nextSRRs[0];
                                Boolean isMatch = false;

                                if (currentSRR.leaseworks__Rate_Based_On__c == 'Ratio Table' && nextSRR.leaseworks__Rate_Based_On__c == 'Ratio Table' &&
                                    currentSRR.leaseworks__Ratio_Table__c ==nextSRR.leaseworks__Ratio_Table__c) {
                                    isMatch = true;
                                }

                                if (!isMatch) {
                                   logRow(parentRate.leaseworks__Lease__r.name,parentRate.leaseworks__Lease__c,parentRate.Id, parentRate.Name,current.Id,nextRec.Id,'Previous'); 
                                }

                            } else {

                                    logRow(parentRate.leaseworks__Lease__r.name,parentRate.leaseworks__Lease__c,parentRate.Id, parentRate.Name,currentSRR.Id,nextRec.Id,'Previous Multiple'); 
                               
                            }
                        }
                    }
                    break;
                }
            }
        }
        exportToCSV();
    }
    
    private static void logRow( String leaseName,String leaseId,String srId,String srName,String currentRateSchedule,
    								String siblingRateSchedule,String relationType        // "Next vs Current" or "Current vs Previous"
    ){
        Map<String, String> row = new Map<String, String>();
        row.put('Lease Name', leaseName);
        row.put('Lease ID', leaseId);
        row.put('SR ID', srId);
        row.put('SR Name', srName);
        row.put('Current Rate Schedule', currentRateSchedule);
        row.put('Next/Prev Rate Schedule', siblingRateSchedule);
        row.put('Relation Type', relationType);
        logRows.add(row);
    }
    
    private static void exportToCSV() {
        if (logRows.isEmpty()) return;
       system.debug('logRows----'+logRows.size());
        // Headers
        List<String> headers = new List<String>{
            'Lease Name',
            'Lease ID',
            'SR ID',
            'SR Name',
            'Current Rate Schedule',
            'Next/Prev Rate Schedule',
            'Relation Type'
        };
    
        String csv = String.join(headers, ',') + '\n';
    
        // Rows
        for (Map<String,String> row : logRows) {
            List<String> vals = new List<String>();
            for (String h : headers) {
                String val = row.containsKey(h) ? row.get(h) : '';
                vals.add('"' + val.replace('"', '""') + '"');
            }
            csv += String.join(vals, ',') + '\n';
        }
    
        ContentVersion cv = new ContentVersion(
            Title = 'RatioTable_Report_' + Datetime.now().format('yyyyMMdd_HHmmss'),
            PathOnClient = 'RatioTableReport.csv',
            VersionData = Blob.valueOf(csv)
        );
        insert cv;
    }
}