force-app/main/default/objects/leaseworks__Assembly_MR_Rate__c/leaseworks__Assembly_MR_Rate__c.object-meta.xml
<CustomObject>
    <description>Configure Maintenance Reserve funds by specifying links to assembly and maintenance events (optional), charge rates, ratio table, escalation, and fund validity period. When activated, the system starts producing MR invoices based on each lease utilization record.</description>
    <label>Supplemental Rent</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplemental Rent</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Assembly_MR_Rate__c/fields/leaseworks__Lease__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease__c</fullName>
    <description>Lease</description>
    <inlineHelpText>Lease</inlineHelpText>
    <label>Lease Name</label>
    <referenceTo>leaseworks__Lease__c</referenceTo>
    <relationshipLabel>Supplemental Rent</relationshipLabel>
    <relationshipName>Assembly_MR_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/leaseworks__Assembly_MR_Rate__c/fields/leaseworks__Rate_Basis__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Rate_Basis__c</fullName>
    <description>As part of the MR 2.0 changes, this field will be deprecated shortly. However, due to its impact on forecasting, we will retain the field for now.</description>
    <label>[OLD MR] Rate Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Cycles</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>APU H</fullName>
            </value>
            <value>
                <fullName>APU C</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/leaseworks__Lease__c.object-meta.xml
<CustomObject>
    <description>Central table for Lease Agreement/contract headers, storing essential details like start/end dates, current status, and associated asset reference.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__MR_Rate__c/leaseworks__MR_Rate__c.object-meta.xml
<CustomObject>
    <description>Maintenance Reserve Schedule for Advanced Escalation: Define and manage historical and future MR rates with user-defined escalation rules. Supports manual creation within the UI or bulk upload via data loader.
[MODULE: Contract]
[LOAD: Optional]
[PREREQUISITES: Lease, Supplemental Rent]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Rate Schedule</label>
    <nameField>
        <label>MR Rate Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__MR_Rate__c/fields/leaseworks__Assembly_MR_Info__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Assembly_MR_Info__c</fullName>
    <label>Supplemental Rent</label>
    <referenceTo>leaseworks__Assembly_MR_Rate__c</referenceTo>
    <relationshipName>MR_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/leaseworks__MR_Rate__c/fields/leaseworks__MR_Rate__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__MR_Rate__c</fullName>
    <label>[OLD MR]MR Rate</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/leaseworks__MR_Rate__c/fields/leaseworks__Rate_Basis__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Rate_Basis__c</fullName>
    <label>[OLD MR]Rate Basis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Cycles</fullName>
            </value>
            <value>
                <fullName>APU H</fullName>
            </value>
            <value>
                <fullName>APU C</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Supplemental_Rent_Rate__c/leaseworks__Supplemental_Rent_Rate__c.object-meta.xml
<CustomObject>
    <description>This placeholder stores all rate details for the MR calculations. Multiple MR charges can be defined for supplemental rent, and the utilization MR calculation will consider all of them. Based on the method defined in the supplemental rent, the total MR calculation for a particular component will be performed.</description>
    <label>Supplemental Rent Rate</label>
    <nameField>
        <label>Supplemental Rent Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplemental Rent Rate</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Supplemental_Rent_Rate__c/fields/leaseworks__MR_Rate_Schedule__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__MR_Rate_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MR Rate Schedule</label>
    <referenceTo>leaseworks__MR_Rate__c</referenceTo>
    <relationshipLabel>Supplemental Rent Rate</relationshipLabel>
    <relationshipName>Supplemental_Rent_Rate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Supplemental_Rent_Rate__c/fields/leaseworks__Supplemental_Rent__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Supplemental_Rent__c</fullName>
    <description>Master relationship with Supplemental Rent</description>
    <inlineHelpText>Master relationship with Supplemental Rent</inlineHelpText>
    <label>Supplemental Rent</label>
    <referenceTo>leaseworks__Assembly_MR_Rate__c</referenceTo>
    <relationshipLabel>Supplemental Rent Rate</relationshipLabel>
    <relationshipName>Supplemental_Rent_Rate</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/leaseworks__Supplemental_Rent_Rate__c/fields/leaseworks__Y_hidden_Base_Supplemental_Rent_Rate__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Y_hidden_Base_Supplemental_Rent_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the previous rate schedule related SRR record</description>
    <inlineHelpText>This field is used to store the previous rate schedule related SRR record</inlineHelpText>
    <label>_Base Supplemental Rent Rate</label>
    <referenceTo>leaseworks__Supplemental_Rent_Rate__c</referenceTo>
    <relationshipLabel>Supplemental Rent Rate</relationshipLabel>
    <relationshipName>Supplemental_Rent_Rate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Supplemental_Rent_Rate__c/fields/leaseworks__Y_Hidden_Serial_No__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Y_Hidden_Serial_No__c</fullName>
    <label>_Serial No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LocalBatchSRRSerialNoUpdate.cls
global class LocalBatchSRRSerialNoUpdate implements Database.Batchable<SObject>, Database.Stateful {

    global String errormsg = '';
    global Integer count = 0;

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Name, leaseworks__Rate_Basis__c, leaseworks__Assembly_MR_Info__c, 
                   leaseworks__Assembly_MR_Info__r.leaseworks__Lease__c, 
                   leaseworks__Assembly_MR_Info__r.leaseworks__Lease__r.Name,
                   leaseworks__Assembly_MR_Info__r.Name, 
                   leaseworks__Assembly_MR_Info__r.leaseworks__Rate_Basis__c,
                   (SELECT Id, Name, leaseworks__Y_Hidden_Serial_No__c 
                    FROM leaseworks__Supplemental_Rent_Rate__r 
                    WHERE CreatedBy.Name = 'vijaya lakshmi')
            FROM leaseworks__MR_Rate__c
        ]);
    }

    global void execute(Database.BatchableContext bc, List<leaseworks__MR_Rate__c> scope) {
        List<leaseworks__Supplemental_Rent_Rate__c> listSRRToUpdate = new List<leaseworks__Supplemental_Rent_Rate__c>();

        for (leaseworks__MR_Rate__c rate : scope) {
            if (rate.leaseworks__Supplemental_Rent_Rate__r.size() == 1 
                && rate.leaseworks__Supplemental_Rent_Rate__r[0].leaseworks__Y_Hidden_Serial_No__c == null) {

                leaseworks__Supplemental_Rent_Rate__c srr = rate.leaseworks__Supplemental_Rent_Rate__r[0];
                srr.leaseworks__Y_Hidden_Serial_No__c = 1; // Update Serial Number
                listSRRToUpdate.add(srr);
                count++;
            }
        }

        if (!listSRRToUpdate.isEmpty()) {
            try {
                leaseworks.LWGlobalUtils.setTriggersAndWFsOff();
                update listSRRToUpdate;
            } catch (Exception e) {
                errormsg += '\n Error updating SRR records: ' + e.getMessage();
            } finally {
                leaseworks.LWGlobalUtils.setTriggersAndWFsOn();
            }
            if(test.isRunningTest()){
                errormsg += 'Dummy error for Test Run';
            }
        }
    }

    global void finish(Database.BatchableContext bc) {
        if (String.isNotBlank(errormsg)) {
            String subject = 'Error updating SRR records: ' + Date.today().format();
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            List<String> toAddresses = new List<String>();
            toAddresses.add(UserInfo.getUserEmail());
            email.setSubject(subject);
            email.setToAddresses(toAddresses);
            email.setHtmlBody(errormsg);
            Messaging.SendEmailResult[] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        }

        System.debug('Total SRR records updated: ' + count);
    }
}