force-app/main/default/objects/leaseworks__Deal_Team__c/leaseworks__Deal_Team__c.object-meta.xml
<CustomObject>
    <label>Deal Team</label>
    <nameField>
        <label>Deal Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Deal_Team__c/fields/leaseworks__Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Department_Defaults</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Deal_Team__c/fields/leaseworks__Marketing_Activity__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Marketing_Activity__c</fullName>
    <label>Deal</label>
    <referenceTo>leaseworks__Marketing_Activity__c</referenceTo>
    <relationshipLabel>Deal Teams</relationshipLabel>
    <relationshipName>Deal_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/leaseworks__Deal_Team__c/fields/pro_Member_Role__c.field-meta.xml
<CustomField>
    <fullName>pro_Member_Role__c</fullName>
    <label>Member Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>pro_Deal_Team_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Marketing_Activity__c/leaseworks__Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Deal
[MODULE: NA]
[LOAD: No]
[PREREQUISITES: NA]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Deal</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Marketing_Activity__c/fields/leaseworks__Deal_Status__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Deal_Status__c</fullName>
    <label>Deal Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>CCO Sign Off</fullName>
            </value>
            <value>
                <fullName>Termsheet Drafting</fullName>
            </value>
            <value>
                <fullName>Termsheet Sent</fullName>
            </value>
            <value>
                <fullName>Mandated</fullName>
            </value>
            <value>
                <fullName>Termsheet Signed</fullName>
            </value>
            <value>
                <fullName>IC Approval</fullName>
            </value>
            <value>
                <fullName>LOI in works</fullName>
            </value>
            <value>
                <fullName>LOI</fullName>
                <label>LOI Sent</label>
            </value>
            <value>
                <fullName>ADM Approval</fullName>
            </value>
            <value>
                <fullName>LOI Signed</fullName>
                <label>LOI Signature</label>
            </value>
            <value>
                <fullName>BAC Approval</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Agreement Executed</fullName>
            </value>
            <value>
                <fullName>SPA</fullName>
            </value>
            <value>
                <fullName>Closed - Won</fullName>
            </value>
            <value>
                <fullName>Closed - Lost</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
                <isActive>false</isActive>
                <label>Delivered</label>
            </value>
            <value>
                <fullName>Market Intel</fullName>
                <isActive>false</isActive>
                <label>Market Intel</label>
            </value>
            <value>
                <fullName>Note</fullName>
                <isActive>false</isActive>
                <label>Note</label>
            </value>
            <value>
                <fullName>Project</fullName>
                <isActive>false</isActive>
                <label>Project</label>
            </value>
            <value>
                <fullName>Request Approved</fullName>
                <isActive>false</isActive>
                <label>Request Approved</label>
            </value>
            <value>
                <fullName>Request Being Evaluated</fullName>
                <isActive>false</isActive>
                <label>Request Being Evaluated</label>
            </value>
            <value>
                <fullName>Request Received</fullName>
                <isActive>false</isActive>
                <label>Request Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Marketing_Activity__c/fields/leaseworks__Inactive_MA__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Inactive_MA__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If the deal is closed, need to check the Inactive check box. Also will need to give reason for closing</inlineHelpText>
    <label>Inactive?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pro_Notification_Control__c/pro_Notification_Control__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Can be used as a flag to control triggering of notification flows upon creation or update of a record.</description>
    <label>Flow Control</label>
</CustomObject>

force-app/main/default/objects/pro_Notification_Control__c/fields/pro_Disable_Notifications__c.field-meta.xml
<CustomField>
    <fullName>pro_Disable_Notifications__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, conditions on flows for sending notifications will avoid triggering the flow.</description>
    <label>Disable Flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/pro_Deal_Team_Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Compliance</fullName>
    </customValue>
    <customValue>
        <fullName>Contracts</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Debt</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Investment &amp; Strategy</fullName>
    </customValue>
    <customValue>
        <fullName>Lease Management</fullName>
    </customValue>
    <customValue>
        <fullName>Legal</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>MR Claims</fullName>
    </customValue>
    <customValue>
        <fullName>Non Deal Approver</fullName>
    </customValue>
    <customValue>
        <fullName>Portfolio Management</fullName>
    </customValue>
    <customValue>
        <fullName>Powerplant</fullName>
    </customValue>
    <customValue>
        <fullName>Regional Marketing Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Tax</fullName>
    </customValue>
    <customValue>
        <fullName>Technical</fullName>
    </customValue>
    <customValue>
        <fullName>Trading</fullName>
    </customValue>
    <customValue>
        <fullName>Investment / Strategy</fullName>
        <isActive>false</isActive>
        <label>Investment / Strategy</label>
    </customValue>
    <customValue>
        <fullName>Powerplantdav</fullName>
        <isActive>false</isActive>
        <label>Powerplantdav</label>
    </customValue>
    <customValue>
        <fullName>Investments</fullName>
        <isActive>false</isActive>
        <label>Investments</label>
    </customValue>
    <customValue>
        <fullName>Runway</fullName>
        <isActive>false</isActive>
        <label>Runway</label>
    </customValue>
    <customValue>
        <fullName>Accounting</fullName>
        <isActive>false</isActive>
        <label>Accounting</label>
    </customValue>
    <customValue>
        <fullName>Asset Trading</fullName>
        <isActive>false</isActive>
        <label>Asset Trading</label>
    </customValue>
    <customValue>
        <fullName>Receivables</fullName>
        <isActive>false</isActive>
        <label>Receivables</label>
    </customValue>
    <customValue>
        <fullName>Pricing</fullName>
        <isActive>false</isActive>
        <label>Pricing</label>
    </customValue>
    <customValue>
        <fullName>Executive</fullName>
        <isActive>false</isActive>
        <label>Executive</label>
    </customValue>
    <masterLabel>Deal Team Roles</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DealTeamInsertBatch.cls
global class DealTeamInsertBatch implements Database.Batchable<SObject>, Database.Stateful {

    global Integer dtSuccess = 0;
    global Integer dtFail = 0;

    global Database.QueryLocator start(Database.BatchableContext bc) {
        pro_Notification_Control__c nc = pro_Notification_Control__c.getOrgDefaults();
        nc.pro_Disable_Notifications__c = true;
        upsert nc;

        return Database.getQueryLocator([
            SELECT Id
            FROM leaseworks__Marketing_Activity__c
            WHERE leaseworks__Inactive_MA__c = false
            AND leaseworks__Deal_Status__c != 'Closed - Won'
            AND leaseworks__Deal_Status__c != 'Closed - Lost'
        ]);
    }

    global void execute(Database.BatchableContext bc, List<leaseworks__Marketing_Activity__c> scope) {
        List<leaseworks__Deal_Team__c> dealTeams = new List<leaseworks__Deal_Team__c>();
        for (leaseworks__Marketing_Activity__c deal : scope) {
            dealTeams.add(new leaseworks__Deal_Team__c(
                leaseworks__Marketing_Activity__c = deal.Id,
                pro_Member_Role__c                = 'Insurance',
                leaseworks__Assigned_To__c        = '0052o00000DQnHVAA1'
            ));
        }

        List<Database.SaveResult> results = Database.insert(dealTeams, false);
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) { dtSuccess++; } else { dtFail++; }
        }
    }

    global void finish(Database.BatchableContext bc) {
        pro_Notification_Control__c nc = pro_Notification_Control__c.getOrgDefaults();
        nc.pro_Disable_Notifications__c = false;
        upsert nc;

        System.debug('Done — DealTeam success: ' + dtSuccess + ', fail: ' + dtFail);
    }
}