force-app/main/default/objects/leaseworks__Marketing_Activity__c/leaseworks__Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Deal
[MODULE: NA]
[LOAD: No]
[PREREQUISITES: NA]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Deal</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Marketing_Activity__c/fields/leaseworks__Counter_Party__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Counter_Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that is being engaged for this deal</description>
    <inlineHelpText>Account that is being engaged for this deal.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>notEqual</operation>
            <value>Operator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Marketing_Activity__c/fields/leaseworks__Deal_Status__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Deal_Status__c</fullName>
    <label>Deal Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>CCO Sign Off</fullName>
            </value>
            <value>
                <fullName>Termsheet Drafting</fullName>
            </value>
            <value>
                <fullName>Termsheet Sent</fullName>
            </value>
            <value>
                <fullName>Mandated</fullName>
            </value>
            <value>
                <fullName>Termsheet Signed</fullName>
            </value>
            <value>
                <fullName>IC Approval</fullName>
            </value>
            <value>
                <fullName>LOI in works</fullName>
            </value>
            <value>
                <fullName>LOI</fullName>
                <label>LOI Sent</label>
            </value>
            <value>
                <fullName>ADM Approval</fullName>
            </value>
            <value>
                <fullName>LOI Signed</fullName>
                <label>LOI Signature</label>
            </value>
            <value>
                <fullName>BAC Approval</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Agreement Executed</fullName>
            </value>
            <value>
                <fullName>SPA</fullName>
            </value>
            <value>
                <fullName>Closed - Won</fullName>
            </value>
            <value>
                <fullName>Closed - Lost</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
                <isActive>false</isActive>
                <label>Delivered</label>
            </value>
            <value>
                <fullName>Market Intel</fullName>
                <isActive>false</isActive>
                <label>Market Intel</label>
            </value>
            <value>
                <fullName>Note</fullName>
                <isActive>false</isActive>
                <label>Note</label>
            </value>
            <value>
                <fullName>Project</fullName>
                <isActive>false</isActive>
                <label>Project</label>
            </value>
            <value>
                <fullName>Request Approved</fullName>
                <isActive>false</isActive>
                <label>Request Approved</label>
            </value>
            <value>
                <fullName>Request Being Evaluated</fullName>
                <isActive>false</isActive>
                <label>Request Being Evaluated</label>
            </value>
            <value>
                <fullName>Request Received</fullName>
                <isActive>false</isActive>
                <label>Request Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Marketing_Activity__c/fields/leaseworks__Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Deal_Type__c</fullName>
    <inlineHelpText>Indicates if the deal is for a lease, SLB, extension, sale etc. and is set at the time of creating the deal. Once an deal has been created, this cannot be changed. You will have to delete and recreate the deal</inlineHelpText>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Engine Exchange</fullName>
            </value>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Lease Amendment</fullName>
            </value>
            <value>
                <fullName>Lease Extension</fullName>
            </value>
            <value>
                <fullName>Lending</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Sale_Novation</fullName>
                <label>Sale - Novation</label>
            </value>
            <value>
                <fullName>Sale_Off_Lease</fullName>
                <label>Sale - Off Lease</label>
            </value>
            <value>
                <fullName>SLB</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
                <label>Non-Deal Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Marketing_Activity__c/fields/leaseworks__Probability_N__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Probability_N__c</fullName>
    <description>Probability of winning the deal.</description>
    <inlineHelpText>Probability of winning the deal</inlineHelpText>
    <label>Probability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>100%</fullName>
                <isActive>false</isActive>
                <label>100%</label>
            </value>
            <value>
                <fullName>25%</fullName>
                <isActive>false</isActive>
                <label>25%</label>
            </value>
            <value>
                <fullName>50%</fullName>
                <isActive>false</isActive>
                <label>50%</label>
            </value>
            <value>
                <fullName>75%</fullName>
                <isActive>false</isActive>
                <label>75%</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Marketing_Activity__c/recordTypes/Approval.recordType-meta.xml
<RecordType>
    <fullName>Approval</fullName>
    <active>true</active>
    <label>Approval</label>
</RecordType>

force-app/main/default/classes/TestMarketingActivityTriggerHandlerLocal.cls
/**
* Test class for MarketingActivityTriggerHandlerLocal.
*
* @author Manasa Jaisetty
* @date 08-01-2024 
*/
@isTest
public class TestMarketingActivityTriggerHandlerLocal {
    
    /*
        Description/Business Scenario: Test update of Deal Status for High probability deals
        
        Type: Validation/Negative Test: validation
        
        Assertion: Validation message when high probability deals do not go through ADM Approval
    
    */
    @isTest
    public static void validateHighProbabilityDealStatus() 
    {   
        Account testAcc = new Account(Name= 'TestOperator', Type = 'Operator');
        insert testAcc;
        
        leaseworks__Marketing_Activity__c dealRec = new leaseworks__Marketing_Activity__c(Name = 'My Deal',
                                                                                           OwnerId = UserInfo.getUserId(),
                                                                                           leaseworks__Counter_Party__c = testAcc.Id,
                                                                                           leaseworks__Deal_Type__c = 'Lease', 
                                                                                           leaseworks__Probability_N__c = 'High',
                                                                                           leaseworks__Deal_Status__c = 'LOI');
        
        insert dealRec;
        
        dealRec.leaseworks__Deal_Status__c = 'LOI Signed';
        try{
            update dealRec;
            System.assert(false);
        }
        catch(Exception ex){
            boolean expectedExceptionThrown = false; 
            expectedExceptionThrown =  ex.getMessage().contains('High Probability Deals need \'ADM Approval\'.') ? true : false ;
            system.assertEquals(expectedExceptionThrown,true,'Error messsage is wrong');
        }
        
    }
    
     /*
        Description/Business Scenario: Test update of Deal Status for Low/Medium probability deals
        
        Type: Validation/Negative Test: validation
        
        Assertion: Validation message when low probability deals move to ADM approval or any status beyond
    
    */
    @isTest    
    public static void validateLowProbabilityDealStatus() 
    {   
        Account testAcc = new Account(Name= 'TestOperator', Type = 'Operator');
        insert testAcc;
        
        leaseworks__Marketing_Activity__c dealRec = new leaseworks__Marketing_Activity__c(Name = 'My Deal',
                                                                                           OwnerId = UserInfo.getUserId(),
                                                                                           leaseworks__Counter_Party__c = testAcc.Id,
                                                                                           leaseworks__Deal_Type__c = 'Lease', 
                                                                                           leaseworks__Probability_N__c = 'Low',
                                                                                           leaseworks__Deal_Status__c = 'LOI');
        
        insert dealRec;
        
        dealRec.leaseworks__Deal_Status__c = 'LOI Signed';
        try{
            update dealRec;
            System.assert(false);
        }
        catch(Exception ex){
            boolean expectedExceptionThrown = false; 
            expectedExceptionThrown =  ex.getMessage().contains('Only High Probability Deals can progress to \'ADM Approval\' deal status or a higher deal status.') ? true : false ;
            system.assertEquals(expectedExceptionThrown,true,'Error messsage is wrong');
        }
        
    }

}