force-app/main/default/objects/leaseworks__Marketing_Activity__c/leaseworks__Marketing_Activity__c.object-meta.xml
<CustomObject>
    <description>Deal
[MODULE: NA]
[LOAD: No]
[PREREQUISITES: NA]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Deal</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Marketing_Activity__c/fields/leaseworks__Deal_Status__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Deal_Status__c</fullName>
    <label>Deal Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>CCO Sign Off</fullName>
            </value>
            <value>
                <fullName>Termsheet Drafting</fullName>
            </value>
            <value>
                <fullName>Termsheet Sent</fullName>
            </value>
            <value>
                <fullName>Mandated</fullName>
            </value>
            <value>
                <fullName>Termsheet Signed</fullName>
            </value>
            <value>
                <fullName>IC Approval</fullName>
            </value>
            <value>
                <fullName>LOI in works</fullName>
            </value>
            <value>
                <fullName>LOI</fullName>
                <label>LOI Sent</label>
            </value>
            <value>
                <fullName>ADM Approval</fullName>
            </value>
            <value>
                <fullName>LOI Signed</fullName>
                <label>LOI Signature</label>
            </value>
            <value>
                <fullName>BAC Approval</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Agreement Executed</fullName>
            </value>
            <value>
                <fullName>SPA</fullName>
            </value>
            <value>
                <fullName>Closed - Won</fullName>
            </value>
            <value>
                <fullName>Closed - Lost</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
                <isActive>false</isActive>
                <label>Delivered</label>
            </value>
            <value>
                <fullName>Market Intel</fullName>
                <isActive>false</isActive>
                <label>Market Intel</label>
            </value>
            <value>
                <fullName>Note</fullName>
                <isActive>false</isActive>
                <label>Note</label>
            </value>
            <value>
                <fullName>Project</fullName>
                <isActive>false</isActive>
                <label>Project</label>
            </value>
            <value>
                <fullName>Request Approved</fullName>
                <isActive>false</isActive>
                <label>Request Approved</label>
            </value>
            <value>
                <fullName>Request Being Evaluated</fullName>
                <isActive>false</isActive>
                <label>Request Being Evaluated</label>
            </value>
            <value>
                <fullName>Request Received</fullName>
                <isActive>false</isActive>
                <label>Request Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Marketing_Activity__c/fields/leaseworks__Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Deal_Type__c</fullName>
    <inlineHelpText>Indicates if the deal is for a lease, SLB, extension, sale etc. and is set at the time of creating the deal. Once an deal has been created, this cannot be changed. You will have to delete and recreate the deal</inlineHelpText>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Engine Exchange</fullName>
            </value>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Lease Amendment</fullName>
            </value>
            <value>
                <fullName>Lease Extension</fullName>
            </value>
            <value>
                <fullName>Lending</fullName>
            </value>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Sale_Novation</fullName>
                <label>Sale - Novation</label>
            </value>
            <value>
                <fullName>Sale_Off_Lease</fullName>
                <label>Sale - Off Lease</label>
            </value>
            <value>
                <fullName>SLB</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
                <label>Non-Deal Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Marketing_Activity__c/fields/leaseworks__Probability_N__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Probability_N__c</fullName>
    <description>Probability of winning the deal.</description>
    <inlineHelpText>Probability of winning the deal</inlineHelpText>
    <label>Probability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>100%</fullName>
                <isActive>false</isActive>
                <label>100%</label>
            </value>
            <value>
                <fullName>25%</fullName>
                <isActive>false</isActive>
                <label>25%</label>
            </value>
            <value>
                <fullName>50%</fullName>
                <isActive>false</isActive>
                <label>50%</label>
            </value>
            <value>
                <fullName>75%</fullName>
                <isActive>false</isActive>
                <label>75%</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Marketing_Activity__c/recordTypes/Approval.recordType-meta.xml
<RecordType>
    <fullName>Approval</fullName>
    <active>true</active>
    <label>Approval</label>
</RecordType>

force-app/main/default/classes/MarketingActivityTriggerHandlerLocal.cls
/**
* Name: MarketingActivityTriggerHandlerLocal
* Description: The MarketingActivityTriggerHandlerLocal is used to implement processes to get trigger when
* leaseworks__Marketing_Activity__c inserted, updated or deleted
*
* @author Manasa Jaisetty
* @date 08-01-2024
*/
    public class MarketingActivityTriggerHandlerLocal implements ITriggerLocal {
        public MarketingActivityTriggerHandlerLocal() {}

    /**
    * bulkBefore
    *
    * This method is called prior to execution of a BEFORE trigger. Use this to cache
    * any data required into maps prior execution of the trigger.
    */
    public void bulkBefore() {
    // If this a delete trigger Cache a list of Deal Id's that are 'in use' 
    }
   
    public void bulkAfter() {}

    public void beforeInsert() {               
    }
   
    public void beforeUpdate() {
        validateDealStatus();
    }
   
        /**
    * beforeDelete
    *
    * This method is called iteratively for each record to be deleted during a BEFORE
    * trigger.
    */
    public void beforeDelete() {}
   
    public void afterInsert() {}
   
    public void afterUpdate() {}
   
    public void afterDelete() {}
   
    public void afterUnDelete() {}
   
    /**
    * andFinally
    *
    * This method is called once all records have been processed by the trigger. Use this
    * method to accomplish any final operations such as creation or updates of other records.
    */
    public void andFinally() {
    // insert any audit records
    }
    
    private static void validateDealStatus(){
        
        Schema.DescribeFieldResult fieldResult = leaseworks__Marketing_Activity__c.leaseworks__Deal_Status__c.getDescribe(); // Getting all the picklist values
        List<Schema.PicklistEntry> lstPicklistEntries = fieldResult.getPicklistValues();
        
        map<string, Integer> mapPle = new map<string, Integer>(); //Key: Deal Status, Value: Order of the picklist entry
        Integer idx = 0;
        Integer referenceIdx = 0;
        for(Schema.PicklistEntry ple: lstPicklistEntries){
            mapPle.put(ple.getValue(), ++idx);
            if(ple.getValue() == 'ADM Approval'){
                referenceIdx = idx;
            }
        }
        System.debug('Reference Idx==' + referenceIdx);
        
        for(leaseworks__Marketing_Activity__c tempDeal: (List<leaseworks__Marketing_Activity__c>)trigger.new){
            leaseworks__Marketing_Activity__c oldDeal = (leaseworks__Marketing_Activity__c)trigger.oldmap.get(tempDeal.id);
            // Bypass validation if Deal Type is 'Non Deal Approval'
            if (String.valueOf(tempDeal.leaseworks__Deal_Type__c).equalsIgnoreCase('Approval')) {
                continue;
            }
            /*For High probability deals, user has to get 'ADM Approval' to set any status post 'ADM Approval'.
            However, user can update the deal status to 'Closed-Lost' without any restrictions*/
            if(oldDeal.leaseworks__deal_status__c != tempDeal.leaseworks__deal_status__c && tempDeal.leaseworks__deal_status__c != 'Closed - Lost')
            {
                if(tempDeal.leaseworks__Probability_N__c == 'High'){
                    if(mapPle.get(tempDeal.leaseworks__deal_status__c) > referenceIdx && 
                       mapPle.get(oldDeal.leaseworks__deal_status__c) < referenceIdx){
                        tempDeal.addError('High Probability Deals need \'ADM Approval\'.');          
                   }    
                }
                else{// Low and Medium probability deals
                    if(mapPle.get(tempDeal.leaseworks__deal_status__c) >= referenceIdx){
                        tempDeal.addError('Only High Probability Deals can progress to \'ADM Approval\' deal status or a higher deal status.');          
                    }
                }
                
            }        
        }
    }
}