force-app/main/default/objects/Interest_Calculator_Parameter__mdt/Interest_Calculator_Parameter__mdt.object-meta.xml
<CustomObject>
    <description>To specify the interest calculation values</description>
    <label>Interest Calculator Parameter</label>
    <pluralLabel>Interest Calculator Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Interest_Calculator_Parameter__mdt/fields/Compound_Interest__c.field-meta.xml
<CustomField>
    <fullName>Compound_Interest__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if the late payment interest calculation is compounded</inlineHelpText>
    <label>Compound Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interest_Calculator_Parameter__mdt/fields/Grace_Period__c.field-meta.xml
<CustomField>
    <fullName>Grace_Period__c</fullName>
    <inlineHelpText>Indicates the number of days after the due date for which interest won&#39;t be charged. Valid entries are from 1 to 365, no decimals.</inlineHelpText>
    <label>Grace Period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interest_Calculator_Parameter__mdt/fields/Interest_Base__c.field-meta.xml
<CustomField>
    <fullName>Interest_Base__c</fullName>
    <label>Interest Base</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>360</fullName>
                <default>true</default>
                <label>360</label>
            </value>
            <value>
                <fullName>365</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interest_Calculator_Parameter__mdt/fields/Interest_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Interest_Calculation_Method__c</fullName>
    <label>Interest Calculation Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Previous Balance</fullName>
                <default>true</default>
                <label>Previous Balance</label>
            </value>
            <value>
                <fullName>Adjusted Balance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/leaseworks__Lease__c.object-meta.xml
<CustomObject>
    <description>Central table for Lease Agreement/contract headers, storing essential details like start/end dates, current status, and associated asset reference.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Lease__c/fields/Grace_Period__c.field-meta.xml
<CustomField>
    <fullName>Grace_Period__c</fullName>
    <inlineHelpText>Grace period after expiry date</inlineHelpText>
    <label>Grace Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/Include_In_Bulk_Interest_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Include_In_Bulk_Interest_Calculation__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Check this box to include all overdue invoices from this lease in the default interest calculation process. Uncheck to exclude them.</inlineHelpText>
    <label>Include In Bulk Interest Calculation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Active_Override__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Active_Override__c</fullName>
    <description>Use this field to override Active? status of the lease with a user entered value</description>
    <inlineHelpText>Use this field to override Active? status of the lease with a user entered value</inlineHelpText>
    <label>Active? Override</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Grace_Period_After_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Grace_Period_After_Due_Date__c</fullName>
    <inlineHelpText>Indicates the number of days after the due date for which interest won&apos;t be charged. Valid entries are from 1 to 365, no decimals.</inlineHelpText>
    <label>Grace Period After Due Date</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Interest_Base__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Interest_Base__c</fullName>
    <label>Interest Base</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>365</fullName>
                <default>true</default>
                <label>365</label>
            </value>
            <value>
                <fullName>360</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Interest_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Interest_Calculation_Method__c</fullName>
    <description>Select how interest is calculated for this contract. Previous Balance: Interest is calculated based on the balance at the start of the day. Adjusted Balance: Interest is calculated based on the balance at the end of the day, after any transactions.</description>
    <inlineHelpText>Select how interest is calculated for this contract. Previous Balance: Interest is calculated based on the balance at the start of the day. Adjusted Balance: Interest is calculated based on the balance at the end of the day, after any transactions.</inlineHelpText>
    <label>Interest Calculation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Previous Balance</fullName>
            </value>
            <value>
                <fullName>Adjusted Balance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Lease_End_Date_New__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease_End_Date_New__c</fullName>
    <label>Contract End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Lease_Start_Date_New__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease_Start_Date_New__c</fullName>
    <label>Contract Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchUpdateLeasesFromMetadataTest.cls
/**
* @description       : Test class for BatchUpdateLeasesFromMetadata class.
* @author            : abhishek.qa@lease-works.com.sndboxfull
* @group             : 
* @last modified on  : 20-08-2024
* @ last modified by  : Smrati Jain
**/
@isTest
public class BatchUpdateLeasesFromMetadataTest {
    
    @isTest
    public static void TestUpdateLeases() {
        
        Interest_Calculator_Parameter__mdt setupRecord = [SELECT Id, MasterLabel, Grace_Period__c,Interest_Base__c,Interest_Calculation_Method__c, Compound_Interest__c FROM Interest_Calculator_Parameter__mdt WHERE MasterLabel =: 'Setup'];
        
        // Insert lease records with null values to be updated by the batch
        List<leaseworks__Lease__c> leaseList = new List<leaseworks__Lease__c>();
        
        leaseworks__Lease__c lease1 = new leaseworks__Lease__c(
            leaseworks__Interest_Base__c = null,
            leaseworks__Grace_Period_After_Due_Date__c = null,
            leaseworks__Lease_End_Date_New__c= System.today(),leaseworks__Lease_Start_Date_New__c = Date.newInstance(2023,03,01),
            leaseworks__Interest_Calculation_Method__c = null,
            Include_In_Bulk_Interest_Calculation__c = false,
            leaseworks__Active_Override__c = 'Active'
        );
        leaseList.add(lease1);
        leaseworks.LWGlobalUtils.setTriggersAndWFsOff();
        insert leaseList;
        leaseworks.LWGlobalUtils.setTriggersAndWFsOn();
            
        Test.startTest();
        BatchUpdateLeasesFromMetadata batchobj = new BatchUpdateLeasesFromMetadata();
        Database.executeBatch(batchobj, 2); 
        Test.stopTest();
        
        leaseworks__Lease__c updatedLease = [SELECT Id, leaseworks__Interest_Base__c, leaseworks__Grace_Period_After_Due_Date__c, leaseworks__Interest_Calculation_Method__c FROM leaseworks__Lease__c WHERE Id = :lease1.Id];
        System.assertNotEquals(null, updatedLease.leaseworks__Interest_Base__c, 'Interest Base should have been updated');
    }
        
}