force-app/main/default/objects/Interest_Calculator_Parameter__mdt/Interest_Calculator_Parameter__mdt.object-meta.xml
<CustomObject>
    <description>To specify the interest calculation values</description>
    <label>Interest Calculator Parameter</label>
    <pluralLabel>Interest Calculator Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Interest_Calculator_Parameter__mdt/fields/Grace_Period__c.field-meta.xml
<CustomField>
    <fullName>Grace_Period__c</fullName>
    <inlineHelpText>Indicates the number of days after the due date for which interest won&#39;t be charged. Valid entries are from 1 to 365, no decimals.</inlineHelpText>
    <label>Grace Period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interest_Calculator_Parameter__mdt/fields/Interest_Base__c.field-meta.xml
<CustomField>
    <fullName>Interest_Base__c</fullName>
    <label>Interest Base</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>360</fullName>
                <default>true</default>
                <label>360</label>
            </value>
            <value>
                <fullName>365</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interest_Calculator_Parameter__mdt/fields/Interest_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Interest_Calculation_Method__c</fullName>
    <label>Interest Calculation Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Previous Balance</fullName>
                <default>true</default>
                <label>Previous Balance</label>
            </value>
            <value>
                <fullName>Adjusted Balance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/leaseworks__Lease__c.object-meta.xml
<CustomObject>
    <description>Central table for Lease Agreement/contract headers, storing essential details like start/end dates, current status, and associated asset reference.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Lease__c/fields/Grace_Period__c.field-meta.xml
<CustomField>
    <fullName>Grace_Period__c</fullName>
    <inlineHelpText>Grace period after expiry date</inlineHelpText>
    <label>Grace Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/Include_In_Bulk_Interest_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Include_In_Bulk_Interest_Calculation__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Check this box to include all overdue invoices from this lease in the default interest calculation process. Uncheck to exclude them.</inlineHelpText>
    <label>Include In Bulk Interest Calculation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Active__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Active__c</fullName>
    <description>Active? Lease checkbox for reporting. Driven by Lease Start and Lease End/Redelivery date, based on Setup -&gt; Custom Settings -&gt; Leaseworks Settings -&gt; Active Lease logic. Active? Override field on the Lease page can override the calculation formula when selected by user</description>
    <formula>If(
        (ISPICKVAL( leaseworks__Active_Override__c ,&#39;Default&#39;) || ISBLANK(TEXT( leaseworks__Active_Override__c ))) , 
        AND(leaseworks__Lease_Start_Date_New__c &lt;= TODAY(),
        
        IF($Setup.leaseworks__LeaseWorksSettings__c.leaseworks__Active_Lease_Logic__c=&#39;Redelivery Date&#39;,
        true,
        leaseworks__Lease_End_Date_New__c&gt;= TODAY()
        ),
        
        (TEXT(leaseworks__Lease_Type_Status__c)==&#39;On Lease&#39;),
        !ISBLANK(leaseworks__Aircraft__c) ),If(ISPICKVAL( leaseworks__Active_Override__c ,&#39;Active&#39;),True,False))</formula>
    <inlineHelpText>Active? Lease checkbox for reporting. Driven by Lease Start and Lease End or Redelivery date based on the configuration. Active? Override field on the Lease page can override the calculation formula when selected by user</inlineHelpText>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Grace_Period_After_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Grace_Period_After_Due_Date__c</fullName>
    <inlineHelpText>Indicates the number of days after the due date for which interest won&apos;t be charged. Valid entries are from 1 to 365, no decimals.</inlineHelpText>
    <label>Grace Period After Due Date</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Interest_Base__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Interest_Base__c</fullName>
    <label>Interest Base</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>365</fullName>
                <default>true</default>
                <label>365</label>
            </value>
            <value>
                <fullName>360</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Interest_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Interest_Calculation_Method__c</fullName>
    <description>Select how interest is calculated for this contract. Previous Balance: Interest is calculated based on the balance at the start of the day. Adjusted Balance: Interest is calculated based on the balance at the end of the day, after any transactions.</description>
    <inlineHelpText>Select how interest is calculated for this contract. Previous Balance: Interest is calculated based on the balance at the start of the day. Adjusted Balance: Interest is calculated based on the balance at the end of the day, after any transactions.</inlineHelpText>
    <label>Interest Calculation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Previous Balance</fullName>
            </value>
            <value>
                <fullName>Adjusted Balance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchUpdateLeasesFromMetadata.cls
/**
* @description       : this batch class is created solely for the purpose of fixing existing lease records
* @author            : abhishek.qa@lease-works.com.sndboxfull
* @group             : 
* @last modified on  : 20-08-2024
* @ last modified by  : Smrati Jain
**/
public class BatchUpdateLeasesFromMetadata implements Database.Batchable<sObject>{
    
    public Database.QueryLocator start(Database.BatchableContext BC){        
        String query = 'SELECT Id,leaseworks__Interest_Base__c,leaseworks__Interest_Calculation_Method__c,Include_In_Bulk_Interest_Calculation__c,leaseworks__Active__c FROM leaseworks__Lease__c WHERE leaseworks__Active__c = true order by CreatedDate desc limit 10';
        return Database.getQueryLocator([SELECT Id,leaseworks__Interest_Base__c,leaseworks__Interest_Calculation_Method__c,Include_In_Bulk_Interest_Calculation__c,leaseworks__Active__c FROM leaseworks__Lease__c WHERE leaseworks__Active__c = true order by CreatedDate desc]);
    }
    
    public void execute(Database.BatchableContext BC, List<leaseworks__Lease__c> leaseList){
        try{
            System.debug('In Execute');
            Interest_Calculator_Parameter__mdt setupRecord = Interest_Calculator_Parameter__mdt.getInstance('Setup');
            List<leaseworks__Lease__c> updateLeaseList = new List<leaseworks__Lease__c>();
            for(leaseworks__Lease__c leaseObj : leaseList){
                if(leaseObj.leaseworks__Interest_Base__c == null || leaseObj.leaseworks__Interest_Calculation_Method__c == null || leaseObj.Include_In_Bulk_Interest_Calculation__c == false){
                    leaseObj.leaseworks__Interest_Base__c = leaseObj.leaseworks__Interest_Base__c != null ? leaseObj.leaseworks__Interest_Base__c : setupRecord.Interest_Base__c;
                    //leaseObj.leaseworks__Grace_Period_After_Due_Date__c = leaseObj.leaseworks__Grace_Period_After_Due_Date__c != null ? leaseObj.leaseworks__Grace_Period_After_Due_Date__c : setupRecord.Grace_Period__c;
                    leaseObj.leaseworks__Interest_Calculation_Method__c = leaseObj.leaseworks__Interest_Calculation_Method__c != null ? leaseObj.leaseworks__Interest_Calculation_Method__c : setupRecord.Interest_Calculation_Method__c;
                    leaseObj.Include_In_Bulk_Interest_Calculation__c = true;
                    System.debug('Adding lease ' + leaseObj.Id);
                    updateLeaseList.add(leaseObj);
                }
            }
            leaseworks.LWGlobalUtils.setTriggersAndWFsOff();
            if(!updateLeaseList.isEmpty()){
                System.debug('Updating leases + ' + updateLeaseList.size());
                update updateLeaseList;
            }
            leaseworks.LWGlobalUtils.setTriggersAndWFsOn();
            
        }catch(Exception ex){
            leaseworks.LWGlobalUtils.setTriggersAndWFsOn(); 
            System.debug('Error in Line '+ex.getLineNumber() + ' Error is '+ex.getMessage());
        }
    }
    
    public void finish(Database.BatchableContext BC){
    }
}