force-app/main/default/objects/leaseworks__Supplemental_Rent_Rate__c/leaseworks__Supplemental_Rent_Rate__c.object-meta.xml
<CustomObject>
    <description>This placeholder stores all rate details for the MR calculations. Multiple MR charges can be defined for supplemental rent, and the utilization MR calculation will consider all of them. Based on the method defined in the supplemental rent, the total MR calculation for a particular component will be performed.</description>
    <label>Supplemental Rent Rate</label>
    <nameField>
        <label>Supplemental Rent Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplemental Rent Rate</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Supplemental_Rent_Utilization_Rate__c/leaseworks__Supplemental_Rent_Utilization_Rate__c.object-meta.xml
<CustomObject>
    <description>This placeholder displays the total MR calculation based on different rates set in the Supplemental Rent Rate. For each Supplemental Rent Rate, a corresponding Supplemental Rent Utilization Rate will be created. This provides better clarity and improves the reporting of MR calculations.</description>
    <label>Supplemental Rent Utilization Rate</label>
    <nameField>
        <label>SR Utilization Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplemental Rent Utilization Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Supplemental_Rent_Utilization_Rate__c/fields/leaseworks__Supplemental_Rent_Rate__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Supplemental_Rent_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Source supplemental Rent Rate record.</description>
    <inlineHelpText>The Source supplemental Rent Rate record.</inlineHelpText>
    <label>Supplemental Rent Rate</label>
    <referenceTo>leaseworks__Supplemental_Rent_Rate__c</referenceTo>
    <relationshipLabel>Supplemental Rent Utilization Rates</relationshipLabel>
    <relationshipName>Supplemental_Rent_Utilization_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Supplemental_Rent_Utilization_Rate__c/fields/leaseworks__Supplemental_Rent_Utilization__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Supplemental_Rent_Utilization__c</fullName>
    <description>The parent Supplemental Rent Utilization record. The parent record displays the Max/Sum of all defined MR rates and that flows to the MR Invoice line item.</description>
    <inlineHelpText>The parent Supplemental Rent Utilization record. The parent record displays the Max/Sum of all defined MR rates and that flows to the MR Invoice line item.</inlineHelpText>
    <label>Supplemental Rent Utilization</label>
    <referenceTo>leaseworks__Utilization_Report_List_Item__c</referenceTo>
    <relationshipLabel>Supplemental Rent Utilization Rates</relationshipLabel>
    <relationshipName>Supplemental_Rent_Utilization_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BatchDeleteSRURRecords.cls
/*
  Description: Batch to delete SRUR Records
  Reference Asana: https://app.asana.com/0/1150819886958569/1208125015503073/f
*/
 
public class BatchDeleteSRURRecords implements Database.Batchable<sObject>, Database.AllowsCallouts,Database.Stateful
    {
	string errormsg = '';
    String logMessage='';
	private static integer batchSize = 10;
        
    public BatchDeleteSRURRecords(){
	}

	public BatchDeleteSRURRecords(String errormessage){  // adding this for code coverage in test class
		errormsg = errormessage;
	}

	//START METHOD
	public Database.QueryLocator start(Database.BatchableContext BC)
	{
		system.debug('Start SRUR Delete Batch (+)');
		
        return Database.getQueryLocator([Select id,Name,leaseworks__Supplemental_Rent_Utilization__c, leaseworks__Supplemental_Rent_Rate__c,CreatedDate  from leaseworks__Supplemental_Rent_Utilization_Rate__c  ]);
	}

	//EXECUTE METHOD
	public void execute(Database.BatchableContext BC,List<sObject> scope)
	{
		system.debug('Execute ProjectedEventsBatch Batch (+)');
        List<leaseworks__Supplemental_Rent_Utilization_Rate__c> listToDelete = new List<leaseworks__Supplemental_Rent_Utilization_Rate__c>();
         for(leaseworks__Supplemental_Rent_Utilization_Rate__c curSRUR: (List<leaseworks__Supplemental_Rent_Utilization_Rate__c>)scope){
             	logMessage += 'SRUR Ids  :: '+curSRUR.id +'--> Name:'+ curSRUR.Name +'--Supplement Rent Utilization--'+curSRUR.leaseworks__Supplemental_Rent_Utilization__c+'\n' ;
				listToDelete.add(curSRUR);
        }
        if(listToDelete.size()>0){ 
            try{
                leaseworks.LWGlobalUtils.setTriggersAndWFsOff();
                 delete listToDelete;  
                leaseworks.LWGlobalUtils.setTriggersAndWFsOn();
        	}catch(Exception e){
                leaseworks.LWGlobalUtils.setTriggersAndWFsOn();
            	errormsg += 'Error in deleting SRUR Record ' + e.getMessage();
        	}
    	} 
		system.debug('Execute BatchDeleteSRURRecords Batch (-)');
	}

	//FINISH METHOD
	public void finish(Database.BatchableContext BC)
	{
		system.debug('Finish BatchDeleteSRURRecords Batch (+)');
        
        if(string.isNotBlank(errorMsg)){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTargetObjectId( UserInfo.getUserId() );
            mail.setSaveAsActivity( false );
            
            String subjectName = 'Error while deleting SRUR Records';
            mail.setSubject( '[' + System.UserInfo.getOrganizationName() + '(' + System.UserInfo.getOrganizationId()  + ')] - ' + subjectName );        
            mail.setHtmlBody(errorMsg);
			Messaging.sendEmail( new Messaging.SingleEmailMessage[] { mail } );
        }else{
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTargetObjectId( UserInfo.getUserId() );
            mail.setSaveAsActivity( false );
             
            String subjectName = 'Successfully deleted SRUR Records';
            mail.setSubject( '[' + System.UserInfo.getOrganizationName() + '(' + System.UserInfo.getOrganizationId()  + ')] - ' + subjectName );        
            mail.setHtmlBody(logMessage);
			Messaging.sendEmail( new Messaging.SingleEmailMessage[] { mail } );
        }
    }
  }