force-app/main/default/objects/pro_Notification_Control__c/pro_Notification_Control__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Can be used as a flag to control triggering of notification flows upon creation or update of a record.</description>
    <label>Flow Control</label>
</CustomObject>

force-app/main/default/objects/pro_Notification_Control__c/fields/pro_Disable_Notifications__c.field-meta.xml
<CustomField>
    <fullName>pro_Disable_Notifications__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, conditions on flows for sending notifications will avoid triggering the flow.</description>
    <label>Disable Flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NotificationToggle.cls
public with sharing class NotificationToggle {
    @InvocableMethod(
        label='Toggle Notification Setting' 
        description='Sets the org-wide Disable Notifications flag in the pro_Notification_Control__c hierarchy setting'
    )
    public static void toggleSetting(List<Request> requests) {
        for (Request req : requests) {
            // Get the organization-level hierarchy setting
            pro_Notification_Control__c setting = pro_Notification_Control__c.getOrgDefaults();
            
            // If none exists, create one
            if (setting == null) {
                setting = new pro_Notification_Control__c();
                setting.SetupOwnerId = UserInfo.getOrganizationId();
            }

            setting.pro_Disable_Notifications__c = req.disableNotifications;
            upsert setting;
        }
    }

    public class Request {
        @InvocableVariable(
            label='Disable Notifications' 
            description='Set to true to disable notifications, false to enable them'
        )
        public Boolean disableNotifications;
    }
}