force-app/main/default/objects/pro_Notification_Control__c/pro_Notification_Control__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Can be used as a flag to control triggering of notification flows upon creation or update of a record.</description>
    <label>Flow Control</label>
</CustomObject>

force-app/main/default/objects/pro_Notification_Control__c/fields/pro_Disable_Notifications__c.field-meta.xml
<CustomField>
    <fullName>pro_Disable_Notifications__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, conditions on flows for sending notifications will avoid triggering the flow.</description>
    <label>Disable Flows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/pro_NotificationToggleService.cls
/**
 * Efficient, non-invocable service for toggling the org-wide notification setting.
 * Single getOrgDefaults + single upsert (no List wrapper). Use from LWC/controller instead of NotificationToggle when not in Flow.
 */
public with sharing class pro_NotificationToggleService {

    /**
     * Sets the org-wide "Disable Notifications" flag. One DML operation.
     * @param disabled True to disable notifications, false to enable.
     */
    public static void setNotificationsDisabled(Boolean disabled) {
        pro_Notification_Control__c setting = pro_Notification_Control__c.getOrgDefaults();
        if (setting == null) {
            setting = new pro_Notification_Control__c();
            setting.SetupOwnerId = UserInfo.getOrganizationId();
        }
        setting.pro_Disable_Notifications__c = disabled;
        upsert setting;
    }
}