force-app/main/default/objects/Account/fields/Accounting__c.field-meta.xml
<CustomField>
    <fullName>Accounting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accounting</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountsMEjY</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Compliance__c.field-meta.xml
<CustomField>
    <fullName>Compliance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compliance</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contracts__c.field-meta.xml
<CustomField>
    <fullName>Contracts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contracts</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Credit__c.field-meta.xml
<CustomField>
    <fullName>Credit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Debt__c.field-meta.xml
<CustomField>
    <fullName>Debt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Debt</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Investment_Strategy__c.field-meta.xml
<CustomField>
    <fullName>Investment_Strategy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment / Strategy</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountsMEog</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/leaseworks__Country__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>leaseworks__Country__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal__c.field-meta.xml
<CustomField>
    <fullName>Legal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Marketing__c.field-meta.xml
<CustomField>
    <fullName>Marketing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Marketing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/MR_Claims__c.field-meta.xml
<CustomField>
    <fullName>MR_Claims__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MR Claims</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountsMEjs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Portfolio_Fund_Management__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Fund_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portfolio Management</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Powerplant__c.field-meta.xml
<CustomField>
    <fullName>Powerplant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Powerplant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountsMEjE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pricing__c.field-meta.xml
<CustomField>
    <fullName>Pricing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pricing</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountsMEjO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Receivables__c.field-meta.xml
<CustomField>
    <fullName>Receivables__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receivables</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountsMEji</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Technical__c.field-meta.xml
<CustomField>
    <fullName>Technical__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technical</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Trading__c.field-meta.xml
<CustomField>
    <fullName>Trading__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trading</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/leaseworks__Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_Accounting__c.field-meta.xml
<CustomField>
    <fullName>pro_Accounting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accounting</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Accounting</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_Compliance__c.field-meta.xml
<CustomField>
    <fullName>pro_Compliance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compliance</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Compliance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_Contracts__c.field-meta.xml
<CustomField>
    <fullName>pro_Contracts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contracts</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_Credit__c.field-meta.xml
<CustomField>
    <fullName>pro_Credit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Credit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_Debt__c.field-meta.xml
<CustomField>
    <fullName>pro_Debt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Debt</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Debt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_Investment_Strategy__c.field-meta.xml
<CustomField>
    <fullName>pro_Investment_Strategy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investment / Strategy</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Investment_Strategy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_Legal__c.field-meta.xml
<CustomField>
    <fullName>pro_Legal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Legal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_Marketing__c.field-meta.xml
<CustomField>
    <fullName>pro_Marketing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_MR_Claims__c.field-meta.xml
<CustomField>
    <fullName>pro_MR_Claims__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MR Claims</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_MRClaims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_Portfolio_Management__c.field-meta.xml
<CustomField>
    <fullName>pro_Portfolio_Management__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portfolio Management</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Portfolio_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_Powerplant__c.field-meta.xml
<CustomField>
    <fullName>pro_Powerplant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Powerplant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Powerplant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_Pricing__c.field-meta.xml
<CustomField>
    <fullName>pro_Pricing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pricing</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Pricing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_Receivables__c.field-meta.xml
<CustomField>
    <fullName>pro_Receivables__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receivables</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Receivables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_Tax__c.field-meta.xml
<CustomField>
    <fullName>pro_Tax__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Tax</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_Technical__c.field-meta.xml
<CustomField>
    <fullName>pro_Technical__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technical</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Technical</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/fields/pro_Trading__c.field-meta.xml
<CustomField>
    <fullName>pro_Trading__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trading</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Trading</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Deal_Team__c/leaseworks__Deal_Team__c.object-meta.xml
<CustomObject>
    <label>Deal Team</label>
    <nameField>
        <label>Deal Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Deal_Team__c/fields/leaseworks__Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Department_Defaults</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Deal_Team__c/fields/pro_Member_Role__c.field-meta.xml
<CustomField>
    <fullName>pro_Member_Role__c</fullName>
    <label>Member Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>pro_Deal_Team_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Legal__c/Legal__c.object-meta.xml
<CustomObject>
    <label>Legal</label>
    <nameField>
        <label>Legal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/pro_Deal_Team_Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Compliance</fullName>
    </customValue>
    <customValue>
        <fullName>Contracts</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <customValue>
        <fullName>Debt</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Investment &amp; Strategy</fullName>
    </customValue>
    <customValue>
        <fullName>Lease Management</fullName>
    </customValue>
    <customValue>
        <fullName>Legal</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>MR Claims</fullName>
    </customValue>
    <customValue>
        <fullName>Non Deal Approver</fullName>
    </customValue>
    <customValue>
        <fullName>Portfolio Management</fullName>
    </customValue>
    <customValue>
        <fullName>Powerplant</fullName>
    </customValue>
    <customValue>
        <fullName>Regional Marketing Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Tax</fullName>
    </customValue>
    <customValue>
        <fullName>Technical</fullName>
    </customValue>
    <customValue>
        <fullName>Trading</fullName>
    </customValue>
    <customValue>
        <fullName>Investment / Strategy</fullName>
        <isActive>false</isActive>
        <label>Investment / Strategy</label>
    </customValue>
    <customValue>
        <fullName>Powerplantdav</fullName>
        <isActive>false</isActive>
        <label>Powerplantdav</label>
    </customValue>
    <customValue>
        <fullName>Investments</fullName>
        <isActive>false</isActive>
        <label>Investments</label>
    </customValue>
    <customValue>
        <fullName>Runway</fullName>
        <isActive>false</isActive>
        <label>Runway</label>
    </customValue>
    <customValue>
        <fullName>Accounting</fullName>
        <isActive>false</isActive>
        <label>Accounting</label>
    </customValue>
    <customValue>
        <fullName>Asset Trading</fullName>
        <isActive>false</isActive>
        <label>Asset Trading</label>
    </customValue>
    <customValue>
        <fullName>Receivables</fullName>
        <isActive>false</isActive>
        <label>Receivables</label>
    </customValue>
    <customValue>
        <fullName>Pricing</fullName>
        <isActive>false</isActive>
        <label>Pricing</label>
    </customValue>
    <customValue>
        <fullName>Executive</fullName>
        <isActive>false</isActive>
        <label>Executive</label>
    </customValue>
    <masterLabel>Deal Team Roles</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TeamMemberUpdater.cls
/*
  * Created by Keiran in Prodigy on 22-01-2025.
  *
  * Description: <<Description of your code goes here>>.
  *
  * Last modified by Keiran in Prodigy on 22-01-2025.
  */

/*
    * Description: <<Replaces specified User lookup fields on Account, Country, or Deal Team records >>.
    *
    * Last modified by Keiran in Prodigy on 22-01-2025.
    */

public without sharing class TeamMemberUpdater {
    @InvocableMethod(label='Team Member Updater' description='Replaces specified User lookup fields on Account, Country, or Deal Team records.')
    public static void replaceAccountRoles(List<InputWrapper> inputList) {
        // Collect records to update
        List<Account> accountsToUpdate = new List<Account>();
        List<leaseworks__Country__c> countriesToUpdate = new List<leaseworks__Country__c>();
        List<leaseworks__Deal_Team__c> dealTeamsToUpdate = new List<leaseworks__Deal_Team__c>();
        
        for (InputWrapper input : inputList) {
         

            // Parse multi-select picklist values into a Set
            Set<String> selectedRoles = new Set<String>(input.roleTypes.split(';'));
            System.debug(selectedRoles);
            
            // Process Accounts
            if (input.accounts != null && !input.accounts.isEmpty()) {
                for (Account account : input.accounts) {
                    Boolean isUpdated = false; // Track if the account was updated
                    System.debug('Change Owner ' + input.ChangeOwner);
                    System.debug('Account Name ' + account.Name);
                    System.debug('Account Owner ' + account.OwnerId);
                    System.debug('Replacee ' + input.replacee.id);
                    // Update owner if ChangeOwner is true
                    if (input.ChangeOwner && account.OwnerId == input.replacee.Id) {
                        System.debug('Inside If Condition');
                        account.OwnerId = input.replacer.Id;
                        isUpdated = true; // Track that the account was updated
                    }
            
                    // Only process role-based updates if roleTypes are provided
                    if (!String.isBlank(input.roleTypes)) {                      
                        for (String role : selectedRoles) {
                            String fieldName = getFieldApiName(role); // Map role to field API name
                            if (fieldName != null && account.get(fieldName) == input.replacee.Id) {
                                account.put(fieldName, input.replacer.Id);
                                isUpdated = true;
                            }
                        }
                    }
            
                    // Add the account to the update list if any field was modified
                    if (isUpdated) {
                        accountsToUpdate.add(account);
                    }
                }
            }

            
            // Process Countries
            if (input.countries != null && !input.countries.isEmpty()) {
                for (leaseworks__Country__c country : input.countries) {
                    Boolean isUpdated = false; // Track if the country was updated
                    
                    // Update fields dynamically for country
                    for (String role : selectedRoles) {
                        String fieldName = getCountryFieldApiName(role); // Map role to field API name
                        if (fieldName != null && country.get(fieldName) == input.replacee.Id) {
                            country.put(fieldName, input.replacer.Id);
                            isUpdated = true;
                        }
                    }
                    
                    
                    
                    if (isUpdated) {
                        countriesToUpdate.add(country);
                    }
                }
            }

            // Process Deal Teams
            if (input.dealTeams != null && !input.dealTeams.isEmpty()) {
                for (leaseworks__Deal_Team__c dealTeam : input.dealTeams) {
                    // Check if pro_Member_Role__c matches one of the selected roles
                    if (selectedRoles.contains(dealTeam.Name) && 
                        dealTeam.leaseworks__Assigned_To__c == input.replacee.Id) {
                        
                        dealTeam.leaseworks__Assigned_To__c = input.replacer.Id;
                        dealTeamsToUpdate.add(dealTeam);
                    }
                }
            }
        }

        // Update modified records
        if (!accountsToUpdate.isEmpty()) {
            update accountsToUpdate;
        }
        if (!countriesToUpdate.isEmpty()) {
            update countriesToUpdate;
        }
        if (!dealTeamsToUpdate.isEmpty()) {
            update dealTeamsToUpdate;
        }
    }
    
    /**
     * Maps the role type from the multi-select picklist to the corresponding API field name for Accounts.
     */
    private static String getFieldApiName(String roleType) {
        Map<String, String> roleToFieldMap = new Map<String, String>{
            'Trading' => 'Trading__c',
            'Technical' => 'Technical__c',
            'Tax' => 'Tax__c',
            'Receivables' => 'Receivables__c',
            'Pricing' => 'Pricing__c',
            'Powerplant' => 'Powerplant__c',
            'Portfolio Management' => 'Portfolio_Fund_Management__c',
            'Marketing' => 'Marketing__c',
            'MR Claims' => 'MR_Claims__c',
            'Legal' => 'Legal__c',
            'Investment Strategy' => 'Investment_Strategy__c',
            'Debt' => 'Debt__c',
            'Credit' => 'Credit__c',
            'Contracts' => 'Contracts__c',
            'Compliance' => 'Compliance__c',
            'Accounting' => 'Accounting__c'
        };

        return roleToFieldMap.get(roleType);
    }
    
    private static String getCountryFieldApiName(String roleType) {
        Map<String, String> roleToCountryFieldMap = new Map<String, String>{
            'Trading' => 'pro_Trading__c',
            'Technical' => 'pro_Technical__c',
            'Tax' => 'pro_Tax__c',
            'Receivables' => 'pro_Receivables__c',
            'Pricing' => 'pro_Pricing__c',
            'Powerplant' => 'pro_Powerplant__c',
            'Portfolio Management' => 'pro_Portfolio_Management__c',
            'Marketing' => 'pro_Marketing__c',
            'MR Claims' => 'pro_MR_Claims__c',
            'Legal' => 'pro_Legal__c',
            'Investment Strategy' => 'pro_Investment_Strategy__c',
            'Debt' => 'pro_Debt__c',
            'Credit' => 'pro_Credit__c',
            'Contracts' => 'pro_Contracts__c',
            'Compliance' => 'pro_Compliance__c',
            'Accounting' => 'pro_Accounting__c'
        };

        return roleToCountryFieldMap.get(roleType);
    }
    
    /**
     * Input wrapper class for the invocable method.
     */
    public class InputWrapper {
        @InvocableVariable(required=true description='User to be replaced')
        public User replacee;

        @InvocableVariable(required=true description='User to replace with')
        public User replacer;

        @InvocableVariable(description='List of Account records')
        public List<Account> accounts;

        @InvocableVariable(description='List of Country records')
        public List<leaseworks__Country__c> countries;

        @InvocableVariable(description='List of Deal Team records')
        public List<leaseworks__Deal_Team__c> dealTeams;

        @InvocableVariable(description='Multi-select picklist of role types')
        public String roleTypes;
        
        @InvocableVariable(description='Whether to change record ownership')
        public Boolean ChangeOwner;
    }
}