force-app/main/default/objects/Account/fields/Financing_Local__c.field-meta.xml
<CustomField>
    <fullName>Financing_Local__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This was added at the time of Implementation</description>
    <label>Financing</label>
    <referenceTo>leaseworks__Financing__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fund_Local__c.field-meta.xml
<CustomField>
    <fullName>Fund_Local__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This was added at the time of Implementation</description>
    <label>Fund</label>
    <referenceTo>pro_Fund__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/leaseworks__Aircraft__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageAircraft</customHelpPage>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Asset_Owner_new__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Asset_Owner_new__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Owner of the Asset</description>
    <inlineHelpText>Owner of the Asset</inlineHelpText>
    <label>Asset Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets (Asset Owner)</relationshipLabel>
    <relationshipName>Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Lease__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field automatically fills with the current active Lease record linked to this Asset, identified by the &#39;Active&#39; field (leaseworks__Active__c) set to &#39;True&#39;. In the absence of an active Lease on this Asset (following the described logic), the system will clear this field. [This process is executed through a scheduled job that runs daily.]</description>
    <inlineHelpText>This field is automatically filled with the current active Lease record linked to this Asset, determined by the &#39;Active&#39; field being set to &#39;True&#39;. If there is no active Lease associated with this Asset (following the logic described), the system will clear this field.</inlineHelpText>
    <label>Lease</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Selected Lease has already different Asset assigned, please change the Lease before saving this Asset</errorMessage>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>leaseworks__Lease__c.leaseworks__Aircraft__c</valueField>
        </filterItems>
        <filterItems>
            <field>leaseworks__Lease__c.leaseworks__Aircraft__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Lease__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Aircrafts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Model_Code__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Model_Code__c</fullName>
    <label>Model Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__MSN_Number__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__MSN_Number__c</fullName>
    <externalId>true</externalId>
    <label>Serial Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/pro_Fund__c.field-meta.xml
<CustomField>
    <fullName>pro_Fund__c</fullName>
    <formula>leaseworks__Asset_Owner_new__r.Fund_Local__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fund</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Financing__c/leaseworks__Financing__c.object-meta.xml
<CustomObject>
    <description>Financing Information</description>
    <label>Financing</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financing</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Financing__c/fields/leaseworks__Aircraft__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Aircraft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aircraft</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>$Source.leaseworks__Lease__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Aircraft__c</referenceTo>
    <relationshipLabel>Financing</relationshipLabel>
    <relationshipName>Financing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Financing__c/fields/leaseworks__Lease__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lease</label>
    <referenceTo>leaseworks__Lease__c</referenceTo>
    <relationshipLabel>Financing</relationshipLabel>
    <relationshipName>Financing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Financing__c/fields/pro_Fund__c.field-meta.xml
<CustomField>
    <fullName>pro_Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links this Financing record to its parent Fund.</description>
    <label>Fund</label>
    <referenceTo>pro_Fund__c</referenceTo>
    <relationshipLabel>Financing</relationshipLabel>
    <relationshipName>Financing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/leaseworks__Lease__c.object-meta.xml
<CustomObject>
    <description>Central table for Lease Agreement/contract headers, storing essential details like start/end dates, current status, and associated asset reference.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Aircraft__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Aircraft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Specify the asset this lease is in relation to</inlineHelpText>
    <label>Asset</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>leaseworks__Aircraft__c.leaseworks__Status__c</field>
            <operation>equals</operation>
            <value>Available, Assigned</value>
        </filterItems>
        <filterItems>
            <field>$Source.leaseworks__Lease_Type_Status__c</field>
            <operation>equals</operation>
            <value>LOI</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non-Lease Agreement</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Aircraft__c</referenceTo>
    <relationshipLabel>Related Lease</relationshipLabel>
    <relationshipName>Leases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Lease_End_Date_New__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease_End_Date_New__c</fullName>
    <label>Contract End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Lease_Start_Date_New__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease_Start_Date_New__c</fullName>
    <label>Contract Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Lesor__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lessor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>notEqual</operation>
            <value>Operator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leases (Lessor)</relationshipLabel>
    <relationshipName>Leases4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pro_Fund__c/pro_Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Pro_RecordSharingControllerTest.cls
@isTest
public class Pro_RecordSharingControllerTest {
    
    @testSetup
    static void setupData() {
    
        // Create a Fund
        pro_Fund__c fund = new pro_Fund__c(Name = 'Test Fund');
        insert fund;
    
        // Create an Account linked to Fund
        Account acc = new Account(
            Name = 'Test Account',
            Fund_Local__c = fund.Id
        );
        insert acc;
    
        // Create Financing linked to Fund
        leaseworks__Financing__c fin = new leaseworks__Financing__c(
            Name = 'Test Financing',
            pro_Fund__c = fund.Id
        );
        insert fin;
    
        // Link Account to Financing
        acc.Financing_Local__c = fin.Id;
        update acc;
    
        leaseworks__Aircraft__c aircraft = new leaseworks__Aircraft__c(
            Name = 'Test Aircraft',
            leaseworks__MSN_Number__c = 'MSN12345',
            leaseworks__Model_Code__c = 'A320-200',
            leaseworks__Asset_Owner_new__c = acc.Id
        );
        insert aircraft;
    
        // Create Lease linked to Aircraft
        leaseworks__Lease__c lease = new leaseworks__Lease__c(
            Name = 'Test Lease',
            leaseworks__Lesor__c = acc.Id,
            leaseworks__Aircraft__c = aircraft.Id,
            leaseworks__Lease_Start_Date_New__c = Date.today(),
            leaseworks__Lease_End_Date_New__c = Date.today().addYears(1)
        );
        insert lease;
    }
    
        private static User createTestUser() {
            Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
            if (p == null) {
                p = [SELECT Id FROM Profile LIMIT 1];
            }
            User u = new User(
                Alias = 'tusr',
                Email = 'tuser' + System.currentTimeMillis() + '@example.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'Tester',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                ProfileId = p.Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                Username = 'tuser' + System.currentTimeMillis() + '@example.com'
            );
            insert u;
            return u;
        }
        
    @isTest
    static void testShareFund() {
        pro_Fund__c fund = [SELECT Id FROM pro_Fund__c LIMIT 1];
        User u = createTestUser();
    
        Test.startTest();
        try {
            Pro_RecordSharingController.shareRecord(fund.Id, u.Id, 'Read');
        } catch (DmlException ex) {
            System.assert(ex.getMessage().contains('trivial share level'));
        }
        Test.stopTest();
    
        Integer cnt = [SELECT COUNT() FROM pro_Fund__Share WHERE ParentId = :fund.Id AND UserOrGroupId = :u.Id];
        System.assert(cnt >= 0); 
    }

    @isTest
    static void testShareFinancing() {
        leaseworks__Financing__c fin = [SELECT Id FROM leaseworks__Financing__c LIMIT 1];
        User u = createTestUser();
    
        Test.startTest();
        try {
            Pro_RecordSharingController.shareRecord(fin.Id, u.Id, 'Read');
        } catch (DmlException ex) {
            System.assert(ex.getMessage().contains('trivial share level'));
        }
        Test.stopTest();
    
        Integer cnt = [SELECT COUNT() FROM leaseworks__Financing__Share WHERE ParentId = :fin.Id AND UserOrGroupId = :u.Id];
        System.assert(cnt >= 0);
    }

    @isTest
    static void testSearchUsersAndGroups() {
        Group g = new Group(
            Name = 'Test External Rep Group ' + System.currentTimeMillis(),
            Type = 'Regular'
        );
        insert g;
    
        Test.startTest();
        List<Pro_RecordSharingController.LookupResult> results =
            Pro_RecordSharingController.searchUsersAndGroups('Test');
        Test.stopTest();
    
        System.assert(results.size() > 0, 'Expected at least one user/group in results');
    
        Boolean foundGroup = false;
        for (Pro_RecordSharingController.LookupResult r : results) {
            if (r.Id == g.Id && r.Type == 'Group') {
                foundGroup = true;
                break;
            }
        }
        System.assert(foundGroup, 'Expected the inserted test group to be returned by search');
    }
    
    @isTest
    static void testGetExistingShares_Fund_Branch() {
        pro_Fund__c fund = [SELECT Id FROM pro_Fund__c LIMIT 1];
    
        Group g = new Group(Name = 'UT Fund Share Group ' + System.currentTimeMillis(), Type = 'Regular');
        insert g;
    
        Boolean fundShareInserted = false;
        try {
            pro_Fund__Share fs = new pro_Fund__Share(
                ParentId = fund.Id,
                UserOrGroupId = g.Id,
                AccessLevel = 'Read',
                RowCause = Schema.pro_Fund__Share.RowCause.Manual
            );
            insert fs;
            fundShareInserted = true;
        } catch (DmlException ignore) {}
    
        List<Pro_RecordSharingController.ShareInfo> out =
            Pro_RecordSharingController.getExistingShares(fund.Id);
        System.assertNotEquals(null, out);
    
        if (fundShareInserted) {
            Boolean found = false;
            for (Pro_RecordSharingController.ShareInfo s : out) {
                if (s.Id == g.Id) { found = true; break; }
            }
            System.assert(found, 'Expected inserted Fund share to be returned.');
        }
    }
    
    @isTest
    static void testGetExistingShares_Financing_Branch() {
        leaseworks__Financing__c fin = [SELECT Id FROM leaseworks__Financing__c LIMIT 1];
    
        Group g = new Group(Name = 'UT Financing Share Group ' + System.currentTimeMillis(), Type = 'Regular');
        insert g;
    
        Boolean finShareInserted = false;
        try {
            leaseworks__Financing__Share fs = new leaseworks__Financing__Share(
                ParentId = fin.Id,
                UserOrGroupId = g.Id,
                AccessLevel = 'Read',
                RowCause = Schema.leaseworks__Financing__Share.RowCause.Manual
            );
            insert fs;
            finShareInserted = true;
        } catch (DmlException ignore) {}
    
        List<Pro_RecordSharingController.ShareInfo> out =
            Pro_RecordSharingController.getExistingShares(fin.Id);
        System.assertNotEquals(null, out);
    
        if (finShareInserted) {
            Boolean found = false;
            for (Pro_RecordSharingController.ShareInfo s : out) {
                if (s.Id == g.Id) { found = true; break; }
            }
            System.assert(found, 'Expected inserted Financing share to be returned.');
        }
    }
    
    @isTest
    static void testGetExistingShares_Account_Branch() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
    
        Group g = new Group(Name = 'UT Account Share Group ' + System.currentTimeMillis(), Type = 'Regular');
        insert g;
    
        Boolean accShareInserted = false;
        try {
            AccountShare Accshare = new AccountShare(
                AccountId = acc.Id,
                UserOrGroupId = g.Id,
                AccountAccessLevel = 'Read',
                OpportunityAccessLevel = 'None',
                CaseAccessLevel = 'None',
                RowCause = Schema.AccountShare.RowCause.Manual
            );
            insert Accshare;
            accShareInserted = true;
        } catch (DmlException ignore) {}
    
        List<Pro_RecordSharingController.ShareInfo> out =
            Pro_RecordSharingController.getExistingShares(acc.Id);
        System.assertNotEquals(null, out);
    
        if (accShareInserted) {
            Boolean found = false;
            for (Pro_RecordSharingController.ShareInfo s : out) {
                if (s.Id == g.Id) { found = true; break; }
            }
            System.assert(found, 'Expected inserted Account share to be returned.');
        }
    }

    @isTest
    static void testRevokeRecordShare_Fund() {
        pro_Fund__c fund = [SELECT Id FROM pro_Fund__c LIMIT 1];
        User u = createTestUser();

        pro_Fund__Share s = new pro_Fund__Share(
            ParentId = fund.Id,
            UserOrGroupId = u.Id,
            AccessLevel = 'Read',
            RowCause = Schema.pro_Fund__Share.RowCause.Manual
        );
        insert s;

        Test.startTest();
        Pro_RecordSharingController.revokeRecordShare(fund.Id, u.Id);
        Test.stopTest();

        System.assertEquals(0, [SELECT COUNT() FROM pro_Fund__Share WHERE Id = :s.Id], 'Fund share should be deleted');
    }

    @isTest
    static void testRevokeRecordShare_Financing() {
        leaseworks__Financing__c fin = [SELECT Id FROM leaseworks__Financing__c LIMIT 1];
        User u = createTestUser();
    
        leaseworks__Financing__Share s;
        Boolean shareInserted = false;
        try {
            s = new leaseworks__Financing__Share(
                ParentId = fin.Id,
                UserOrGroupId = u.Id,
                AccessLevel = 'Edit',
                RowCause = Schema.leaseworks__Financing__Share.RowCause.Manual
            );
            insert s;
            shareInserted = true;
        } catch (DmlException ex) {
            System.debug('Skipping insert due to trivial share level: ' + ex.getMessage());
        }
    
        Test.startTest();
        Pro_RecordSharingController.revokeRecordShare(fin.Id, u.Id);
        Test.stopTest();
    
        if (shareInserted) {
            System.assertEquals(0,
                [SELECT COUNT() FROM leaseworks__Financing__Share WHERE Id = :s.Id],
                'Financing share should be deleted');
        } else {
            System.assert(true, 'No share inserted due to trivial level, revoke logic still executed.');
        }
    }

    @isTest
    static void testRevokeRecordShare_Account() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        User u = createTestUser();

        AccountShare s = new AccountShare(
            AccountId = acc.Id,
            UserOrGroupId = u.Id,
            AccountAccessLevel = 'Read',
            OpportunityAccessLevel = 'None',
            CaseAccessLevel = 'None',
            RowCause = Schema.AccountShare.RowCause.Manual
        );
        insert s;

        Test.startTest();
        Pro_RecordSharingController.revokeRecordShare(acc.Id, u.Id);
        Test.stopTest();

        System.assertEquals(0, [SELECT COUNT() FROM AccountShare WHERE Id = :s.Id], 'Account share should be deleted');
    }
    
    @isTest
    static void testAssetOwnerChangeTrigger() {
        
        Account oldAcc = new Account(Name = 'Old Owner');
        insert oldAcc;
    
        Account newAcc = new Account(Name = 'New Owner');
        insert newAcc;
    
        pro_Fund__c fund = new pro_Fund__c(Name = 'Fund - NewAcc');
        insert fund;
    
        leaseworks__Financing__c fin = new leaseworks__Financing__c(
            Name = 'Fin - NewAcc',
            pro_Fund__c = fund.Id
        );
        insert fin;
    
        newAcc.Fund_Local__c = fund.Id;
        newAcc.Financing_Local__c = fin.Id;
        update newAcc;
    
        leaseworks__Aircraft__c ac = new leaseworks__Aircraft__c(
            Name = 'Aircraft A',
            leaseworks__Asset_Owner_new__c = oldAcc.Id,
            leaseworks__MSN_Number__c = 'MSN123_TEST',
            leaseworks__Model_Code__c = 'A320-200'
        );
        insert ac;
    
        User extUser = createTestUser();
    
        AccountShare sh = new AccountShare(
            AccountId = oldAcc.Id,
            UserOrGroupId = extUser.Id,
            AccountAccessLevel = 'Read',
            OpportunityAccessLevel = 'None',
            CaseAccessLevel = 'None',
            RowCause = Schema.AccountShare.RowCause.Manual
        );
        insert sh;
    
        Test.startTest();
        ac.leaseworks__Asset_Owner_new__c = newAcc.Id;
        update ac; 
        Test.stopTest();
    
        Integer oldCnt = [
            SELECT COUNT() FROM AccountShare
            WHERE AccountId = :oldAcc.Id AND UserOrGroupId = :extUser.Id
        ];
        System.assertEquals(1, oldCnt, 'Old owner Account share should remain untouched');
    
        Integer newCnt = [
            SELECT COUNT() FROM AccountShare
            WHERE AccountId = :newAcc.Id AND UserOrGroupId = :extUser.Id
        ];
        System.assertEquals(0, newCnt, 'No new Account share should be created for new owner');
    
        Integer acShareCount = [
            SELECT COUNT() FROM leaseworks__Aircraft__Share
            WHERE ParentId = :ac.Id AND UserOrGroupId = :extUser.Id
        ];
        System.assertEquals(0, acShareCount,
            'Old owner user should not retain Aircraft share after ownership change when not shared to new owner');
    
        Integer leaseShareCount = [
            SELECT COUNT()
            FROM leaseworks__Lease__Share
            WHERE ParentId IN (
                SELECT Id FROM leaseworks__Lease__c WHERE leaseworks__Aircraft__c = :ac.Id
            )
            AND UserOrGroupId = :extUser.Id
        ];
        System.assertEquals(0, leaseShareCount,
            'Old owner user should not retain Lease share after ownership change');
    }
    
    @isTest
    static void testGetExistingShares_Aircraft_And_Lease_Branches() {
        leaseworks__Aircraft__c aircraft = [
            SELECT Id
            FROM leaseworks__Aircraft__c
            LIMIT 1
        ];
        leaseworks__Lease__c lease = [
            SELECT Id
            FROM leaseworks__Lease__c
            LIMIT 1
        ];

        Test.startTest();
        List<Pro_RecordSharingController.ShareInfo> aircraftShares =
            Pro_RecordSharingController.getExistingShares(aircraft.Id);
        List<Pro_RecordSharingController.ShareInfo> leaseShares =
            Pro_RecordSharingController.getExistingShares(lease.Id);
        Test.stopTest();

        System.assertNotEquals(null, aircraftShares, 'Aircraft branch should execute');
        System.assertNotEquals(null, leaseShares, 'Lease branch should execute');
    }

    @isTest
    static void testRevokeRecordShare_Aircraft_And_Lease() {
        leaseworks__Aircraft__c aircraft = [
            SELECT Id
            FROM leaseworks__Aircraft__c
            LIMIT 1
        ];
        leaseworks__Lease__c lease = [
            SELECT Id
            FROM leaseworks__Lease__c
            LIMIT 1
        ];

        User u = createTestUser();
        try {
            leaseworks__Aircraft__Share aShare = new leaseworks__Aircraft__Share(
                ParentId      = aircraft.Id,
                UserOrGroupId = u.Id,
                AccessLevel   = 'Read',
                RowCause      = Schema.leaseworks__Aircraft__Share.RowCause.Manual
            );
            insert aShare;
        } catch (DmlException ex) {
            System.debug('Skipping Aircraft share insert (possibly trivial): ' + ex.getMessage());
        }

        try {
            leaseworks__Lease__Share lShare = new leaseworks__Lease__Share(
                ParentId      = lease.Id,
                UserOrGroupId = u.Id,
                AccessLevel   = 'Read',
                RowCause      = Schema.leaseworks__Lease__Share.RowCause.Manual
            );
            insert lShare;
        } catch (DmlException ex) {
            System.debug('Skipping Lease share insert (possibly trivial): ' + ex.getMessage());
        }

        Test.startTest();
        Pro_RecordSharingController.revokeRecordShare(aircraft.Id, u.Id);
        Pro_RecordSharingController.revokeRecordShare(lease.Id, u.Id);
        Test.stopTest();

        Integer acShareCount = [
            SELECT COUNT()
            FROM leaseworks__Aircraft__Share
            WHERE ParentId = :aircraft.Id
            AND UserOrGroupId = :u.Id
        ];
        Integer leaseShareCount = [
            SELECT COUNT()
            FROM leaseworks__Lease__Share
            WHERE ParentId = :lease.Id
            AND UserOrGroupId = :u.Id
        ];
        System.assertEquals(0, acShareCount, 'Aircraft shares for user should be revoked');
        System.assertEquals(0, leaseShareCount, 'Lease shares for user should be revoked');
    }

    @isTest
    static void testGetSharedUsersForAccount_AllLevels() {
        Account acc = [
            SELECT Id
            FROM Account
            WHERE Name = 'Test Account'
            LIMIT 1
        ];

        User u = createTestUser();
        AccountShare s = new AccountShare(
            AccountId            = acc.Id,
            UserOrGroupId        = u.Id,
            AccountAccessLevel   = 'Read',
            OpportunityAccessLevel = 'None',
            CaseAccessLevel        = 'None',
            RowCause             = Schema.AccountShare.RowCause.Manual
        );
        try {
            insert s;
        } catch (DmlException ex) {
            System.debug('Skipping AccountShare insert (possibly trivial): ' + ex.getMessage());
        }

        Test.startTest();
        Set<Id> users = Pro_RecordSharingController.getSharedUsersForAccount(acc.Id);
        Test.stopTest();
        System.assertNotEquals(null, users, 'Method should return a Set');
        if (!users.isEmpty()) {
            System.assert(users.contains(u.Id), 'Expected shared user to be returned for Account');
        }
    }

        @isTest
    static void testRecalcSharingForAircraft_NewOwnerHasUsers() {
        Account oldAcc = [
            SELECT Id
            FROM Account
            WHERE Name = 'Test Account'
            LIMIT 1
        ];

        leaseworks__Aircraft__c ac = [
            SELECT Id, leaseworks__Asset_Owner_new__c
            FROM leaseworks__Aircraft__c
            WHERE leaseworks__Asset_Owner_new__c = :oldAcc.Id
            LIMIT 1
        ];

        leaseworks__Lease__c lease = [
            SELECT Id
            FROM leaseworks__Lease__c
            WHERE leaseworks__Aircraft__c = :ac.Id
            LIMIT 1
        ];

        Account newAcc = new Account(Name = 'New Owner 2');
        insert newAcc;

        User extUser = createTestUser();
        AccountShare oldAccShare = new AccountShare(
            AccountId             = oldAcc.Id,
            UserOrGroupId         = extUser.Id,
            AccountAccessLevel    = 'Read',
            OpportunityAccessLevel = 'None',
            CaseAccessLevel        = 'None',
            RowCause              = Schema.AccountShare.RowCause.Manual
        );
        AccountShare newAccShare = new AccountShare(
            AccountId             = newAcc.Id,
            UserOrGroupId         = extUser.Id,
            AccountAccessLevel    = 'Read',
            OpportunityAccessLevel = 'None',
            CaseAccessLevel        = 'None',
            RowCause              = Schema.AccountShare.RowCause.Manual
        );
        try {
            insert new List<AccountShare>{ oldAccShare, newAccShare };
        } catch (DmlException ex) {
            System.debug('Skipping AccountShare inserts (possibly trivial): ' + ex.getMessage());
        }

        try {
            leaseworks__Aircraft__Share aShare = new leaseworks__Aircraft__Share(
                ParentId      = ac.Id,
                UserOrGroupId = extUser.Id,
                AccessLevel   = 'Read',
                RowCause      = Schema.leaseworks__Aircraft__Share.RowCause.Manual
            );
            leaseworks__Lease__Share lShare = new leaseworks__Lease__Share(
                ParentId      = lease.Id,
                UserOrGroupId = extUser.Id,
                AccessLevel   = 'Read',
                RowCause      = Schema.leaseworks__Lease__Share.RowCause.Manual
            );
            insert new List<SObject>{ aShare, lShare };
        } catch (DmlException ex) {
            System.debug('Skipping initial Aircraft/Lease share inserts: ' + ex.getMessage());
        }
        Test.startTest();
        Pro_RecordSharingController.recalcSharingForAircraft(ac.Id, oldAcc.Id, newAcc.Id);
        Test.stopTest();

        Integer acShareCount = [
            SELECT COUNT()
            FROM leaseworks__Aircraft__Share
            WHERE ParentId = :ac.Id
            AND UserOrGroupId = :extUser.Id
        ];
        Integer leaseShareCount = [
            SELECT COUNT()
            FROM leaseworks__Lease__Share
            WHERE ParentId = :lease.Id
            AND UserOrGroupId = :extUser.Id
        ];
        System.assert(acShareCount >= 0, 'Aircraft share query should succeed');
        System.assert(leaseShareCount >= 0, 'Lease share query should succeed');
        if (acShareCount == 0 || leaseShareCount == 0) {
            System.debug('Shares may be treated as trivial in this org, but recalcSharingForAircraft executed.');
        }
    }
}