force-app/main/default/objects/Account/fields/leaseworks__Main_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Main_Email_Address__c</fullName>
    <description>Email address set up to contact the airline (preferably the CEO or the CFO of the firm)</description>
    <label>Main Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/leaseworks__Region__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Region__c</fullName>
    <formula>Text(leaseworks__Country__r.leaseworks__Region__c )</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Country__c/leaseworks__Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Invoice__c/leaseworks__Invoice__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageLease</customHelpPage>
    <description>Generic Object to hold Invoice information.</description>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Balance_Due__c</fullName>
    <formula>IF( OR(ISPICKVAL(leaseworks__Status__c,&#39;Declined&#39;),ISPICKVAL(leaseworks__Status__c,&#39;Cancelled&#39;)),0,  leaseworks__Total_Amount_Due__c  - (leaseworks__Amount_Paid_Remaining__c + leaseworks__Availed_Credit_Amount_Cm__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Date_of_MR_Payment_Due__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Date_of_MR_Payment_Due__c</fullName>
    <description>Date when payment is due (For MR invoices, X number of days after receiving invoice as specified in the lease. For Rent invoices, it is copied over from rent slip.)</description>
    <inlineHelpText>Payment of the invoice is due on this date. Some due dates are auto-populated but users can edit the record and enter another date.</inlineHelpText>
    <label>Date Payment Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Invoice_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Default Late Interest Invoice Date</description>
    <inlineHelpText>Default Late Interest Invoice Date</inlineHelpText>
    <label>Invoice Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Invoice_Number__c</fullName>
    <description>Unique Invoice Sequence Number</description>
    <inlineHelpText>Unique Invoice Sequence Number</inlineHelpText>
    <label>_Invoice Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Invoice_Type__c</fullName>
    <description>Note: When any invoice type is added, add the same to the {Invoice Type} field on the Invoice Line Item Object and add the dependency.</description>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aircraft MR</fullName>
                <default>true</default>
                <label>Aircraft MR</label>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
            <value>
                <fullName>Security Deposit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Non MR</fullName>
            </value>
            <value>
                <fullName>Deferred - Rent</fullName>
            </value>
            <value>
                <fullName>Deferred - MR</fullName>
            </value>
            <value>
                <fullName>HL/SL-Rent</fullName>
            </value>
            <value>
                <fullName>HL/SL-MR</fullName>
            </value>
            <value>
                <fullName>HL/SL-SD</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>HL/SL-Interest</fullName>
            </value>
            <value>
                <fullName>Broker Fee</fullName>
            </value>
            <value>
                <fullName>Agency Fee</fullName>
            </value>
            <value>
                <fullName>Other Receivables</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Default Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Lease__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease__c</fullName>
    <label>Contract</label>
    <referenceTo>leaseworks__Lease__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Lease_Id__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease_Id__c</fullName>
    <formula>leaseworks__Lease__r.leaseworks__Lease_Id__c</formula>
    <label>Lease Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Lessor_Level__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lessor_Level__c</fullName>
    <description>This field is used to set the lessor/HL in the invoice name</description>
    <label>_Lessor Level</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Total_Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Total_Amount_Due__c</fullName>
    <description>Invoice Amount plus taxes and adjustments.</description>
    <formula>leaseworks__Invoiced_Amount_Formula__c +  leaseworks__Tax_Amount_Rollup__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Invoice Amount plus taxes and adjustments.</inlineHelpText>
    <label>Total Invoiced Amount($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Type__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Type__c</fullName>
    <formula>text(leaseworks__Invoice_Type__c)  + if(isblank(leaseworks__Monthly_Utilization_Type_F__c)   ,&#39;&#39; , &#39; - &#39; +leaseworks__Monthly_Utilization_Type_F__c  )</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/leaseworks__Lease__c.object-meta.xml
<CustomObject>
    <description>Central table for Lease Agreement/contract headers, storing essential details like start/end dates, current status, and associated asset reference.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Lease_Id__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease_Id__c</fullName>
    <description>Unique Lease Number</description>
    <formula>/*(IF( !ISBLANK(Y_Hidden_Lease_Id__c), 
(&#39;Lease&#39;&amp;&#39;-&#39;&amp;RIGHT(&#39;0000&#39; &amp; TEXT( Y_Hidden_Lease_Id__c ),5)), NULL))*/ 

null</formula>
    <label>Z_Unused_2101 Lease Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Lesor__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lessor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>notEqual</operation>
            <value>Operator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leases (Lessor)</relationshipLabel>
    <relationshipName>Leases4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Lessee__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lessee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Source : Fortress. Ability to have Lessee different from Operator. Asana - Operator and Lessee could be different. Operator hierarchy needed.</description>
    <label>Z_Unused_OP Lessee</label>
    <referenceTo>leaseworks__Operator__c</referenceTo>
    <relationshipLabel>Z_Unused_OP Leases (Lessee)</relationshipLabel>
    <relationshipName>Leases_As_Lessees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Lessee_New__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lessee_New__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Source : Fortress. Ability to have Lessee different from Operator. Asana - Operator and Lessee could be different. Operator hierarchy needed.</description>
    <inlineHelpText>Lookup to Accounts. Start typing the name until a match is presented. Click the magnifying glass to see a list.</inlineHelpText>
    <label>Lessee</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Operator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leases (Lessee)</relationshipLabel>
    <relationshipName>Leases_As_Lessees_New</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Operator__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Operator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Z_Unused_OP Operator</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>leaseworks__Operator__c.leaseworks__Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Operator__c</referenceTo>
    <relationshipLabel>Z_Unused_OP Leases</relationshipLabel>
    <relationshipName>Leases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Region__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Region__c</fullName>
    <label>Z_Unused_2206 Region</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Type__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Type__c</fullName>
    <description>Type of Lease. Source : Fortress. (Asana : Fortress Misc Requirements)</description>
    <inlineHelpText>Specify Type of Lease (eg, Aircraft, Engine)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aircraft</fullName>
                <default>true</default>
                <label>Aircraft</label>
            </value>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Operator__c/leaseworks__Operator__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPage</customHelpPage>
    <description>A lessor&apos;s airline customers who operate the leased aircraft or engines</description>
    <label>Z_Unused_OP Operator</label>
    <nameField>
        <label>Z_Unused_OP Operator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Z_Unused_OP Operators</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Operator__c/fields/leaseworks__Address_Street__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Address_Street__c</fullName>
    <label>Z_Unused_OP Address Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Operator__c/fields/leaseworks__City__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__City__c</fullName>
    <label>Z_Unused_OP City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Operator__c/fields/leaseworks__Country_Lookup__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Country_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Z_Unused_OP Country</label>
    <referenceTo>leaseworks__Country__c</referenceTo>
    <relationshipLabel>Z_Unused_OP Operators</relationshipLabel>
    <relationshipName>Operators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Operator__c/fields/leaseworks__Region__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Region__c</fullName>
    <label>Z_Unused_OP Region [Deprecated]</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Latin America and Caribbean</fullName>
            </value>
            <value>
                <fullName>Middle East and Africa</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>Oceania</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Operator__c/fields/leaseworks__Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Zip_Code__c</fullName>
    <label>Z_Unused_OP Zip/Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConsolidationCoverPageController.cls
public class ConsolidationCoverPageController {
    public lessorWrapper lessorData {get;set;}
    public leseeWrapper leseeData {get;set;}
    public List<InvoiceData> lstOfInvoiceData {get;set;}
    public String invoiceData{get;set;}
    public String lesseId{get;set;}
    Public ConsolidationCoverPageController(){
        System.debug('Run the Constructor');
        leseeData = new leseeWrapper();
        lessorData = new lessorWrapper();
        lstOfInvoiceData = new List<InvoiceData>();
        invoiceData = ApexPages.currentPage().getParameters().get('selectedInvoices');
        lesseId = ApexPages.currentPage().getParameters().get('lesseId');
        getDataForCoverPage();
    }
    
    Public void getDataForCoverPage(){
        List<object> lstObjIds= (List<object>) JSON.deserializeUntyped(invoiceData);
        List<string> invIDs= new List<string> ();
        for(Object a:lstObjIds){
            invIDs.add(String.valueOf(a));
        }
        // When Object is operator
        // for(leaseworks__Operator__c objOperator : [SELECT Id, leaseworks__Address_Street__c, Name, leaseworks__City__c, leaseworks__Zip_Code__c, leaseworks__Region__c, leaseworks__Country_Lookup__r.Name FROM leaseworks__Operator__c Where Id =:  lesseId] ){
        //     leseeData.lesse_name = objOperator.Name;
        //     leseeData.lesse_address_street = objOperator.leaseworks__Address_Street__c;
        //     leseeData.lesse_city = objOperator.leaseworks__City__c;
        //     leseeData.lesse_state = objOperator.leaseworks__Region__c;
        //     leseeData.lesse_zip_code = objOperator.leaseworks__Zip_Code__c;
        //     leseeData.lesse_country = objOperator.leaseworks__Country_Lookup__r.Name;
        // }
        
        // When Object is Account
        for(Account objOperator : [SELECT Id, BillingStreet, Name, BillingCity, BillingPostalCode, leaseworks__Region__c , BillingCountry FROM Account Where Id =:  lesseId] ){
            leseeData.lesse_name = objOperator.Name;
            leseeData.lesse_address_street = objOperator.BillingStreet;
            leseeData.lesse_city = objOperator.BillingCity;
            leseeData.lesse_state = objOperator.leaseworks__Region__c;
            leseeData.lesse_zip_code = objOperator.BillingPostalCode;
            leseeData.lesse_country = objOperator.BillingCountry;
        }
        
        //When Object is Operator
        //for(leaseworks__Lease__c objLease : [SELECT Id, leaseworks__Lesor__r.Name, leaseworks__Lesor__r.BillingStreet, leaseworks__Lesor__r.BillingPostalCode, leaseworks__Lesor__r.BillingCity, leaseworks__Lesor__r.BillingState, leaseworks__Lesor__r.BillingCountry, leaseworks__Lesor__r.leaseworks__Main_Email_Address__c FROM leaseworks__Lease__c Where leaseworks__Lessee__c =:  lesseId] ){
        //When Object is Account
        for(leaseworks__Lease__c objLease : [SELECT Id, leaseworks__Lesor__r.Name, leaseworks__Lesor__r.BillingStreet, leaseworks__Lesor__r.BillingPostalCode, leaseworks__Lesor__r.BillingCity, leaseworks__Lesor__r.BillingState, leaseworks__Lesor__r.BillingCountry, leaseworks__Lesor__r.leaseworks__Main_Email_Address__c FROM leaseworks__Lease__c Where leaseworks__Lessee_New__c =:  lesseId] ){
            lessorData.lessor_name = objLease.leaseworks__Lesor__r.Name;
            lessorData.lessor_billing_street = objLease.leaseworks__Lesor__r.BillingStreet;
            lessorData.lessor_billing_city = objLease.leaseworks__Lesor__r.BillingCity;
            lessorData.lessor_billing_state = objLease.leaseworks__Lesor__r.BillingState;
            lessorData.lessor_billing_postal_code = objLease.leaseworks__Lesor__r.BillingPostalCode;
            lessorData.lessor_billing_country = objLease.leaseworks__Lesor__r.BillingCountry;
            lessorData.lessor_email = objLease.leaseworks__Lesor__r.leaseworks__Main_Email_Address__c;
        }
        
        Integer s_num = 1;
        double total_amount = 0;
        for(leaseworks__Invoice__c invObj : [SELECT Id, leaseworks__Lease__c, leaseworks__Balance_Due__c, leaseworks__Invoice_Type__c, leaseworks__Invoice_Date__c, leaseworks__Lease_Id__c, leaseworks__Lessor_Level__c, leaseworks__Type__c, leaseworks__Total_Amount_Due__c, leaseworks__Invoice_Number__c, leaseworks__Date_of_MR_Payment_Due__c FROM leaseworks__Invoice__c Where Id IN : invIDs]){
            InvoiceData invoiceDataObj = new InvoiceData();
            invoiceDataObj.s_no = s_num;
            invoiceDataObj.invoice_no = invObj.leaseworks__Invoice_Number__c;
            invoiceDataObj.invoice_type = invObj.leaseworks__Invoice_Type__c;
            invoiceDataObj.invoice_date = invObj.leaseworks__Invoice_Date__c;
            invoiceDataObj.invoice_due_date = invObj.leaseworks__Date_of_MR_Payment_Due__c;
            invoiceDataObj.invoice_amount = invObj.leaseworks__Balance_Due__c;
            total_amount += double.valueOf(invObj.leaseworks__Balance_Due__c);
            lstOfInvoiceData.add(invoiceDataObj);
            s_num++;
        }
        leseeData.invoice_amount_sum = total_amount;
    }
    
    Class leseeWrapper{
        public String lesse_name {get;set;}
        public String lesse_address_street {get;set;}
        public String lesse_city {get;set;}
        public String lesse_state {get;set;}
        public String lesse_zip_code {get;set;}
        public String lesse_country {get;set;}
        public double invoice_amount_sum {get;set;}
    }
    
    Class lessorWrapper{
        public String lessor_name {get;set;}
        public String lessor_billing_street {get;set;}
        public String lessor_billing_city {get;set;}
        public String lessor_billing_state {get;set;}
        public String lessor_billing_postal_code {get;set;}
        public String lessor_billing_country {get;set;}
        public String lessor_email {get;set;}
    }
    
    Class InvoiceData{
        public Integer s_no {get;set;}
        public String invoice_no {get;set;}
        public String invoice_type {get;set;}
        public Date invoice_date {get;set;}
        public Date invoice_due_date {get;set;}
        public double invoice_amount {get;set;}
    }
}