force-app/main/default/objects/Account/fields/leaseworks__Active__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Active__c</fullName>
    <label>Z_Unused_2206 Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interest_Calculator_Parameter__mdt/Interest_Calculator_Parameter__mdt.object-meta.xml
<CustomObject>
    <description>To specify the interest calculation values</description>
    <label>Interest Calculator Parameter</label>
    <pluralLabel>Interest Calculator Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Interest_Calculator_Parameter__mdt/fields/Compound_Interest__c.field-meta.xml
<CustomField>
    <fullName>Compound_Interest__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if the late payment interest calculation is compounded</inlineHelpText>
    <label>Compound Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interest_Calculator_Parameter__mdt/fields/Grace_Period__c.field-meta.xml
<CustomField>
    <fullName>Grace_Period__c</fullName>
    <inlineHelpText>Indicates the number of days after the due date for which interest won&#39;t be charged. Valid entries are from 1 to 365, no decimals.</inlineHelpText>
    <label>Grace Period</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interest_Calculator_Parameter__mdt/fields/Interest_Base__c.field-meta.xml
<CustomField>
    <fullName>Interest_Base__c</fullName>
    <label>Interest Base</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>360</fullName>
                <default>true</default>
                <label>360</label>
            </value>
            <value>
                <fullName>365</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interest_Calculator_Parameter__mdt/fields/Interest_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Interest_Calculation_Method__c</fullName>
    <label>Interest Calculation Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Previous Balance</fullName>
                <default>true</default>
                <label>Previous Balance</label>
            </value>
            <value>
                <fullName>Adjusted Balance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/leaseworks__Lease__c.object-meta.xml
<CustomObject>
    <description>Central table for Lease Agreement/contract headers, storing essential details like start/end dates, current status, and associated asset reference.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Lease__c/fields/Grace_Period__c.field-meta.xml
<CustomField>
    <fullName>Grace_Period__c</fullName>
    <inlineHelpText>Grace period after expiry date</inlineHelpText>
    <label>Grace Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Active__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Active__c</fullName>
    <description>Active? Lease checkbox for reporting. Driven by Lease Start and Lease End/Redelivery date, based on Setup -&gt; Custom Settings -&gt; Leaseworks Settings -&gt; Active Lease logic. Active? Override field on the Lease page can override the calculation formula when selected by user</description>
    <formula>If(
        (ISPICKVAL( leaseworks__Active_Override__c ,&#39;Default&#39;) || ISBLANK(TEXT( leaseworks__Active_Override__c ))) , 
        AND(leaseworks__Lease_Start_Date_New__c &lt;= TODAY(),
        
        IF($Setup.leaseworks__LeaseWorksSettings__c.leaseworks__Active_Lease_Logic__c=&#39;Redelivery Date&#39;,
        true,
        leaseworks__Lease_End_Date_New__c&gt;= TODAY()
        ),
        
        (TEXT(leaseworks__Lease_Type_Status__c)==&#39;On Lease&#39;),
        !ISBLANK(leaseworks__Aircraft__c) ),If(ISPICKVAL( leaseworks__Active_Override__c ,&#39;Active&#39;),True,False))</formula>
    <inlineHelpText>Active? Lease checkbox for reporting. Driven by Lease Start and Lease End or Redelivery date based on the configuration. Active? Override field on the Lease page can override the calculation formula when selected by user</inlineHelpText>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Lessee_New__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lessee_New__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Source : Fortress. Ability to have Lessee different from Operator. Asana - Operator and Lessee could be different. Operator hierarchy needed.</description>
    <inlineHelpText>Lookup to Accounts. Start typing the name until a match is presented. Click the magnifying glass to see a list.</inlineHelpText>
    <label>Lessee</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Operator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leases (Lessee)</relationshipLabel>
    <relationshipName>Leases_As_Lessees_New</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Operator_New__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Operator_New__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operator</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Operator</value>
        </filterItems>
        <filterItems>
            <field>Account.leaseworks__Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leases (Operator)</relationshipLabel>
    <relationshipName>Leases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InterestInvoiceCalculatorController.cls
/**
* @description : This class is for getting the lessee records and calling the batch class, also checking is there any batch is running for the same.
To execute this class you have to go on interest studio, select lessee, invoice type, month, year and need to calculate interest.
* @author : abhishek.qa@lease-works.com.sndboxfull
* @group : 
* @last modified on : 12-09-2024
* @ last modified by : Smrati Jain
**/
public with sharing class InterestInvoiceCalculatorController {
        
    @AuraEnabled
    public static list<Account> getLesseeRecords(string searchKey) {
        Set<Id> operatorIds = new Set<Id>();
        Set<Id> lesseeIds = new Set<Id>();
        Set<Id> leaseIds = new Set<Id>();
        List<leaseworks__Lease__c> leases = [SELECT leaseworks__Operator_New__c, leaseworks__Lessee_New__c, leaseworks__Active__c FROM leaseworks__Lease__c WHERE leaseworks__Active__c = true LIMIT 50000];
        for (leaseworks__Lease__c lease : leases) {
            if (lease.leaseworks__Operator_New__c != null) {
                operatorIds.add(lease.leaseworks__Operator_New__c);
            }
            if (lease.leaseworks__Lessee_New__c != null) {
                lesseeIds.add(lease.leaseworks__Lessee_New__c);
            }
        }
        leaseIds.addAll(operatorIds);
		leaseIds.addAll(lesseeIds);
        list<Account> acc = [SELECT Id,Name,Type FROM Account WHERE Id IN : leaseIds AND Name LIKE : '%' + searchKey + '%' LIMIT 50000];
        return acc; 
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Interest_Calculator_Parameter__mdt> getSetupRecord() {
        List<Interest_Calculator_Parameter__mdt> setupRecords = [SELECT MasterLabel, Interest_Base__c, Interest_Calculation_Method__c, Grace_Period__c, Compound_Interest__c FROM Interest_Calculator_Parameter__mdt where MasterLabel = 'Setup'];
        if(setupRecords.size() > 0){
            return setupRecords; 
        }
        return null; 
    }
    
    @AuraEnabled
    public static String refreshTransactions(List<String> selectedLesseIdList, List<String>selectedInvoiceTypeLabelList, String month ,Integer year){
        String Status = '';
        String currentUserMailId = userInfo.getUserEmail();
        try {
            ApexClass aC = [SELECT Id,Name FROM ApexClass WHERE Name = 'BatchCreateDefaultInterestInvoice' LIMIT 1];
            if([SELECT count() FROM AsyncApexJob WHERE JobType='BatchApex' AND  ApexClassID =:aC.Id AND (Status = 'Processing' OR Status = 'Preparing' OR  Status = 'Queued' OR  Status = 'Holding')] < 1){
                BatchCreateDefaultInterestInvoice batchInvoiceObj = new BatchCreateDefaultInterestInvoice(selectedLesseIdList,month,year,selectedInvoiceTypeLabelList,currentUserMailId);
                Database.executeBatch(batchInvoiceObj,1);    
                Status = 'Success';
            }
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
        return Status;
    }
    
}