force-app/main/default/objects/leaseworks__Bulk_Invoice_Process_Request_Line_Log__c/leaseworks__Bulk_Invoice_Process_Request_Line_Log__c.object-meta.xml
<CustomObject>
    <label>Bulk Invoice Process Request Line Log</label>
    <nameField>
        <label>Bulk Invoice Process Request Line Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bulk Invoice Process Request Line Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Bulk_Invoice_Process_Request_Line_Log__c/fields/leaseworks__Comments__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/leaseworks__Bulk_Invoice_Process_Request_Line_Log__c/fields/leaseworks__Link_to_Invoice__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Link_to_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to display the invoice connected to Bulk Invoice process request line log.</description>
    <inlineHelpText>The invoice connected to Bulk Invoice process request line log.</inlineHelpText>
    <label>Link to Invoice</label>
    <referenceTo>leaseworks__Invoice__c</referenceTo>
    <relationshipLabel>Bulk Invoice Process Request Line Logs (Link to Invoice)</relationshipLabel>
    <relationshipName>Bulk_Invoice_Process_Request_Line_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Exception_Log__c/leaseworks__Exception_Log__c.object-meta.xml
<CustomObject>
    <description>An object to keep track of exceptions that cannot be shown to the end users. E.g. exceptions from future methods.</description>
    <label>Exception Log</label>
    <nameField>
        <label>Exception Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Exception_Log__c/fields/leaseworks__Additional_Message__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Additional_Message__c</fullName>
    <label>Additional Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Exception_Log__c/fields/leaseworks__Detailed__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Detailed__c</fullName>
    <label>Detailed Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/leaseworks__Exception_Log__c/fields/leaseworks__Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Exception_Log__c/fields/leaseworks__Objects_In_Context__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Objects_In_Context__c</fullName>
    <label>Objects In Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Exception_Log__c/fields/leaseworks__Record_Ids__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Record_Ids__c</fullName>
    <description>Record in context. Comma separated list if multiple records in context.</description>
    <label>Record Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Exception_Log__c/fields/leaseworks__Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Exception_Log__c/fields/leaseworks__Trigger_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Trigger_Event_Type__c</fullName>
    <label>Trigger Event Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Exception_Log__c/fields/leaseworks__Type__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
                <default>true</default>
                <label>Error</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Exception_Log__c/fields/leaseworks__User_In_Context__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__User_In_Context__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User In Context</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Exception_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__LW_Setup__c/leaseworks__LW_Setup__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Leaseworks Setup</label>
</CustomObject>

force-app/main/default/objects/leaseworks__LW_Setup__c/fields/leaseworks__Disable__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Disable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inactive?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/leaseworks__LW_Setup__c/fields/leaseworks__Value__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Power_BI_Auth_Settings__mdt/leaseworks__Power_BI_Auth_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Power BI Auth Settings</label>
    <pluralLabel>Power BI Auth Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/leaseworks__Power_BI_Auth_Settings__mdt/fields/leaseworks__ClientId__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__ClientId__c</fullName>
    <description>Application Id/ Client Id is created in the Azure AD and used to configure the project&#39;s support for Client Credentials Flow.</description>
    <label>ClientId</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/leaseworks__Power_BI_Auth_Settings__mdt/fields/leaseworks__ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__ClientSecret__c</fullName>
    <description>Client Secret is created in the Azure AD and used to configure the project&apos;s support for Client Credentials Flow.</description>
    <label>ClientSecret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Power_BI_Auth_Settings__mdt/fields/leaseworks__Embedded_Report_Url__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Embedded_Report_Url__c</fullName>
    <description>Url for embedding the report 
Eg : &apos;https://api.powerbi.com/v1.0/myorg/groups/&apos; + WorkspaceId + &apos;/reports/&apos; + ReportId + &apos;/GenerateToken&apos;;</description>
    <label>Embedded Report Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/leaseworks__Power_BI_Auth_Settings__mdt/fields/leaseworks__Login_Url_part1__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Login_Url_part1__c</fullName>
    <description>Login url part 1 for the powerBI endPoint : 
Eg: https://login.microsoftonline.com/</description>
    <label>Login Url_part1</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/leaseworks__Power_BI_Auth_Settings__mdt/fields/leaseworks__Login_Url_part2__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Login_Url_part2__c</fullName>
    <description>Login url part 2 for the powerBI endPoint : 
Eg: /oauth2/v2.0/token</description>
    <label>Login Url part2</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Power_BI_Auth_Settings__mdt/fields/leaseworks__Report_Url__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Report_Url__c</fullName>
    <description>Url for the report
Eg : https://api.powerbi.com/v1.0/myorg/groups/</description>
    <label>Report Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/leaseworks__Power_BI_Auth_Settings__mdt/fields/leaseworks__Scope__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Scope__c</fullName>
    <description>https://analysis.windows.net/powerbi/api/.default</description>
    <label>Scope</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/leaseworks__Power_BI_Auth_Settings__mdt/fields/leaseworks__TenantId__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__TenantId__c</fullName>
    <description>Tenant Id is created in the Azure AD and used to configure the project&#39;s support for Client Credentials Flow.</description>
    <label>TenantId</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PowerBIReportUtil.cls
/*

***********************************************************************

Apex Class Name    : PowerBIReportUtil

@description       : Utility Class for Power Bi Report Builder Integration
***********************************************************************/

public without sharing class PowerBIReportUtil {
    public static leaseworks__Power_BI_Auth_Settings__mdt authSetting;
   
    @TestVisible
    static List<leaseworks__Power_BI_Auth_Settings__mdt> powerBiConfigurationMappings{
        get{
            if(powerBiConfigurationMappings == NULL){
                powerBiConfigurationMappings = [SELECT leaseworks__ClientId__c,leaseworks__ClientSecret__c,leaseworks__Embedded_Report_Url__c,leaseworks__Login_Url_part1__c,leaseworks__Login_Url_part2__c,Label,leaseworks__Report_Url__c,
                                                leaseworks__Scope__c,leaseworks__TenantId__c FROM leaseworks__Power_BI_Auth_Settings__mdt ];
            }
            return powerBiConfigurationMappings;
        }
        set;
    }
   
    /**
* @description :Method to fetch the accessToken for the customMetaData
*  
* @param  : customMetadata name.
* @throws : Error Message to display on UI
**/
    public static String getPowerBiAccessToken(String customMetadataName) {
        authSetting = fetchAuthSettingVal(customMetadataName);
        string tenantId = '';    
        string clientId = '';    
        string clientSecret = '';
        string powerbiEndpoint = '';//construct URL for client credentials flow
        string postDataScope = '';
        System.debug('authSetting : '+authSetting);
       
        if(authSetting != null){
            tenantId = authSetting.leaseworks__TenantId__c;    
            clientId = authSetting.leaseworks__ClientId__c;    
            clientSecret = authSetting.leaseworks__ClientSecret__c;  
            postDataScope = authSetting.leaseworks__Scope__c;
            powerbiEndpoint = authSetting.leaseworks__Login_Url_part1__c + TenantId + authSetting.leaseworks__Login_Url_part2__c;
        }
       
        
        HttpRequest reqClientCredentialsFlow = new HttpRequest();
        reqClientCredentialsFlow.setMethod('POST');
        reqClientCredentialsFlow.setEndpoint(powerbiEndpoint);        
        reqClientCredentialsFlow.setHeader('Content-Type', 'application/x-www-form-urlencoded');
       
       
        ClientCredentialPostData postData = new ClientCredentialPostData();
        postData.client_id = clientId;
        postData.client_info = '1';
        postData.client_secret = clientSecret;
        postData.scope = postDataScope;
        postData.grant_type = 'client_credentials';        
        String postBody = postData.getPostData();
        reqClientCredentialsFlow.setBody(postBody);
        System.debug('postBody : '+postBody);
        System.debug('Callouts so farb1: ' + Limits.getCallouts());
      
        Http http = new Http();   
        //  HTTP request to get access token
        HttpResponse response = http.send(reqClientCredentialsFlow);
        System.debug('response : '+response);
        
        String responseJson = response.getBody();
       
        System.debug('responseJson : '+responseJson);
        ClientCredentialResponse responseData = (ClientCredentialResponse)JSON.deserialize(responseJson, ClientCredentialResponse.class);
        String access_token = responseData.access_token;    
        
        return access_token;
       
    }
   
 
    /**
* @description :Method to fetch the configuration data of the authSettings created using the customMetadata Name
*  
* @param  : customMetadataName
* @throws : Error Message to display on UI
**/
    public static leaseworks__Power_BI_Auth_Settings__mdt fetchAuthSettingVal(String customMetadataName){
        leaseworks__Power_BI_Auth_Settings__mdt authSetting;
        try{
            // get auth settings from Custom Metadata Type record
            if(!Test.isRunningTest()){
                authSetting = leaseworks__Power_BI_Auth_Settings__mdt.getInstance(customMetadataName);
            }
            else{
                for(leaseworks__Power_BI_Auth_Settings__mdt mdt: powerBiConfigurationMappings){
                    authSetting = mdt;
                }
               
            }
            return authSetting;
        }
        catch(exception e){
            throw new AuraHandledException('The Custom-MetaData Setting name is Incorrect.Please check the Custom-MetaData Setting name in the report configuration.');
        }
    }
   
    public class ClientCredentialPostData {
        public String client_id;
        public String client_info;
        public string client_secret;
        public String scope;
        public string grant_type;
        public String getPostData(){
            return 'client_id=' + this.client_id +
                '&client_info=' + this.client_info +
                '&client_secret=' + this.client_secret +
                '&scope=' + this.scope +
                '&grant_type=' + grant_type;
        }
    }
   
    public class ClientCredentialResponse {
        public String access_token;
        public String expires_in;
        public String ext_expires_in;
        public String token_type;
    }
        /**
* @description :Method called from flow, Invokes PowerBI Download Request
 * @param  : list of records Ids
* @throws : none
**/
   @InvocableMethod(label='Power Bi Invocation')
    public static void invokePowerBi(List<Id> recordIds) {
       Id recordId=id.valueof(recordIds[0]);
       String objectName = recordId.getSObjectType().getDescribe().getName();
        
       Set<Id> setIds = new Set<Id>(recordIds);
       Boolean isAccessTokenGenerated=true;
       String accesstoken;
       try{
             accesstoken = PowerBIReportUtil.getPowerBiAccessToken('PowerBiReportBuilder');
        }
        catch(Exception e ){
            isAccessTokenGenerated=false;
            //exception log
            ////add map from azorradevsb
        }
        if(isAccessTokenGenerated && !(String.isBlank(accesstoken))){
            database.executebatch(new BatchPowerBIInvokeDownloadRequest(setIds, accesstoken,objectName,False,0),1);
        }
      
         
    
    }
      public static string getLWSetup_CS(string TypeStr){
        leaseworks__LW_Setup__c lwSetup = leaseworks__LW_Setup__c.getValues(TypeStr);
        if(!isSetupDisabled(TypeStr) && lwSetup!=null  ) return lwSetup.leaseworks__value__c ;
        return null;
    }
        public static boolean isSetupDisabled(string TypeStr){
        leaseworks__LW_Setup__c lwSetup = leaseworks__LW_Setup__c.getValues(TypeStr);
        if(lwSetup!=null) return lwSetup.leaseworks__Disable__c ;
        return false;
    }
        /**
* @description :Method to send Email if error occurs on induvidual record generation
 * @param  : subject,errorMessage
* @throws : none
**/
    public static void sendEmailonError(string subject,string errorMessage){
        leaseworks.LWGlobalUtils.sendEmailToLWAdmins(subject,errorMessage);

    }
    
 /**
* @description :Method to update Line Logs of errors during Bulk Invoice Generation
*  
* @param  : subject,errorMessage
* @throws : none
**/
     public static void updateLineLog(string recordId,string errorMessage){
        	leaseworks__Bulk_Invoice_Process_Request_Line_Log__c lineLog=[SELECT Id,leaseworks__Comments__c,leaseworks__Link_to_Invoice__c  from leaseworks__Bulk_Invoice_Process_Request_Line_Log__c where leaseworks__Link_to_Invoice__c =: recordID order by createddate desc limit 1 ];
                    lineLog.leaseworks__Comments__c=errorMessage;
                    leaseworks.LWGlobalUtils.setTriggersAndWFsOff();
                    update lineLog;
                    leaseworks.LWGlobalUtils.setTriggersAndWFsOn();

    }
 /**
* @description :Method to create Exception logs if any error occurs
*  
* @param  : subject,errorMessage,recordId,batchName
* @throws : none
**/
    public static void createExceptionLog(string name,string process,string errorMessage,string recordId){
        	leaseworks__Exception_Log__c newEL = new leaseworks__Exception_Log__c(Name=name, leaseworks__Stack_Trace__c='',
			                                                                      leaseworks__Exception_Message__c='Error while running '+process +' batch for PowerBI Document Generation ', leaseworks__Additional_Message__c='', leaseworks__Objects_In_Context__c='',
			                                                                      leaseworks__Record_Ids__c=recordId, leaseworks__User_In_Context__c=System.UserInfo.getUserId()
			                                                                      , leaseworks__Detailed__c =errorMessage ,leaseworks__Type__c = 'API Call'
			                                                                      ,leaseworks__Trigger_Event_Type__c = '' );
             insert newEL;

    }
    public static string convertMonth(date d ){
        Datetime dt = DateTime.newInstance(d, Time.newInstance(0,0,0,0));
        String monthName = dt.format('MMM');
        string year = dt.format('YY');
        monthName = monthName+'-'+year;
        return monthName;
    }
   
}