force-app/main/default/objects/leaseworks__PBH_Rent_Per_Assembly__c/leaseworks__PBH_Rent_Per_Assembly__c.object-meta.xml
<CustomObject>
    <label>PBH Rent Assembly</label>
    <nameField>
        <label>PBH Rent Per Assembly Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBH Rent Assemblies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__PBH_Rent_Per_Assembly__c/fields/leaseworks__PBH_Rent_Rate__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__PBH_Rent_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PBH Rent Rate</label>
    <referenceTo>leaseworks__PBH_Rent_Rate__c</referenceTo>
    <relationshipName>PBH_Amount_Per_Assemblies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__PBH_Rent_Per_Assembly__c/fields/leaseworks__Rent_Schedule__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Rent_Schedule__c</fullName>
    <label>Rent Schedule</label>
    <referenceTo>leaseworks__Rent__c</referenceTo>
    <relationshipName>PBH_Amount_Per_Assemblies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/leaseworks__PBH_Rent_Rate__c/leaseworks__PBH_Rent_Rate__c.object-meta.xml
<CustomObject>
    <description>Capture the PBH related field details such as which Assemblies has been chosen and Rates
If applicable and the Rent Type is PBH, provide details of the PBH Rent calculation, including charge items per FH and FC.
[MODULE: Contract]
[LOAD: Yes]
[PREREQUISITES: Rent Schedule (PBH)]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>PBH Rate</label>
    <nameField>
        <label>PBH Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PBH Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__PBH_Rent_Rate__c/fields/leaseworks__Multi_Rent_Schedule__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Multi_Rent_Schedule__c</fullName>
    <label>Multi Rent Schedule</label>
    <referenceTo>leaseworks__Stepped_Rent__c</referenceTo>
    <relationshipLabel>PBH Rent Rates</relationshipLabel>
    <relationshipName>PBH_Rent_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/leaseworks__Rent__c/leaseworks__Rent__c.object-meta.xml
<CustomObject>
    <description>Rent Slips, typically generated monthly for each Rent Schedule, detail rent calculations like amounts and cost breakdowns. They trigger invoice generation per payment cycle, usually done automatically by Rent Studio. But for importing data from other systems or new leases, manual upload via a data loader is also possible.
Rent Slips for Rent Type &apos;Fixed&apos;, &apos;Floating&apos;, &apos;Seasonal&apos;, &apos;PBH&apos;, typically generated monthly for each Rent Schedule, detail rent calculations like amounts and cost breakdowns. They trigger invoice generation per payment cycle, usually done automatically by Rent Studio. But for importing data from other systems or new leases, manual upload via a data loader is also possible.
[MODULE: Contract]
[LOAD: Optional]
[PREREQUISITES: Rent Schedule]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Rent Slip</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rent Slip</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Rent__c/fields/leaseworks__For_Month_Ending__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__For_Month_Ending__c</fullName>
    <defaultValue>date(year(today())+(if(month(today())&gt;=11,1,0)),
(mod(month(today()),12)+2),
1)-1</defaultValue>
    <description>Changing to default to end of next month. Source: Fortress.
Date Due will be made optional.</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Rent__c/fields/leaseworks__Rent_Type__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Rent_Type__c</fullName>
    <formula>TEXT(leaseworks__Stepped_Rent__r.leaseworks__Rent_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rent Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Rent__c/fields/leaseworks__Stepped_Rent__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Stepped_Rent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Step Rent Record(Rent Schedule)</description>
    <inlineHelpText>Lookup to Rent Schedule(Step Rent)</inlineHelpText>
    <label>Rent Schedule</label>
    <referenceTo>leaseworks__Stepped_Rent__c</referenceTo>
    <relationshipLabel>Rent Slip</relationshipLabel>
    <relationshipName>Rent_Period</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Stepped_Rent__c/leaseworks__Stepped_Rent__c.object-meta.xml
<CustomObject>
    <description>This lease-level configuration table houses Rent Schedule parameters, including start/end dates and base rent. While typically a single schedule exists per lease, exceptions involving rent type changes (fixed to PBH, etc.) necessitate additional schedules. Users leverage Rent Studio to manage these schedules, generating rent slips and subsequent invoices.
If Applicable and the Rent Type can be Fixed, Floating, Seasonal, PBH.
This lease-level configuration table houses Rent Schedule parameters, including start/end dates and base rent. While typically a single schedule exists per lease, exceptions involving rent type changes (fixed to PBH, etc.) necessitate additional schedules. Users leverage Rent Studio to manage these schedules, generating rent slips and subsequent invoices.
[MODULE: Contract]
[LOAD: Yes]
[PREREQUISITES: Lease]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Rent Schedule</label>
    <nameField>
        <label>Rent Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rent Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Stepped_Rent__c/fields/leaseworks__Rent_Type__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Rent_Type__c</fullName>
    <description>Types of monthly rent calculations. For variable Rent: there will be a base (say $100), a multiplier (say 1.1) and will be tied to Libor (say its 2% for a certain mo). Calculation would be 100*1.1 = 110. and then adjust down by 2% (calculated on 100). So net amount would be 108. Also, may have a floor or ceiling. If the ceiling is 107, then you pay 107 instead of 108.
Base
Multiplier
Libor
Value = Base * Multiplier - (Base*LIBOR)</description>
    <inlineHelpText>Rent Type per the Lease</inlineHelpText>
    <label>Rent Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Rent</fullName>
                <default>true</default>
                <label>Fixed Rent</label>
            </value>
            <value>
                <fullName>Floating Rent</fullName>
            </value>
            <value>
                <fullName>Power By The Hour</fullName>
            </value>
            <value>
                <fullName>Seasonal Rent</fullName>
            </value>
            <value>
                <fullName>Manual Rent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Stepped_Rent__c/fields/leaseworks__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Start_Date__c</fullName>
    <inlineHelpText>The first day of the first Rent Slip of this Rent Schedule. By default it is the Lease Start Date or the day after the last day of the previous Rent Schedule.</inlineHelpText>
    <label>Rent Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestLocalSript.cls
public class TestLocalSript {
    
    public static void TestMissingPBHRentAssembly(){

        String msg = '';
        set<id> rentScheduleId = new set<id>();     
        Map<id,List<leaseworks__Rent__c>> mapRentSchIdToRentSlip = new  Map<id,List<leaseworks__Rent__c>>();
        
        for(leaseworks__Rent__c rentSlip :[SELECT Id, name, leaseworks__rent_type__c,leaseworks__Start_Date__c, 
                                                      leaseworks__For_Month_Ending__c,leaseworks__Stepped_Rent__c  FROM leaseworks__Rent__c
                                                      where leaseworks__rent_type__c = 'Power By The Hour' AND 
                                                     Id not in (select  leaseworks__Rent_Schedule__c from leaseworks__PBH_Rent_Per_Assembly__c 
                                                                where leaseworks__Rent_Schedule__c != null)]){
            if(mapRentSchIdToRentSlip.keyset().contains(rentSlip.leaseworks__Stepped_Rent__c)){
                 mapRentSchIdToRentSlip.get(rentSlip.leaseworks__Stepped_Rent__c).add(rentslip);                                                      
            }else{
                mapRentSchIdToRentSlip.put(rentSlip.leaseworks__Stepped_Rent__c,new list<leaseworks__Rent__c>());  
            }
                                                                    
        }
    
        List<leaseworks__PBH_Rent_Rate__c> listRates = [select id, name,leaseworks__Multi_Rent_Schedule__c from leaseworks__PBH_Rent_Rate__c where leaseworks__Multi_Rent_Schedule__c in:mapRentSchIdToRentSlip.keyset() ];
        for(leaseworks__PBH_Rent_Rate__c pbhRates :listRates){
            msg += 'PBH rent assembly missing for ---' + pbhRates.leaseworks__Multi_Rent_Schedule__c + '\n';
            if(mapRentSchIdToRentSlip.get(pbhRates.leaseworks__Multi_Rent_Schedule__c).size()>0){
            	msg += '\t\tRent slip with missing PBH rent assembly:\n';
            	for(leaseworks__Rent__c rentSlip :mapRentSchIdToRentSlip.get(pbhRates.leaseworks__Multi_Rent_Schedule__c)){
                	msg += '\t\t\trent slip :' + rentslip.id  + '\n';
            	}   
            }
            
        }
        system.debug(msg);
    }

}