force-app/main/default/objects/leaseworks__Invoice__c/leaseworks__Invoice__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageLease</customHelpPage>
    <description>Generic Object to hold Invoice information.</description>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Accounting_Description__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Accounting_Description__c</fullName>
    <label>_Accounting Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Date_Invoice_Sent__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Date_Invoice_Sent__c</fullName>
    <description>This field is used to determine when the Invoice record was sent.</description>
    <label>Date Invoice Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Invoice_Sent__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Invoice_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Source: Fortress</description>
    <inlineHelpText>Has the invoice been sent?</inlineHelpText>
    <label>Invoice Sent?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Invoice_Type__c</fullName>
    <description>Note: When any invoice type is added, add the same to the {Invoice Type} field on the Invoice Line Item Object and add the dependency.</description>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aircraft MR</fullName>
                <default>true</default>
                <label>Aircraft MR</label>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
            <value>
                <fullName>Security Deposit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Non MR</fullName>
            </value>
            <value>
                <fullName>Deferred - Rent</fullName>
            </value>
            <value>
                <fullName>Deferred - MR</fullName>
            </value>
            <value>
                <fullName>HL/SL-Rent</fullName>
            </value>
            <value>
                <fullName>HL/SL-MR</fullName>
            </value>
            <value>
                <fullName>HL/SL-SD</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>HL/SL-Interest</fullName>
            </value>
            <value>
                <fullName>Broker Fee</fullName>
            </value>
            <value>
                <fullName>Agency Fee</fullName>
            </value>
            <value>
                <fullName>Other Receivables</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Default Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Invoiced_Amount_Formula__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Invoiced_Amount_Formula__c</fullName>
    <description>This field displays the sum of Initial Invoiced Amount and Total Adjustments made to this invoice</description>
    <formula>leaseworks__Amount__c +   leaseworks__Total_Adjustment_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field displays the sum of Initial Invoiced Amount and Total Adjustments made to this invoice</inlineHelpText>
    <label>Adjusted Invoiced Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loop__DDP__c/Loop__DDP__c.object-meta.xml
<CustomObject>
    <customHelpPage>Loop__aboutloop</customHelpPage>
    <description>Nintex DocGen Packages</description>
    <label>DocGen Package</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocGen Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loop__DDP_Integration_Option__c/Loop__DDP_Integration_Option__c.object-meta.xml
<CustomObject>
    <description>Delivery Options for DocGen Packages</description>
    <label>Delivery Option</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loop__DDP_Integration_Option__c/fields/Loop__DDP__c.field-meta.xml
<CustomField>
    <fullName>Loop__DDP__c</fullName>
    <label>DocGen Package</label>
    <referenceTo>Loop__DDP__c</referenceTo>
    <relationshipName>Custom_Integration_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SendInvDDP.cls
global class SendInvDDP {
    public static String MR_INVOICE_PACKAGE_NAME = 'MR Invoice';
    public static String RENT_INVOICE_PACKAGE_NAME = 'Rent Invoice';
    //In the class there is dynamic Id 'deployKey' which holds the id of Report Delivery Option. 
    //For this never forget to create Email Delivery option under Rent Invoice DDP Report.
    public class MissingDDPInfoException extends Exception { }
    
    webService static string sendDDP(List<Id> ids, string Itype) {
        try{
            system.debug('param list ids='+ids +'=Itype=' +Itype);
            
            Map<String,String> deployKeyMap = new Map<String,String>();
            Map<String,String> ddpNameIdMap = new Map<String,String>();
            
            // CHANGE ANY FILTER (WHERE) CRITERIA NECESSARY
            List<Loop__DDP__c> ddps = [SELECT Id, Name, (SELECT Id FROM Loop__Custom_Integration_Options__r WHERE Recordtype.Name = 'Email') FROM Loop__DDP__c WHERE (Name =: MR_INVOICE_PACKAGE_NAME OR Name =: RENT_INVOICE_PACKAGE_NAME)];
            System.debug('list ddps='+ddps);
            
            if (ddps == null || ddps.size() < 1) {
                // CHANGE THE EXCEPTION MESSAGE IF DESIRED
                throw new MissingDDPInfoException('A DDP specified was not found.');
            }
            else {
                for (Loop__DDP__c ddp : ddps) {
                    if (ddp.Loop__Custom_Integration_Options__r == null || ddp.Loop__Custom_Integration_Options__r.size() < 1){
                        // CHANGE THE EXCEPTION MESSAGE IF DESIRED
                        throw new MissingDDPInfoException('A Delivery Option specified was not found.');
                    }
                    for(Loop__DDP_Integration_Option__c lcio : ddp.Loop__Custom_Integration_Options__r){
                        if(!deployKeyMap.containsKey(ddp.Id)){
                            deployKeyMap.put(ddp.Id, lcio.Id);
                            ddpNameIdMap.put(ddp.Name, ddp.Id);
                        }  
                    }
                }
                system.debug('ddpNameIdMap'+ddpNameIdMap);
                system.debug('deployKeyMap'+deployKeyMap);
            }
            
            // GET RECORDS TO RUN DDPS FOR
            Map<Id, List<leaseworks__Invoice__c >> ddpIdsAndObjects = new Map<Id, List<leaseworks__Invoice__c >>();
            List<leaseworks__Invoice__c> soqlList = [SELECT Id, leaseworks__Accounting_Description__c,Name,leaseworks__Invoiced_Amount_Formula__c, leaseworks__Invoice_Sent__c,leaseworks__Date_Invoice_Sent__c, leaseworks__Invoice_Type__c FROM leaseworks__Invoice__c  WHERE Id IN :ids];
            
            for (leaseworks__Invoice__c so : soqlList) {
                if (so.leaseworks__Invoice_Type__c == 'Rent') {
                    if (ddpNameIdMap.containsKey(RENT_INVOICE_PACKAGE_NAME) && ddpNameIdMap.get(RENT_INVOICE_PACKAGE_NAME) != null && !ddpIdsAndObjects.containsKey(ddpNameIdMap.get(RENT_INVOICE_PACKAGE_NAME))) {
                        ddpIdsAndObjects.put(ddpNameIdMap.get(RENT_INVOICE_PACKAGE_NAME), new List<leaseworks__Invoice__c >());
                    }
                    ddpIdsAndObjects.get(ddpNameIdMap.get(RENT_INVOICE_PACKAGE_NAME)).add(so);
                }
                else if (so.leaseworks__Invoice_Type__c == 'Aircraft MR') {
                    if (ddpNameIdMap.containsKey(MR_INVOICE_PACKAGE_NAME) && ddpNameIdMap.get(MR_INVOICE_PACKAGE_NAME) != null && !ddpIdsAndObjects.containsKey(ddpNameIdMap.get(MR_INVOICE_PACKAGE_NAME))) {
                        ddpIdsAndObjects.put(ddpNameIdMap.get(MR_INVOICE_PACKAGE_NAME), new List<leaseworks__Invoice__c >());
                    }
                    ddpIdsAndObjects.get(ddpNameIdMap.get(MR_INVOICE_PACKAGE_NAME)).add(so);
                }
            }
            system.debug('ddpIdsAndObjects====='+ddpIdsAndObjects);
            system.debug('soqlList====='+soqlList);
            
            Loop.loopMessage lm = new Loop.loopMessage();
            // SESSION ID NEEDED IF IT CANNOT BE DETERMINED FROM UserInfo.getSessionId()
            lm.sessionId = UserInfo.getSessionId();
            
            // SET DESIRED BATCH NOTIFICATION. IF THIS IS NOT DONE, THE DEFAULT IS 'NONE'
            // THIS IS AVAILABLE IN LOOP 6.7 / 9.56 AND ABOVE
            lm.batchNotification = Loop.loopMessage.Notification.BEGIN_AND_COMPLETE;
            //lm.batchNotification = Loop.loopMessage.Notification.ON_COMPLETE;
            //lm.batchNotification = Loop.loopMessage.Notification.ON_ERROR;
            
            // LOOP THROUGH WHATEVER COLLECTIONS NECESSARY FOR THE DDP REQUESTS
            for (Id ddpId : ddpIdsAndObjects.keySet()) {
                for (leaseworks__Invoice__c myObject : ddpIdsAndObjects.get(ddpId)) {
                    system.debug('My Delivery Option Deploykey ='+deployKeyMap.get(ddpId));
                    
                    if(deployKeyMap.get(ddpId) != null){
                        // ADD A DDP RUN REQUEST
                        system.debug('myObject====='+myObject);
                        lm.requests.add(new Loop.loopMessage.loopMessageRequest(
                            myObject.Id, // MAIN RECORD ID - SAME OBJECT AS THE DDP RECORD TYPE SPECIFIES
                            ddpId, // DDP ID
                            new Map<string, string>{
                                'deploy' => deployKeyMap.get(ddpId)// THIS COULD BE A DELIVERY OPTION ID INSTEAD
                                    //'deploy' => 'a2s0Y00000017wS' // THIS COULD BE A DELIVERY OPTION ID INSTEAD
                                    // 'SFAccount' => myObject.Account__c,  a2oc000000KtCnK
                                    // 'SFContact' => myObject.Contact__c
                                    // THESE PARAMETERS ARE THE SAME AS THOSE FOUND IN OUR OUTBOUND MESSAGE DOCUMENTATION
                                    // PLEASE REFERENCE THAT DOCUMENTATION FOR ADDITIONAL OPTIONS
                                    // 'attachIds' => attachmentIdsVariable
                                    // 'deploytype' => 'autodocusign' // IF deploy IS A DOCUSIGN DELIVERY OPTION ID
                                    // 'deploytype' => 'autoemail' // IF deploy IS AN EMAIL DELIVERY OPTION ID
                                    }
                        ));
                    }
                }
            }
            
            // SEND ALL DDP RUN REQUESTS IN A SINGLE CALL OUT
            if (!Test.isRunningTest()) { 
                lm.sendAllRequests();
                system.debug('lm====='+lm);
            } else { 
                system.debug('No API Requests for Test Class');
            }
            
            System.debug('soqlList b: '+soqlList);
            //updatig the Email sent record into object database
            for (leaseworks__Invoice__c  soqlI : soqlList) {
                soqlI.leaseworks__Invoice_Sent__c = true;
                soqlI.leaseworks__Date_Invoice_Sent__c =  system.today();
                
                leaseworks.LWGlobalUtils.setTriggersflagOn();
                update soqlI;
                leaseworks.LWGlobalUtils.setTriggersflagOff();
            }
            System.debug('soqlList a: '+soqlList);
            return 'Your requests are being processed.';
        }
        catch(Exception ex){
            System.debug('Error: '+ex.getMessage()+' at line number:'+ex.getLineNumber()+' --- '+ex.getStackTraceString());
        }
        return '';
    }
    
    public static void superTest(){
        Integer i=0;
        i++;
    }
}