force-app/main/default/objects/leaseworks__Invoice__c/leaseworks__Invoice__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageLease</customHelpPage>
    <description>Generic Object to hold Invoice information.</description>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Amount__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Amount__c</fullName>
    <description>Total Amount Due : This is the amount due generated by the system. This might get overridden by the user.
Rent - Rent due + Intereset - MRO
Aircraft MR - UR.Total_Maintenance_Reserve__c
Assembly MR - AsmblyUR.Total_Maintenance_Reserve__c</description>
    <inlineHelpText>Amount of Invoice before taxes or any adjustments</inlineHelpText>
    <label>Original Invoiced Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Exchange_Rate__c</fullName>
    <description>Exchange Rate</description>
    <label>Exchange Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Invoice_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Default Late Interest Invoice Date</description>
    <inlineHelpText>Default Late Interest Invoice Date</inlineHelpText>
    <label>Invoice Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Rent__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Rent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>leaseworks__Rent__c.leaseworks__RentPayments__c</field>
            <operation>equals</operation>
            <valueField>$Source.leaseworks__Lease__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Rent__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice_Line_Item__c/leaseworks__Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Line Items that constitute the invoice details
An invoice line item represents a specific entry on an invoice, offering a detailed breakdown of the total invoiced amount. 
Population Requirement Details: If the triggers are ON, the system will automatically create lines with line amounts for MR invoices based on the supplemental Rent amount calculated on utilization, and for Rent invoices based on the Rent Slip lines. Security deposit and other types of invoices will only have one line auto-created by the system.
If the trigger is OFF, the data for the invoice line items must be manually loaded. However, this is not a recommended method for loading invoice line data.
[MODULE: Finance]
[LOAD: Optional]
[PREREQUISITES: Invoice (if loading with Triggers OFF)]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Invoice_Line_Item__c/fields/leaseworks__Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Amount_Due__c</fullName>
    <description>Amount Due($)</description>
    <inlineHelpText>Amount of Invoice Line before any adjustments</inlineHelpText>
    <label>Invoice Line Amount($)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice_Line_Item__c/fields/leaseworks__Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Exchange_Rate__c</fullName>
    <description>The rate of exchange between the foreign currency and base currency based on the selected date</description>
    <formula>leaseworks__Invoice__r.leaseworks__Exchange_Rate__c</formula>
    <inlineHelpText>The rate of exchange between the foreign currency and base currency based on the selected date</inlineHelpText>
    <label>Exchange Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice_Line_Item__c/fields/leaseworks__Invoice__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>leaseworks__Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice_Line_Item__c/fields/leaseworks__Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Invoice_Date__c</fullName>
    <formula>leaseworks__Invoice__r.leaseworks__Invoice_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>_Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Payment__c/leaseworks__Payment__c.object-meta.xml
<CustomObject>
    <description>The Payments &amp; Credits serves as a vital record capturing payments made against individual invoices. Users can specify whether the payment was made in cash or as an offset against other outstanding amounts.
When loaded via Payment Studio, these records are automatically created with an approved status and associated with individual invoices upon Payment Studio record approval.
Population Requirement Details: Conditionally Required if legacy data loading is required and is not loaded via payment studio
[MODULE: Finance]
[LOAD: Yes]
[PREREQUISITES: If the Payment Type (Payment/Credit field) equals Cash Payment, Invoice, Payment on Account. If the Payment Type (Payment/Credit field) is not equal to &apos;Cash Payment&apos; then the below are required., Invoice, Letter of Credit, Payable, Security Deposit, Credit Memo]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Payments &amp; Credits</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments &amp; Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Payment__c/fields/leaseworks__Amount__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Amount__c</fullName>
    <inlineHelpText>Update of the  amount will re-calculate Payment Line Items accordingly, all manual adjustments will be overwritten</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/leaseworks__Payment__c/fields/leaseworks__Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Exchange_Rate__c</fullName>
    <description>The rate of exchange between the foreign currency and base currency based on the selected date</description>
    <inlineHelpText>The rate of exchange between the foreign currency and base currency based on the selected date</inlineHelpText>
    <label>Exchange Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Payment__c/fields/leaseworks__Invoice__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>leaseworks__Invoice__c</referenceTo>
    <relationshipLabel>Payments &amp; Credits</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/leaseworks__Payment_Line_Item__c/leaseworks__Payment_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Line Items that constitute the invoice details</description>
    <label>View Payment Line Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>View Payment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Payment_Line_Item__c/fields/leaseworks__Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Exchange_Rate__c</fullName>
    <description>The rate of exchange between the foreign currency and base currency based on the selected date</description>
    <formula>leaseworks__Payment__r.leaseworks__Exchange_Rate__c</formula>
    <inlineHelpText>The rate of exchange between the foreign currency and base currency based on the selected date</inlineHelpText>
    <label>Exchange Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Rent__c/leaseworks__Rent__c.object-meta.xml
<CustomObject>
    <description>Rent Slips, typically generated monthly for each Rent Schedule, detail rent calculations like amounts and cost breakdowns. They trigger invoice generation per payment cycle, usually done automatically by Rent Studio. But for importing data from other systems or new leases, manual upload via a data loader is also possible.
Rent Slips for Rent Type &apos;Fixed&apos;, &apos;Floating&apos;, &apos;Seasonal&apos;, &apos;PBH&apos;, typically generated monthly for each Rent Schedule, detail rent calculations like amounts and cost breakdowns. They trigger invoice generation per payment cycle, usually done automatically by Rent Studio. But for importing data from other systems or new leases, manual upload via a data loader is also possible.
[MODULE: Contract]
[LOAD: Optional]
[PREREQUISITES: Rent Schedule]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Rent Slip</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rent Slip</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Rent__c/fields/leaseworks__Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Billing_Currency__c</fullName>
    <description>Indicates the billing currency, which is set according to the billing currency specified on the related  schedule.</description>
    <formula>TEXT(leaseworks__Stepped_Rent__r.leaseworks__Billing_Currency__c)</formula>
    <inlineHelpText>Indicates the billing currency, which is set according to the billing currency specified on the related  schedule.</inlineHelpText>
    <label>Billing Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Rent__c/fields/leaseworks__Final_Rent_Slip_Amount__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Final_Rent_Slip_Amount__c</fullName>
    <description>Indicates final rent amount for this rent period including adjustment. Used when multi-currency is enabled</description>
    <formula>leaseworks__Total_Due__c</formula>
    <inlineHelpText>Indicates final rent amount for this rent period including adjustment. Used when multi-currency is enabled</inlineHelpText>
    <label>Final Rent Slip Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Rent__c/fields/leaseworks__Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Invoice_Date__c</fullName>
    <description>The initial Invoice Date when the invoice was created.</description>
    <inlineHelpText>The initial Invoice Date when the invoice was created.</inlineHelpText>
    <label>Invoice Date (Initial)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Rent__c/fields/leaseworks__Link_to_Invoice__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Link_to_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Link to Invoice</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.leaseworks__RentPayments__c</field>
            <operation>equals</operation>
            <valueField>leaseworks__Invoice__c.leaseworks__Lease__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Invoice__c</referenceTo>
    <relationshipLabel>Rent Schedule</relationshipLabel>
    <relationshipName>Rent_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Rent__c/fields/leaseworks__Stepped_Rent__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Stepped_Rent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Step Rent Record(Rent Schedule)</description>
    <inlineHelpText>Lookup to Rent Schedule(Step Rent)</inlineHelpText>
    <label>Rent Schedule</label>
    <referenceTo>leaseworks__Stepped_Rent__c</referenceTo>
    <relationshipLabel>Rent Slip</relationshipLabel>
    <relationshipName>Rent_Period</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Rent_Slip_Line_Item__c/leaseworks__Rent_Slip_Line_Item__c.object-meta.xml
<CustomObject>
    <description>[MODULE: NA]
[LOAD: No]
[PREREQUISITES: NA]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Rent Slip Line Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rent Slip Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Rent_Slip_Line_Item__c/fields/leaseworks__Amount__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Amount__c</fullName>
    <label>Line Amount($)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/leaseworks__Stepped_Rent__c/leaseworks__Stepped_Rent__c.object-meta.xml
<CustomObject>
    <description>This lease-level configuration table houses Rent Schedule parameters, including start/end dates and base rent. While typically a single schedule exists per lease, exceptions involving rent type changes (fixed to PBH, etc.) necessitate additional schedules. Users leverage Rent Studio to manage these schedules, generating rent slips and subsequent invoices.
If Applicable and the Rent Type can be Fixed, Floating, Seasonal, PBH.
This lease-level configuration table houses Rent Schedule parameters, including start/end dates and base rent. While typically a single schedule exists per lease, exceptions involving rent type changes (fixed to PBH, etc.) necessitate additional schedules. Users leverage Rent Studio to manage these schedules, generating rent slips and subsequent invoices.
[MODULE: Contract]
[LOAD: Yes]
[PREREQUISITES: Lease]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Rent Schedule</label>
    <nameField>
        <label>Rent Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rent Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Stepped_Rent__c/fields/leaseworks__Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Billing_Currency__c</fullName>
    <description>Select the applicable currency for this rent schedule. The billing currency is the agreed-upon contract currency used to issue invoices to the lessee</description>
    <inlineHelpText>Select the applicable currency for this rent schedule. The billing currency is the agreed-upon contract currency used to issue invoices to the lessee. Note: Billing currency selection is only supported for the Fixed Rent type.</inlineHelpText>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Currency_GP</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Stepped_Rent__c/fields/leaseworks__Rent_Period__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Rent_Period__c</fullName>
    <inlineHelpText>Period to which the Lessor charges the Lessee Rent in accordance with the Lease Agreement</inlineHelpText>
    <label>Rent Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Stepped_Rent__c/fields/Local_Currency_local__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency_local__c</fullName>
    <description>Represents the currency to be displayed on the Invoices.</description>
    <inlineHelpText>Select the currency to be displayed on the Invoices for this rent schedule</inlineHelpText>
    <label>Transaction  Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Currency_GP</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/leaseworks__Currency_GP.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>MYR</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Currency Global Picklist</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LocalMulticurrencyMigration.cls
/**
* LocalMulticurrencyMigration
*
* This class provides a utility to migrate local multicurrency implemented data to the packaged multicurrency format in the system.
* NOTE:
* - This is essentially a datafix utility class.
* - It is intended to migrate the local multicurrency data seamlessly to the packaged multicurrency setup.
* - Should be deleted after successful execution and data migration.
*/

public with sharing class LocalMulticurrencyMigration {
    
    public static void processMultiCurrencyMigration(Boolean runScript) {
        String msg = '';
        String errormsg = '';
        
        try {
            List<leaseworks__Stepped_Rent__c> listRentSch = [SELECT Id, Local_Currency_local__c, leaseworks__Billing_Currency__c, 
                                                             (SELECT Id, Name, leaseworks__Link_to_Invoice__c, leaseworks__Stepped_Rent__c, leaseworks__Stepped_Rent__r.leaseworks__Billing_Currency__c, leaseworks__Stepped_Rent__r.Local_Currency_local__c 
                                                              FROM leaseworks__Rent_Period__r WHERE leaseworks__Link_to_Invoice__c != null)  
                                                             FROM leaseworks__Stepped_Rent__c WHERE Local_Currency_local__c = 'EUR'];
            
            msg += 'Total EUR Stepped Rents found: ' + listRentSch.size() + ' <br>';
            System.debug('Total EUR Stepped Rents found: ' + listRentSch.size());
            
            Set<Id> invoiceIds = new Set<Id>();
            
            if(Test.isRunningTest()){                
                for (leaseworks__Stepped_Rent__c objRent : listRentSch) {
                    for (leaseworks__Rent__c objRSlip : objRent.leaseworks__Rent_Period__r) {
                        if (objRSlip.leaseworks__Link_to_Invoice__c != null) {
                            invoiceIds.add(objRSlip.leaseworks__Link_to_Invoice__c);
                        }
                    }
                }
            }else{
                invoiceIds.addAll(new Set<Id>{'a2taA000000l9MPQAY', 'a2taA000000l9MQQAY', 'a2taA000000lLqbQAE', 'a2taA000000lLsDQAU', 'a2taA000000lLtpQAE', 'a2taA000000lM1tQAE', 'a2taA000000lM3VQAU', 'a2taA000000lM57QAE', 'a2taA000000l9RFQAY', 'a2taA000000l9RGQAY', 'a2taA000000l9RHQAY', 'a2taA000000lLdhQAE', 'a2taA000000lLfJQAU', 'a2taA000000lLgvQAE', 'a2taA000000lLllQAE', 'a2taA000000lLnNQAU'});
            }
            
            Map<Id, leaseworks__Invoice__c> invoiceMap = new Map<Id, leaseworks__Invoice__c>([
                SELECT Id, leaseworks__Exchange_Rate__c, leaseworks__Invoice_Date__c, leaseworks__Amount__c, leaseworks__Rent__r.leaseworks__Final_Rent_Slip_Amount__c, leaseworks__Rent__r.leaseworks__Stepped_Rent__c, (SELECT Id, Name, leaseworks__Amount_Due__c, leaseworks__Rent_Slip_Line_Item__r.leaseworks__Amount__c, Y_Hidden_Amount_Bef_Round_Local__c 
                                                                                                                                                                                                                          FROM leaseworks__Invoice_Line_Items__r), (SELECT Id, leaseworks__Payment_Status__c, leaseworks__Amount__c FROM leaseworks__Payments__r WHERE leaseworks__Payment_Status__c = 'Approved')	
                FROM leaseworks__Invoice__c WHERE Id IN :invoiceIds and leaseworks__Status__c != 'Declined']);
            
            System.debug('Invoices queried: ' + invoiceMap.size());
            
            Set<Date> invoiceDates = new Set<Date>();
            Set<Id> steppedRentIdsForInvoices = new Set<Id>();
            
            for(leaseworks__Invoice__c objInv : invoiceMap.values()) {
                if(objInv.leaseworks__Invoice_Date__c != null) {
                    invoiceDates.add(objInv.leaseworks__Invoice_Date__c);
                }
                if (objInv.leaseworks__Rent__r != null && objInv.leaseworks__Rent__r.leaseworks__Stepped_Rent__c != null) {
                    steppedRentIdsForInvoices.add(objInv.leaseworks__Rent__r.leaseworks__Stepped_Rent__c);
                }
            }
            
            Map<String, leaseworks__Currency_Rates__c> mapExchangeRate = new Map<String, leaseworks__Currency_Rates__c>();
            
            for(leaseworks__Currency_Rates__c rate : [Select Id, Name, leaseworks__Source_Currency__c, leaseworks__Target_Currency__c, leaseworks__Date__c, leaseworks__Rate_New__c from leaseworks__Currency_Rates__c where leaseworks__Date__c IN :invoiceDates and ((leaseworks__Source_Currency__c = 'USD' and leaseworks__Target_Currency__c = 'EUR') or (leaseworks__Source_Currency__c = 'EUR' and leaseworks__Target_Currency__c = 'USD'))]){
                String key = rate.leaseworks__Source_Currency__c + '-' + rate.leaseworks__Target_Currency__c + '-' + rate.leaseworks__Date__c.format();
                mapExchangeRate.put(key, rate);
            }
            
            List<leaseworks__Invoice__c> listInvoiceToUpdate = new List<leaseworks__Invoice__c>();
            List<leaseworks__Stepped_Rent__c> listRentToUpdate = new List<leaseworks__Stepped_Rent__c>();
            List<leaseworks__Invoice_Line_Item__c> listInvItemsToUpdate = new List<leaseworks__Invoice_Line_Item__c>();
            List<leaseworks__Payment__c> listPaymentsToUpdate = new List<leaseworks__Payment__c>();
            List<leaseworks__Payment_Line_Item__c> listPaymentLineItemsToUpdate = new List<leaseworks__Payment_Line_Item__c>();
            List<leaseworks__Currency_Rates__c> listNewCurrencyRateToCreate = new List<leaseworks__Currency_Rates__c>();
            
            for (leaseworks__Invoice__c objInv : invoiceMap.values()){
                
                Decimal exRate;
                leaseworks__Currency_Rates__c objRate;
                
                if(objInv.leaseworks__Invoice_Date__c != null){
                    String rateKey = 'USD-EUR-' + objInv.leaseworks__Invoice_Date__c.format();
                    objRate = mapExchangeRate.get(rateKey);
                    
                    if(objRate != null){
                        exRate = objRate.leaseworks__Rate_New__c;
                        System.debug('Currency Rate from query: ' + exRate + ' for date: ' + objInv.leaseworks__Invoice_Date__c);
                        msg += 'Currency Rate from query: ' + exRate + ' for date: ' + objInv.leaseworks__Invoice_Date__c + ' <br>';
                        
                        String revkey = 'EUR-USD-' + objInv.leaseworks__Invoice_Date__c.format();
                        
                        if (!mapExchangeRate.containsKey(revkey)) {
                            leaseworks__Currency_Rates__c objNewRate = new leaseworks__Currency_Rates__c();
                            objNewRate.leaseworks__Date__c = objRate.leaseworks__Date__c;
                            objNewRate.leaseworks__Source_Currency__c = objRate.leaseworks__Target_Currency__c;
                            objNewRate.leaseworks__Target_Currency__c = objRate.leaseworks__Source_Currency__c;
                            objNewRate.leaseworks__Rate_New__c = (exRate != 0) ? (1 / exRate).setScale(6, System.RoundingMode.HALF_UP) : 1;
                            objNewRate.Name = 'EUR / USD ' + objRate.leaseworks__Date__c;
                            
                            // Only add if not already staged for creation
                            listNewCurrencyRateToCreate.add(objNewRate);
                            System.debug('Prepared new reverse currency rate for key ' + revkey + ' Value: ' + objNewRate.leaseworks__Rate_New__c);
                            msg += 'Prepared new reverse currency rate for ' + revkey + ' Value: ' + objNewRate.leaseworks__Rate_New__c + ' <br>';
                            mapExchangeRate.put(revkey, objNewRate);
                        }
                    }
                    else{
                        System.debug('No Currency Rate found for date: ' + objInv.leaseworks__Invoice_Date__c + ' for Invoice: '+ objInv.Id);
                        msg += 'No Currency Rate found for date: ' + objInv.leaseworks__Invoice_Date__c + ' for Invoice: '+ objInv.Id + ' <br>';
                        continue;
                    }
                } else{
                    System.debug('Invoice date is null for invoice: ' + objInv.Id);
                    msg += 'Invoice date is null for invoice: ' + objInv.Id + ' <br>';
                    continue;
                }
                
                if (objInv.leaseworks__Invoice_Line_Items__r.size() > 1) {
                    System.debug('INFO: Invoice ' + objInv.Id + ' has ' + objInv.leaseworks__Invoice_Line_Items__r.size() + ' line items!');
                    msg += 'INFO: Invoice ' + objInv.Id + ' has ' + objInv.leaseworks__Invoice_Line_Items__r.size() + ' line items!  <br>';
                }
                
                if(exRate == null){
                    System.debug('Exchange Rate is null for this Invoice: '+ objInv);
                    msg += 'Exchange Rate is null for this Invoice: '+ objInv + ' <br>';
                    continue;
                }
                
                Decimal origAmt = objInv.leaseworks__Amount__c;
                Decimal newInvAmt = (objInv.leaseworks__Amount__c * exRate).setScale(2, System.RoundingMode.HALF_UP);
                objInv.leaseworks__Amount__c = newInvAmt;
                objInv.leaseworks__Exchange_Rate__c = (exRate != 0) ? (1 / exRate) : 1;
                
                if(objInv.leaseworks__Rent__r.leaseworks__Final_Rent_Slip_Amount__c != origAmt){
                    listInvoiceToUpdate.add(objInv);
                    System.debug('Invoice Item ' + objInv.Id + ' | Original Due: ' + origAmt + ' | New Due: ' + newInvAmt);
                    msg += 'Invoice Item ' + objInv.Id + ' | Original Due: ' + origAmt + ' | New Due: ' + newInvAmt + ' <br>';
                }
                else{
                    System.debug('Invoice record already updated -> '+ objInv.Id);
                    msg += 'Invoice record already updated -> '+ objInv.Id + ' <br>';
                }
                
                for (leaseworks__Invoice_Line_Item__c line : objInv.leaseworks__Invoice_Line_Items__r) {
                    Decimal origDueAmt = line.leaseworks__Amount_Due__c;
                    Decimal newAmt = (origDueAmt * exRate).setScale(2, System.RoundingMode.HALF_UP);
                    
                    //line.leaseworks__Exchange_Rate__c = (exRate != 0) ? (1 / exRate) : 1;
                    line.leaseworks__Amount_Due__c = newAmt;
                    line.Y_Hidden_Amount_Bef_Round_Local__c = newAmt;
                    
                    if(line.leaseworks__Rent_Slip_Line_Item__r.leaseworks__Amount__c != origDueAmt){
                        listInvItemsToUpdate.add(line);
                        System.debug('Invoice Line Item ' + line.Id + ' | Original Due: ' + origDueAmt + ' | New Due: ' + newAmt);
                        msg += 'Invoice Line Item ' + line.Id + ' | Original Due: ' + origDueAmt + ' | New Due: ' + newAmt + ' <br>';
                    }
                    else{
                        System.debug('Invoice Line Item already updated -> '+ line.Id);
                        msg += 'Invoice Line Item already updated -> ' + line.Id + ' <br>';
                    }
                }  
            }
            
            for (leaseworks__Stepped_Rent__c objRent : listRentSch) {
                if(steppedRentIdsForInvoices.contains(objRent.Id)){
                    if(objRent.Local_Currency_local__c != null && objRent.leaseworks__Billing_Currency__c != objRent.Local_Currency_local__c) {
                        objRent.leaseworks__Billing_Currency__c = objRent.Local_Currency_local__c;
                        listRentToUpdate.add(objRent);
                        System.debug('Updated Billing Currency for Stepped Rent ' + objRent.Id);
                        msg += 'Updated Billing Currency for Stepped Rent ' + objRent.Id + ' <br>';
                    }
                }
            }
            
            if (runScript && !Test.isRunningTest() && (!listRentToUpdate.isEmpty() || !listInvItemsToUpdate.isEmpty() || !listPaymentsToUpdate.isEmpty() || !listPaymentLineItemsToUpdate.isEmpty())) {
                leaseworks.LWGlobalUtils.setTriggersAndWFsOff();
                
                try {
                    if(!listNewCurrencyRateToCreate.isEmpty()) {
                        insert listNewCurrencyRateToCreate;
                        System.debug('Created ' + listNewCurrencyRateToCreate.size() + ' New currency rates');
                        msg += 'Created ' + listNewCurrencyRateToCreate.size() + ' New currency rates <br>';
                    }
                    
                    if(!listRentToUpdate.isEmpty()) {
                        update listRentToUpdate;
                        System.debug('Updated ' + listRentToUpdate.size() + ' Rent Slips.');
                    }
                    
                    if(!listInvoiceToUpdate.isEmpty()) {
                        update listInvoiceToUpdate;
                        System.debug('Updated ' + listInvoiceToUpdate.size() + ' Invoices.');
                    }
                    
                    if(!listInvItemsToUpdate.isEmpty()) {
                        update listInvItemsToUpdate;
                        System.debug('Updated ' + listInvItemsToUpdate.size() + ' Invoice Line Items.');
                    }
                    
                    msg += 'Successfully created ' + listNewCurrencyRateToCreate.size() + ' currency rates and updated ' + listRentToUpdate.size() + ' Stepped Rents, ' + listInvoiceToUpdate.size() + ' Invoices, ' + listInvItemsToUpdate.size() + ' Invoice Line Items <br>';
                    
                } catch (Exception e) {
                    leaseworks.LWGlobalUtils.setTriggersAndWFsOn();
                    errormsg += 'Error during update: ' + e.getMessage() + '<br>' + e.getStackTraceString();
                    throw e; // Re-throw to be caught by outer catch block
                }
            } else {
                msg += 'No records to update. <br>';
            }
            
        } catch (Exception e) {
            errormsg += 'Error during processing: ' + e.getMessage() + '<br>' + e.getStackTraceString();
            System.debug('Error: ' + e.getMessage() + ' at ' + e.getLineNumber());
        }
        
        // Send Email with results
        sendResultEmail(msg, errormsg);
    }
    
    private static void sendResultEmail(String msg, String errormsg) {
        try {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTargetObjectId(UserInfo.getUserId());
            mail.setSaveAsActivity(false);
            String subjectName = 'MultiCurrency Local implementation migration Update - ' + Date.today().format();
            mail.setSubject('[' + UserInfo.getOrganizationName() + '] - ' + subjectName);
            mail.setHtmlBody(msg + (String.isNotBlank(errormsg) ? '<br><br>ERRORS:<br>' + errormsg : ''));
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        } catch (Exception e) {
            System.debug('Error sending email: ' + e.getMessage());
        }
    }
}