force-app/main/default/objects/leaseworks__Currency_Rates__c/leaseworks__Currency_Rates__c.object-meta.xml
<CustomObject>
    <description>The Currency Rates object captures real-time or historical exchange rates for various currencies . It helps to access accurate and up-to-date currency conversion data, facilitating international transactions, financial analysis, and currency-related calculations. Users can retrieve exchange rates for specific currencies and dates.
[MODULE: Contract]
[LOAD: Optional]
[PREREQUISITES: NA]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Currency Rates</label>
    <nameField>
        <label>Currency Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currency Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Currency_Rates__c/fields/leaseworks__Date__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Date__c</fullName>
    <description>Specifies the date when the exchange rate is recorded.</description>
    <inlineHelpText>Specifies the date when the exchange rate is recorded.</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Currency_Rates__c/fields/leaseworks__Rate_New__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Rate_New__c</fullName>
    <description>Represents the value of one currency in terms of another. It determines how much of one currency is needed to get a unit of another currency.</description>
    <inlineHelpText>Indicates the value of source currency in terms of target currency.</inlineHelpText>
    <label>Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Currency_Rates__c/fields/leaseworks__Source_Currency__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Source_Currency__c</fullName>
    <description>Indicates the currency against which exchange rate is quoted.</description>
    <inlineHelpText>Select the currency against which exchange rate is quoted.</inlineHelpText>
    <label>Source Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Currency_GP</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Stepped_Rent__c/leaseworks__Stepped_Rent__c.object-meta.xml
<CustomObject>
    <description>This lease-level configuration table houses Rent Schedule parameters, including start/end dates and base rent. While typically a single schedule exists per lease, exceptions involving rent type changes (fixed to PBH, etc.) necessitate additional schedules. Users leverage Rent Studio to manage these schedules, generating rent slips and subsequent invoices.
If Applicable and the Rent Type can be Fixed, Floating, Seasonal, PBH.
This lease-level configuration table houses Rent Schedule parameters, including start/end dates and base rent. While typically a single schedule exists per lease, exceptions involving rent type changes (fixed to PBH, etc.) necessitate additional schedules. Users leverage Rent Studio to manage these schedules, generating rent slips and subsequent invoices.
[MODULE: Contract]
[LOAD: Yes]
[PREREQUISITES: Lease]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Rent Schedule</label>
    <nameField>
        <label>Rent Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rent Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Stepped_Rent__c/fields/leaseworks__Billing_Currency__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Billing_Currency__c</fullName>
    <description>Select the applicable currency for this rent schedule. The billing currency is the agreed-upon contract currency used to issue invoices to the lessee</description>
    <inlineHelpText>Select the applicable currency for this rent schedule. The billing currency is the agreed-upon contract currency used to issue invoices to the lessee. Note: Billing currency selection is only supported for the Fixed Rent type.</inlineHelpText>
    <label>Billing Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Currency_GP</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Stepped_Rent__c/fields/pro_Currency_Rates__c.field-meta.xml
<CustomField>
    <fullName>pro_Currency_Rates__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Currency Rates object. Used to aid with Currency Conversion calculations for non USD Rent Schedules</description>
    <label>Currency Rates</label>
    <referenceTo>leaseworks__Currency_Rates__c</referenceTo>
    <relationshipLabel>Rent Schedule</relationshipLabel>
    <relationshipName>Rent_Schedule</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/leaseworks__Currency_GP.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>MYR</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <masterLabel>Currency Global Picklist</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SetCurrencyRateOnSteppedRentTest.cls
@isTest
private class SetCurrencyRateOnSteppedRentTest {

    @isTest static void testScheduler() {
        // Minimal test context setup
        leaseworks__Currency_Rates__c rate = new leaseworks__Currency_Rates__c(
            leaseworks__Source_Currency__c = 'EUR',
            leaseworks__Rate_New__c = 1.2,
            leaseworks__Date__c = Date.today()
        );
        insert rate;

        leaseworks__Stepped_Rent__c rent = new leaseworks__Stepped_Rent__c(
            leaseworks__Billing_Currency__c = 'EUR'
        );
        insert rent;

        Test.startTest();
        System.schedule('Test Schedule', '0 0 1 * * ?', new SetCurrencyRateOnSteppedRent());
        Test.stopTest();

        rent = [SELECT pro_Currency_Rates__c FROM leaseworks__Stepped_Rent__c WHERE Id = :rent.Id];
        System.assertEquals(rate.Id, rent.pro_Currency_Rates__c);
    }
}