force-app/main/default/objects/leaseworks__Aircraft__c/leaseworks__Aircraft__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageAircraft</customHelpPage>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Engine_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Type_GP__c</fullName>
    <label>Engine Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Asset_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft_Type__c/leaseworks__Aircraft_Type__c.object-meta.xml
<CustomObject>
    <description>Object that captures trends in aircraft types based on conversations that are happening across fleets and customers.</description>
    <label>Aircraft Type</label>
    <nameField>
        <label>Aircraft Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Aircraft_Type__c/fields/leaseworks__Engine_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Type_GP__c</fullName>
    <label>Engine Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Asset_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/leaseworks__Constituent_Assembly__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageAircraft</customHelpPage>
    <label>Assembly</label>
    <nameField>
        <label>Assembly Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assemblies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__Engine_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Type_GP__c</fullName>
    <label>Engine Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Manufacturer_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__Model__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Model__c</fullName>
    <label>Z_Unused_2012 Purchased Thrust</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Customer_Interaction_Log__c/leaseworks__Customer_Interaction_Log__c.object-meta.xml
<CustomObject>
    <description>[MODULE: NA]
[LOAD: No]
[PREREQUISITES: NA]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Interaction Log</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interaction Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Customer_Interaction_Log__c/fields/leaseworks__Engine_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Type_GP__c</fullName>
    <label>Engine Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Asset_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Customer_Interaction_Log__c/fields/leaseworks__Variant__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Variant__c</fullName>
    <label>Z_Unused_2304_Variant</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>100B</fullName>
            </value>
            <value>
                <fullName>100F</fullName>
            </value>
            <value>
                <fullName>100SF</fullName>
            </value>
            <value>
                <fullName>103</fullName>
            </value>
            <value>
                <fullName>112</fullName>
            </value>
            <value>
                <fullName>200</fullName>
            </value>
            <value>
                <fullName>200B</fullName>
            </value>
            <value>
                <fullName>200ER</fullName>
            </value>
            <value>
                <fullName>200F</fullName>
            </value>
            <value>
                <fullName>200LR</fullName>
            </value>
            <value>
                <fullName>200PCF</fullName>
            </value>
            <value>
                <fullName>200SF</fullName>
            </value>
            <value>
                <fullName>211</fullName>
            </value>
            <value>
                <fullName>212</fullName>
            </value>
            <value>
                <fullName>231</fullName>
            </value>
            <value>
                <fullName>232</fullName>
            </value>
            <value>
                <fullName>233</fullName>
            </value>
            <value>
                <fullName>300</fullName>
            </value>
            <value>
                <fullName>300ER</fullName>
            </value>
            <value>
                <fullName>300LR</fullName>
            </value>
            <value>
                <fullName>300SF</fullName>
            </value>
            <value>
                <fullName>400</fullName>
            </value>
            <value>
                <fullName>400F</fullName>
            </value>
            <value>
                <fullName>500</fullName>
            </value>
            <value>
                <fullName>600</fullName>
            </value>
            <value>
                <fullName>600F</fullName>
            </value>
            <value>
                <fullName>600R</fullName>
            </value>
            <value>
                <fullName>700</fullName>
            </value>
            <value>
                <fullName>800</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Engine_Template__c/leaseworks__Engine_Template__c.object-meta.xml
<CustomObject>
    <label>Engine Template</label>
    <nameField>
        <label>Engine Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engine Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Engine_Template__c/fields/leaseworks__Engine_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Type_GP__c</fullName>
    <label>Engine Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Manufacturer_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Engine_Template__c/fields/leaseworks__Model__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Model__c</fullName>
    <label>Z_Unused_2307_Model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Manufacturer__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>3DAero</fullName>
            </value>
            <value>
                <fullName>A330</fullName>
            </value>
            <value>
                <fullName>CF34</fullName>
            </value>
            <value>
                <fullName>CF6</fullName>
            </value>
            <value>
                <fullName>CFM56-5B</fullName>
            </value>
            <value>
                <fullName>CFM56-5B26/27</fullName>
            </value>
            <value>
                <fullName>GE90</fullName>
            </value>
            <value>
                <fullName>JT8</fullName>
            </value>
            <value>
                <fullName>JT9</fullName>
            </value>
            <value>
                <fullName>PW2037</fullName>
            </value>
            <value>
                <fullName>PW4000</fullName>
            </value>
            <value>
                <fullName>PW4056</fullName>
            </value>
            <value>
                <fullName>PW4060</fullName>
            </value>
            <value>
                <fullName>PW4064</fullName>
            </value>
            <value>
                <fullName>PW4162</fullName>
            </value>
            <value>
                <fullName>PW4168A</fullName>
            </value>
            <value>
                <fullName>PW4462</fullName>
            </value>
            <value>
                <fullName>RB211</fullName>
            </value>
            <value>
                <fullName>Trent 772B</fullName>
            </value>
            <value>
                <fullName>Trent 892B</fullName>
            </value>
            <value>
                <fullName>V2500</fullName>
            </value>
            <value>
                <fullName>V2527</fullName>
            </value>
            <value>
                <fullName>V2533</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Engine_Template__c/fields/leaseworks__Variant__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Variant__c</fullName>
    <label>Z_Unused_2307_Variant</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10E6</fullName>
            </value>
            <value>
                <fullName>10E7</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>80AXX</fullName>
            </value>
            <value>
                <fullName>80BXX</fullName>
            </value>
            <value>
                <fullName>80C2</fullName>
            </value>
            <value>
                <fullName>80C2B1F</fullName>
            </value>
            <value>
                <fullName>80C2B2</fullName>
            </value>
            <value>
                <fullName>80C2B5F</fullName>
            </value>
            <value>
                <fullName>80CXX</fullName>
            </value>
            <value>
                <fullName>80EXX</fullName>
            </value>
            <value>
                <fullName>3B1</fullName>
            </value>
            <value>
                <fullName>3B2</fullName>
            </value>
            <value>
                <fullName>3C1</fullName>
            </value>
            <value>
                <fullName>5B3/2P</fullName>
            </value>
            <value>
                <fullName>5B3/P</fullName>
            </value>
            <value>
                <fullName>5B4/2P</fullName>
            </value>
            <value>
                <fullName>5B4/P</fullName>
            </value>
            <value>
                <fullName>5B6/2P</fullName>
            </value>
            <value>
                <fullName>5B6/3</fullName>
            </value>
            <value>
                <fullName>5B6/P</fullName>
            </value>
            <value>
                <fullName>7B22</fullName>
            </value>
            <value>
                <fullName>7B24</fullName>
            </value>
            <value>
                <fullName>7B26</fullName>
            </value>
            <value>
                <fullName>7B27</fullName>
            </value>
            <value>
                <fullName>115B</fullName>
            </value>
            <value>
                <fullName>115B1</fullName>
            </value>
            <value>
                <fullName>CET/RTC</fullName>
            </value>
            <value>
                <fullName>94</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Market_Intelligence__c/leaseworks__Market_Intelligence__c.object-meta.xml
<CustomObject>
    <label>Market Intelligence</label>
    <nameField>
        <label>Market Intel Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Intelligence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Market_Intelligence__c/fields/leaseworks__Engine_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Type_GP__c</fullName>
    <label>Engine Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Asset_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Pricing_Run_New__c/leaseworks__Pricing_Run_New__c.object-meta.xml
<CustomObject>
    <description>[MODULE: NA]
[LOAD: No]
[PREREQUISITES: NA]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Commercial Terms</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Pricing_Run_New__c/fields/leaseworks__Engine_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Type_GP__c</fullName>
    <label>Engine Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Manufacturer_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/leaseworks__Engine_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CF34</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80A</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80C2</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80E1</fullName>
    </customValue>
    <customValue>
        <fullName>CFM56-5A</fullName>
    </customValue>
    <customValue>
        <fullName>CFM56-5B</fullName>
    </customValue>
    <customValue>
        <fullName>CFM56-5C</fullName>
    </customValue>
    <customValue>
        <fullName>CFM56-7B</fullName>
    </customValue>
    <customValue>
        <fullName>GE90-100</fullName>
    </customValue>
    <customValue>
        <fullName>LEAP-1A</fullName>
    </customValue>
    <customValue>
        <fullName>LEAP-1B</fullName>
    </customValue>
    <customValue>
        <fullName>PW1000G</fullName>
    </customValue>
    <customValue>
        <fullName>PW1100G-JM</fullName>
    </customValue>
    <customValue>
        <fullName>PW1500</fullName>
    </customValue>
    <customValue>
        <fullName>PW2000</fullName>
    </customValue>
    <customValue>
        <fullName>PW4000</fullName>
    </customValue>
    <customValue>
        <fullName>PW4000-100</fullName>
    </customValue>
    <customValue>
        <fullName>PW4056</fullName>
    </customValue>
    <customValue>
        <fullName>Trent-700</fullName>
    </customValue>
    <customValue>
        <fullName>Trent-800</fullName>
    </customValue>
    <customValue>
        <fullName>Trent-1000</fullName>
    </customValue>
    <customValue>
        <fullName>Trent-7000</fullName>
    </customValue>
    <customValue>
        <fullName>Trent-XWB</fullName>
    </customValue>
    <customValue>
        <fullName>V2500-( )5</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>PW4162</fullName>
        <isActive>false</isActive>
        <label>PW4162</label>
    </customValue>
    <customValue>
        <fullName>PW4168A</fullName>
        <isActive>false</isActive>
        <label>PW4168A</label>
    </customValue>
    <customValue>
        <fullName>PW4462</fullName>
        <isActive>false</isActive>
        <label>PW4462</label>
    </customValue>
    <customValue>
        <fullName>RB211</fullName>
        <isActive>false</isActive>
        <label>RB211</label>
    </customValue>
    <customValue>
        <fullName>Trent 892B</fullName>
        <isActive>false</isActive>
        <label>Trent 892B</label>
    </customValue>
    <masterLabel>Engine Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchGPCreateDependencies.cls
/**********
 * This batch class creates dependencies between the new fields referring to the global picklist by copying the settings 
 * from the source picklist that has been deprecated
 * It needs to be executed with a batch size of 1 to prevent time out errors
 * It can be run in two modes - Readonly = true(to review the changes), ReadOnly = false(to execute the changes).
**********/ 
public class BatchGPCreateDependencies implements Database.batchable <String>, Database.Stateful, Database.AllowsCallouts{
  
    String exceptionMessage; 
    String logMessage;
    String versionNumber;
    Boolean bReadOnly;
    public BatchGPCreateDependencies(String versionNumber, Boolean bReadOnly)
    {
       this.versionNumber = (versionNumber == ''? 'ALL': versionNumber);
       exceptionMessage = '';   
       logMessage = '';
       this.bReadOnly = bReadOnly; 
    }
       
    public  List<String> start(Database.BatchableContext bc) {
        List<string> lstOldFieldsToNewGP = new List<string>();
        if(this.versionNumber == '34' || this.versionNumber == 'ALL'){
            lstOldFieldsToNewGP.add('leaseworks__Engine_Template__c.leaseworks__Model__c' +'-'+ 'leaseworks__Engine_Template__c.leaseworks__Engine_Type_GP__c');
            lstOldFieldsToNewGP.add('leaseworks__Engine_Template__c.leaseworks__Variant__c' +'-'+ 'leaseworks__Engine_Template__c.leaseworks__Engine_Variant_GP__c');            
            
            lstOldFieldsToNewGP.add('leaseworks__Market_Intelligence__c.leaseworks__Engine_Type_List__c' +'-'+ 'leaseworks__Market_Intelligence__c.leaseworks__Engine_Type_GP__c');            
            lstOldFieldsToNewGP.add('leaseworks__Market_Intelligence__c.leaseworks__Variant__c' +'-'+ 'leaseworks__Market_Intelligence__c.leaseworks__Asset_Variant_GP__c');            
            lstOldFieldsToNewGP.add('leaseworks__Market_Intelligence__c.leaseworks__Engine_Variant__c' +'-'+ 'leaseworks__Market_Intelligence__c.leaseworks__Engine_Variant_GP__c');            
            
            lstOldFieldsToNewGP.add('leaseworks__Customer_Interaction_Log__c.leaseworks__Engine_Type_List__c' +'-'+ 'leaseworks__Customer_Interaction_Log__c.leaseworks__Engine_Type_GP__c');            
            lstOldFieldsToNewGP.add('leaseworks__Customer_Interaction_Log__c.leaseworks__Variant__c' +'-'+ 'leaseworks__Customer_Interaction_Log__c.leaseworks__Asset_Variant_GP__c');            
            lstOldFieldsToNewGP.add('leaseworks__Customer_Interaction_Log__c.leaseworks__Engine_Variant__c' +'-'+ 'leaseworks__Customer_Interaction_Log__c.leaseworks__Engine_Variant_GP__c');            
            
            lstOldFieldsToNewGP.add('leaseworks__Pricing_Run_New__c.leaseworks__Engine_Type_picklist__c' +'-'+ 'leaseworks__Pricing_Run_New__c.leaseworks__Engine_Type_GP__c');            
        }
           
       if(this.versionNumber == '37' || this.versionNumber == 'ALL'){
           lstOldFieldsToNewGP.add('leaseworks__Aircraft_Type__c.leaseworks__Aircraft_Variant__c' +'-'+'leaseworks__Aircraft_Type__c.leaseworks__Asset_Variant_GP__c');
           lstOldFieldsToNewGP.add('leaseworks__Aircraft_Type__c.leaseworks__Engine_Type__c' +'-'+'leaseworks__Aircraft_Type__c.leaseworks__Engine_Type_GP__c');
           lstOldFieldsToNewGP.add('leaseworks__Aircraft_Type__c.leaseworks__Engine_Variant__c' +'-'+'leaseworks__Aircraft_Type__c.leaseworks__Engine_Variant_GP__c');
           
           lstOldFieldsToNewGP.add('leaseworks__Constituent_Assembly__c.leaseworks__Engine_Model__c' +'-'+'leaseworks__Constituent_Assembly__c.leaseworks__Engine_Type_GP__c');
           lstOldFieldsToNewGP.add('leaseworks__Constituent_Assembly__c.leaseworks__Engine_Thrust__c' +'-'+'leaseworks__Constituent_Assembly__c.leaseworks__Engine_Variant_GP__c');                  
           
           lstOldFieldsToNewGP.add('leaseworks__Aircraft__c.leaseworks__Aircraft_Variant__c' +'-'+'leaseworks__Aircraft__c.leaseworks__Asset_Variant_GP__c');
           lstOldFieldsToNewGP.add('leaseworks__Aircraft__c.leaseworks__Engine_Type__c' +'-'+'leaseworks__Aircraft__c.leaseworks__Engine_Type_GP__c');                  
       }   
        
       return lstOldFieldsToNewGP;
   }
       
   public void execute(Database.BatchableContext BC, List<String> OldFieldToNewField)
   {
     
      String oldField = OldFieldToNewField[0].substringBefore('-');
      String newGPField = OldFieldToNewField[0].substringAfter('-');
      logMessage += '<br/>' + 'Processing==' + 'Old=' + oldField + '==New==' + newGPField + '<br/>';
      System.debug('Processing==' + 'Old=' + oldField + '==New==' + newGPField); 
          
      try{
          
          MetadataService.MetadataPort service = new MetadataService.MetadataPort();
          service.SessionHeader = new MetadataService.SessionHeader_element();
          service.SessionHeader.sessionId = UserInfo.getSessionId();
          service.timeout_x=120000;
  
           MetadataService.CustomField oldDependentCustomField = (MetadataService.CustomField) service.readMetadata(
          'CustomField', new String[] {oldField}).getRecords()[0];
  
           MetadataService.CustomField newDependentCustomField = (MetadataService.CustomField) service.readMetadata(
          'CustomField', new String[] {newGPField}).getRecords()[0];
  
          for (MetadataService.ValueSettings  vs : oldDependentCustomField.valueSet.valueSettings) {
              System.debug('OLD Controlling Field Values==' + vs.controllingFieldValue);
              System.debug('OLD Value Name==' + vs.valueName);    
              logMessage += 'OLD Controlling Field Values==' + vs.controllingFieldValue + '<br/>';
              logMessage += 'OLD Value Name==' + vs.valueName + '<br/>';
          }
  
          newDependentCustomField.valueSet.valueSettings = oldDependentCustomField.valueSet.valueSettings;
  
          for (MetadataService.ValueSettings  newVS : newDependentCustomField.valueSet.valueSettings) {
              System.debug('FINAL NEW Controlling Field Values==' + newVS.controllingFieldValue);
              System.debug('FINAL NEW Value Name==' + newVS.valueName);  
              logMessage += 'FINAL NEW Controlling Field Values==' + newVS.controllingFieldValue + '<br/>';
              logMessage += 'FINAL NEW Value Name==' + newVS.valueName + '<br/>';
          }
  
          if(!bReadOnly){
              System.debug('Successfully updating dependencies' + 'Old=' + oldField + '==New==' + newGPField);
              logMessage += 'Successfully updating dependencies' + 'Old=' + oldField + '==New==' + newGPField + '<br/>';
              MetadataService.UpsertResult result = service.upsertMetadata(new MetadataService.Metadata[] {newDependentCustomField})[0];
              
               if(!result.success){
                  for(MetadataService.Error errObj : result.errors){
                      logMessage += 'Error while upsert==' + errObj.message + '<br/>';
                      exceptionMessage += 'Error while upsert==' + errObj.message + '<br/>';
                      System.debug('Error while upsert==' + errObj.message);
                  }
              }
              
              System.debug('Successfully updated dependencies' + 'Old=' + oldField + '==New==' + newGPField);
              logMessage += 'Successfully updated dependencies' + 'Old=' + oldField + '==New==' + newGPField + '<br/>';
          }
  
      }
      catch(Exception ex){
          logMessage += 'ERROR: Exception while creating dependencies=='+ oldField 
              + '==' + newGPField +'==' + ex.getMessage() + '<br/>';
          exceptionMessage += 'ERROR: Exception while creating dependencies=='+ oldField 
              + '==' + newGPField +'==' + ex.getMessage() + '<br/>';
          System.debug('ERROR: Exception while creating dependencies=='+ ex.getMessage());
      }
  }
  
  public void finish(Database.BatchableContext BC) {
         if(!String.isEmpty(exceptionMessage)){
          Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
          mail.setTargetObjectId( UserInfo.getUserId() );
          mail.setSaveAsActivity( false );
          
          String subjectName = 'Error while creating dependencies';
          mail.setSubject( '[' + System.UserInfo.getOrganizationName() + '(' + System.UserInfo.getOrganizationId()  + ')] - ' + subjectName );        
          mail.setHtmlBody(exceptionMessage);
          Messaging.sendEmail( new Messaging.SingleEmailMessage[] { mail } );
      }
      if(!String.isEmpty(logMessage)){
          Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
          mail.setTargetObjectId( UserInfo.getUserId() );
          mail.setSaveAsActivity( false );
          
          String subjectName = 'Successfully created dependencies==ReadOnly==' + bReadOnly;
          mail.setSubject( '[' + System.UserInfo.getOrganizationName() + '(' + System.UserInfo.getOrganizationId()  + ')] - ' + subjectName );        
          mail.setHtmlBody(logMessage);
          Messaging.sendEmail( new Messaging.SingleEmailMessage[] { mail } );
      }
   }
      
  }