force-app/main/default/objects/leaseworks__Aircraft__c/leaseworks__Aircraft__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageAircraft</customHelpPage>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Lessor__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lessor__c</fullName>
    <formula>leaseworks__Lease__r.leaseworks__Lesor__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lessor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Manufacturer_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Manufacturer_GP__c</fullName>
    <inlineHelpText>The Manufacturer values come from a &quot;global picklist&quot; that applies throughout LeaseWorks. The list is used with aircraft or engine assets.</inlineHelpText>
    <label>Manufacturer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Manufacturer_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__MSN_Number__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__MSN_Number__c</fullName>
    <externalId>true</externalId>
    <label>Serial Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__TSN__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__TSN__c</fullName>
    <description>Time since aircraft was new</description>
    <inlineHelpText>Time since aircraft was new</inlineHelpText>
    <label>TSN</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/leaseworks__Constituent_Assembly__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageAircraft</customHelpPage>
    <label>Assembly</label>
    <nameField>
        <label>Assembly Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assemblies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__Attached_Aircraft__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Attached_Aircraft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Asset to which this assembly is currently associated to</description>
    <inlineHelpText>Asset to which this assembly is currently associated to temporarily or permanently</inlineHelpText>
    <label>Asset (Titled / Owned)</label>
    <referenceTo>leaseworks__Aircraft__c</referenceTo>
    <relationshipLabel>Assemblies (Titled / Owned)</relationshipLabel>
    <relationshipName>Constituent_Assemblies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__Description__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Description__c</fullName>
    <label>Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__Engine_Thrust__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Thrust__c</fullName>
    <label>Z_Unused_2308 Engine Variant</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>122</fullName>
            </value>
            <value>
                <fullName>124</fullName>
            </value>
            <value>
                <fullName>3B1</fullName>
            </value>
            <value>
                <fullName>3B2</fullName>
            </value>
            <value>
                <fullName>3C1</fullName>
            </value>
            <value>
                <fullName>5A1</fullName>
            </value>
            <value>
                <fullName>5A3</fullName>
            </value>
            <value>
                <fullName>5A4</fullName>
            </value>
            <value>
                <fullName>5A5</fullName>
            </value>
            <value>
                <fullName>5B1</fullName>
            </value>
            <value>
                <fullName>5B2</fullName>
            </value>
            <value>
                <fullName>5B3</fullName>
            </value>
            <value>
                <fullName>5B4</fullName>
            </value>
            <value>
                <fullName>5B5</fullName>
            </value>
            <value>
                <fullName>5B6</fullName>
            </value>
            <value>
                <fullName>5B7</fullName>
            </value>
            <value>
                <fullName>5B8</fullName>
            </value>
            <value>
                <fullName>5B9</fullName>
            </value>
            <value>
                <fullName>5C2</fullName>
            </value>
            <value>
                <fullName>5C3</fullName>
            </value>
            <value>
                <fullName>5C4</fullName>
            </value>
            <value>
                <fullName>7B22</fullName>
            </value>
            <value>
                <fullName>7B24</fullName>
            </value>
            <value>
                <fullName>7B26</fullName>
            </value>
            <value>
                <fullName>7B27</fullName>
            </value>
            <value>
                <fullName>V2500-A1</fullName>
            </value>
            <value>
                <fullName>V2522-A5</fullName>
            </value>
            <value>
                <fullName>V2524-A5</fullName>
            </value>
            <value>
                <fullName>V2527-A5</fullName>
            </value>
            <value>
                <fullName>V2527E-A5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__Manufacturer_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Manufacturer_GP__c</fullName>
    <label>Manufacturer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Manufacturer_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__Part_Number__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Part_Number__c</fullName>
    <description>This is an informational field. Use it to record the part number of the major component, when required.</description>
    <inlineHelpText>This is an informational field. Use it to record the part number of the major component, when required.</inlineHelpText>
    <label>Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__TSN__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__TSN__c</fullName>
    <description>Time since new</description>
    <inlineHelpText>Time Since New</inlineHelpText>
    <label>TSN</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Engine_Template__c/leaseworks__Engine_Template__c.object-meta.xml
<CustomObject>
    <label>Engine Template</label>
    <nameField>
        <label>Engine Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engine Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Engine_Template__c/fields/leaseworks__Current_Catalog_Year__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Current_Catalog_Year__c</fullName>
    <label>Current Catalog Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Engine_Template__c/fields/leaseworks__Manufacturer_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Manufacturer_GP__c</fullName>
    <label>Manufacturer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Manufacturer_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Engine_Template__c/fields/leaseworks__Part_Number__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Part_Number__c</fullName>
    <label>Z_Unused_2404_Part Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Engine_Template_Thrust__c/leaseworks__Engine_Template_Thrust__c.object-meta.xml
<CustomObject>
    <description>[MODULE: NA]
[LOAD: No]
[PREREQUISITES: NA]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Engine Template Thrust</label>
    <nameField>
        <label>Engine Template Thrust Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engine Template Thrust</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Engine_Template_Thrust__c/fields/leaseworks__Engine_Template__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Template__c</fullName>
    <label>Engine Template</label>
    <referenceTo>leaseworks__Engine_Template__c</referenceTo>
    <relationshipLabel>Engine Template Thrust</relationshipLabel>
    <relationshipName>Engine_Template_Thrust</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/leaseworks__Engine_Template_Thrust__c/fields/leaseworks__Thrust_Settings__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Thrust_Settings__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Thrust setting refers to the specific degree of power and force at which an aircraft&apos;s engines are configured to operate.</description>
    <inlineHelpText>Thrust setting refers to the specific degree of power and force at which an aircraft&apos;s engines are configured to operate.</inlineHelpText>
    <label>Thrust Settings</label>
    <referenceTo>leaseworks__Engine_Thrust__c</referenceTo>
    <relationshipLabel>Engine Template Thrust</relationshipLabel>
    <relationshipName>Engine_Template_Thrust</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lessor__c/leaseworks__Lessor__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPage</customHelpPage>
    <description>Details of the Lessor</description>
    <label>Setup</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Lessor__c/fields/leaseworks__Lease_Logo__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease_Logo__c</fullName>
    <defaultValue>&quot;https://c.na11.content.force.com/servlet/servlet.ImageServer?id=015G0000001SwrR&amp;oid=00DG0000000ggTD&amp;lastMod=1352235828000&quot;</defaultValue>
    <label>Company Logo URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/leaseworks__LLP_Template__c/leaseworks__LLP_Template__c.object-meta.xml
<CustomObject>
    <label>LLP Template</label>
    <nameField>
        <label>LLP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LLP Template</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__LLP_Template__c/fields/leaseworks__Description__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Description__c</fullName>
    <label>Z_Unused Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__LLP_Template__c/fields/leaseworks__Engine_Template__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Template__c</fullName>
    <label>Engine Template</label>
    <referenceTo>leaseworks__Engine_Template__c</referenceTo>
    <relationshipName>LLP_Template</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/leaseworks__LLP_Template__c/fields/leaseworks__IIN__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__IIN__c</fullName>
    <description>LLP Location identification number</description>
    <inlineHelpText>LLP Location identification number</inlineHelpText>
    <label>IIN</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__LLP_Template__c/fields/leaseworks__Life_Limit_Cycles__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Life_Limit_Cycles__c</fullName>
    <description>Default Life Limit is the certified limit provided by OEM.</description>
    <inlineHelpText>Limit used to calculate the remaining cycle.</inlineHelpText>
    <label>Default Life Limit (Cycles)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__LLP_Template__c/fields/leaseworks__Part_Name__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Part_Name__c</fullName>
    <label>Part Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__LLP_Template__c/fields/leaseworks__Part_Number__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Part_Number__c</fullName>
    <inlineHelpText>Part number that will be used as default for the Engine stack</inlineHelpText>
    <label>Default Part Number</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__LLP_Template__c/fields/leaseworks__Position_LLPT__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Position_LLPT__c</fullName>
    <description>Unique position of the LLP on the engine. LLP Name and Position should be unique to identify exact Life Limited Part</description>
    <inlineHelpText>Unique position of the LLP on the engine. LLP Name and Position should be unique to identify exact Life Limited Part</inlineHelpText>
    <label>Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/leaseworks__Manufacturer_Global.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ACMS</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus</fullName>
    </customValue>
    <customValue>
        <fullName>APIC</fullName>
    </customValue>
    <customValue>
        <fullName>BF Goodrich</fullName>
    </customValue>
    <customValue>
        <fullName>Boeing</fullName>
    </customValue>
    <customValue>
        <fullName>Bombardier</fullName>
    </customValue>
    <customValue>
        <fullName>CFM</fullName>
        <label>CFMI</label>
    </customValue>
    <customValue>
        <fullName>Dassault</fullName>
    </customValue>
    <customValue>
        <fullName>Dowty Rotol</fullName>
    </customValue>
    <customValue>
        <fullName>Embraer</fullName>
    </customValue>
    <customValue>
        <fullName>Engine Alliance</fullName>
    </customValue>
    <customValue>
        <fullName>GE</fullName>
    </customValue>
    <customValue>
        <fullName>General Electric</fullName>
    </customValue>
    <customValue>
        <fullName>Goodrich</fullName>
    </customValue>
    <customValue>
        <fullName>Goodrich Corporation</fullName>
    </customValue>
    <customValue>
        <fullName>Hamilton Sundstrand</fullName>
    </customValue>
    <customValue>
        <fullName>Honeywell</fullName>
    </customValue>
    <customValue>
        <fullName>Honeywell-Allied Signal</fullName>
    </customValue>
    <customValue>
        <fullName>IAE</fullName>
    </customValue>
    <customValue>
        <fullName>Liebherr Aerospace</fullName>
    </customValue>
    <customValue>
        <fullName>McDonnell Douglas (Boeing)</fullName>
        <label>McDonnell Douglas</label>
    </customValue>
    <customValue>
        <fullName>Messier Dowty</fullName>
    </customValue>
    <customValue>
        <fullName>Not specified</fullName>
    </customValue>
    <customValue>
        <fullName>Pratt &amp; Whitney</fullName>
    </customValue>
    <customValue>
        <fullName>Rolls-Royce</fullName>
    </customValue>
    <customValue>
        <fullName>Safran Landing Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Sundstrand</fullName>
    </customValue>
    <customValue>
        <fullName>United Technologies Corporation</fullName>
    </customValue>
    <customValue>
        <fullName>Airbus SAS</fullName>
        <isActive>false</isActive>
        <label>Airbus SAS</label>
    </customValue>
    <customValue>
        <fullName>Rolls Royce</fullName>
        <isActive>false</isActive>
        <label>Rolls Royce</label>
    </customValue>
    <masterLabel>Manufacturer</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestBatchUpdateLLPRecord.cls
@istest
public class TestBatchUpdateLLPRecord {
    @istest
    private static void testLLPUpdate(){
          leaseworks__Engine_Thrust__c engineThrust = new leaseworks__Engine_Thrust__c();
        engineThrust.Name = 'Default';
        insert engineThrust;
        leaseworks__Lessor__c testLessor = new leaseworks__Lessor__c(Name='TestLessor', leaseworks__Lease_Logo__c='http://abcd.lease-works.com/a.gif'
				 );
            insert testLessor;
            
      
        
        List<leaseworks__Engine_Template__c> engTempList = new List<leaseworks__Engine_Template__c>();
        leaseworks__Engine_Template__c EngTemp1 = new leaseworks__Engine_Template__c(Name='Engine Template 1',leaseworks__Manufacturer_GP__c ='Airbus'
                                                             ,leaseworks__Current_Catalog_Year__c='2010');
        engTempList.add(EngTemp1);

        leaseworks__Engine_Template__c EngTemp2 = new leaseworks__Engine_Template__c(Name='Engine Template 2',leaseworks__Manufacturer_GP__c ='Boeing'
        ,leaseworks__Current_Catalog_Year__c='2011');
        engTempList.add(EngTemp2);

       
        insert engTempList;
        leaseworks__Engine_Template_Thrust__c engTmplThrust = new leaseworks__Engine_Template_Thrust__c (
            Name = 'Test1',
            leaseworks__Engine_Template__c = engTempList[0].id, leaseworks__Thrust_Settings__c = engineThrust.id
        );
       // insert engTmplThrust;
        List<leaseworks__LLP_Template__c> ListLLPTempRec = New List<leaseworks__LLP_Template__c> ();
        leaseworks__LLP_Template__c LLP1 = new leaseworks__LLP_Template__c(Name='Booster Spool',leaseworks__Engine_Template__c=engTempList[0].Id ,leaseworks__Part_Name__c='Booster Spool',
                                                  leaseworks__Part_Number__c='13456',leaseworks__Position_LLPT__c=11,leaseworks__Life_Limit_Cycles__c=11000,leaseworks__IIN__c='222');
        leaseworks__LLP_Template__c LLP2 = new leaseworks__LLP_Template__c(Name='Booster Spool',leaseworks__Engine_Template__c=engTempList[0].Id ,leaseworks__Part_Name__c='Booster Spool',
                                                  leaseworks__Part_Number__c='11111',leaseworks__Position_LLPT__c=42,leaseworks__Life_Limit_Cycles__c=10500,leaseworks__IIN__c='112');
        leaseworks__LLP_Template__c LLP3 = new leaseworks__LLP_Template__c(Name='Spool',leaseworks__Engine_Template__c=engTempList[0].Id ,leaseworks__Part_Name__c='Spool',
                                                  leaseworks__Part_Number__c='12345',leaseworks__Position_LLPT__c=null,leaseworks__Life_Limit_Cycles__c=10000,leaseworks__IIN__c='111');
        ListLLPTempRec.add(LLP1); 
        ListLLPTempRec.add(LLP2); 
        ListLLPTempRec.add(LLP3);
        
        insert ListLLPTempRec;
        
        leaseworks__Aircraft__c aircraft = new leaseworks__Aircraft__c(Name='TestAircraft',leaseworks__MSN_Number__c='TestMSN1');
        insert aircraft;
         Id idRecordType=Schema.SObjectType.leaseworks__Constituent_Assembly__c.getRecordTypeInfosByDeveloperName().get('Engine').getRecordTypeId();
       leaseworks__Constituent_Assembly__c cs= new leaseworks__Constituent_Assembly__c(
            Name='Test_Engine_1',
            leaseworks__Attached_Aircraft__c= aircraft.Id, 
            leaseworks__Description__c ='Test_Engine_1', 
            leaseworks__TSN__c=10000, leaseworks__CSN__c=5000,
            leaseworks__Engine_Thrust_Setting__c=engineThrust.id,
            leaseworks__Type__c = 'Engine 1',
            leaseworks__Serial_Number__c = 'Test_Engine_1',leaseworks__Engine_Template_CA__c=engTempList[0].id,
            recordtypeId=idRecordType);
        insert cs;
        test.starttest();
        BatchUpdateLLPRecords.callBatchUpdateLLPRecords();
        test.stoptest();
    }

}