force-app/main/default/objects/leaseworks__Aircraft__c/leaseworks__Aircraft__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageAircraft</customHelpPage>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Lease__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field automatically fills with the current active Lease record linked to this Asset, identified by the &#39;Active&#39; field (leaseworks__Active__c) set to &#39;True&#39;. In the absence of an active Lease on this Asset (following the described logic), the system will clear this field. [This process is executed through a scheduled job that runs daily.]</description>
    <inlineHelpText>This field is automatically filled with the current active Lease record linked to this Asset, determined by the &#39;Active&#39; field being set to &#39;True&#39;. If there is no active Lease associated with this Asset (following the logic described), the system will clear this field.</inlineHelpText>
    <label>Lease</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Selected Lease has already different Asset assigned, please change the Lease before saving this Asset</errorMessage>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>leaseworks__Lease__c.leaseworks__Aircraft__c</valueField>
        </filterItems>
        <filterItems>
            <field>leaseworks__Lease__c.leaseworks__Aircraft__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Lease__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Aircrafts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Credit_Memo__c/leaseworks__Credit_Memo__c.object-meta.xml
<CustomObject>
    <description>Credit memo object
Enables users to document and track instances where customers are owed refunds or credits due to various reasons such as returned merchandise, pricing adjustments, or billing errors.
Population Requirement Details: Conditionally Required if legacy data loading is required
[MODULE: Finance]
[LOAD: Yes]
[PREREQUISITES: Lessee]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Credit Memo #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Credit_Memo__c/fields/leaseworks__Asset__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>leaseworks__Aircraft__c.leaseworks__Status__c</field>
            <operation>notEqual</operation>
            <value>Sold</value>
        </filterItems>
        <filterItems>
            <field>leaseworks__Aircraft__c.leaseworks__Sold__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Aircraft__c</referenceTo>
    <relationshipLabel>Asset</relationshipLabel>
    <relationshipName>Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Credit_Memo__c/fields/leaseworks__Credit_Memo_Date__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Credit_Memo_Date__c</fullName>
    <label>Credit Memo Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Credit_Memo__c/fields/leaseworks__Invoice__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the invoice when we are creating credit memo corrections.</description>
    <inlineHelpText>Lookup to the invoice when we are creating credit memo corrections.</inlineHelpText>
    <label>_Source Invoice</label>
    <referenceTo>leaseworks__Invoice__c</referenceTo>
    <relationshipLabel>Credit Memos</relationshipLabel>
    <relationshipName>Credit_Memos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Credit_Memo__c/fields/leaseworks__Lease__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>leaseworks__Lease__c.leaseworks__Lessee_New__c</field>
            <operation>equals</operation>
            <valueField>$Source.leaseworks__Lessee_New__c</valueField>
        </filterItems>
        <filterItems>
            <field>leaseworks__Lease__c.leaseworks__Operator_New__c</field>
            <operation>equals</operation>
            <valueField>$Source.leaseworks__Lessee_New__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Lease__c</referenceTo>
    <relationshipLabel>Credit Memo</relationshipLabel>
    <relationshipName>Credit_Memo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/leaseworks__Invoice__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageLease</customHelpPage>
    <description>Generic Object to hold Invoice information.</description>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__For_Period_Ending_F__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__For_Period_Ending_F__c</fullName>
    <formula>IF(
   ISNULL(leaseworks__Month_Ending__c) ,  DATE( YEAR(ADDMONTHS(leaseworks__Invoice_Date__c,1) ) ,MONTH(ADDMONTHS(leaseworks__Invoice_Date__c,1)),1) - 1, leaseworks__Month_Ending__c

)</formula>
    <label>For Period Ending</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Lease__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease__c</fullName>
    <label>Contract</label>
    <referenceTo>leaseworks__Lease__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/leaseworks__Invoice__c/fields/leaseworks__Y_Hidden_Asumd_Inv__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Y_Hidden_Asumd_Inv__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is a Z_Unused field, and It is used to identify the Docgen pdf generated for invoice records.</description>
    <label>_Generate From Docgen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/leaseworks__Lease__c.object-meta.xml
<CustomObject>
    <description>Central table for Lease Agreement/contract headers, storing essential details like start/end dates, current status, and associated asset reference.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Aircraft__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Aircraft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Specify the asset this lease is in relation to</inlineHelpText>
    <label>Asset</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>leaseworks__Aircraft__c.leaseworks__Status__c</field>
            <operation>equals</operation>
            <value>Available, Assigned</value>
        </filterItems>
        <filterItems>
            <field>$Source.leaseworks__Lease_Type_Status__c</field>
            <operation>equals</operation>
            <value>LOI</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non-Lease Agreement</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Aircraft__c</referenceTo>
    <relationshipLabel>Related Lease</relationshipLabel>
    <relationshipName>Leases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchPowerBIExportDocument.cls
/**
* @description       : Batch created to Download Report From Power Bi
* Caller:            : BatchPowerBIRequestPoller(Once the polling is completed for a give record,
*                      the batch "BatchPowerBiExportDocument" is invoked to get the file and store it 
*                       to the desired location)
* @author            : ChangeMeIn@UserSettingsUnder.SFDoc
* @group             : 
* 
**/

public class BatchPowerBIExportDocument implements Database.Batchable<sObject>, Database.AllowsCallouts,Database.Stateful{
    private map<id,string> mapOfRecordsForDownload;
    private string typeOfRecord;
    private boolean isBulkInvoicing;
    private string errorMessage='';
    /*
* @params:
*        map<id,string> mapOfRecordsForDownload : 
*                                              id- Record Id
*                                              string - File location retrieved from Export Request +accesstoken 
*        accesstoken : AccessToken To Power Bi App
*        typeOfRecord : Type of Sobject record
*        isBulkInvoicing : Boolean to check if the request is from Bulk Invoicing
*        retryCounter : The number of times batch is re-executed for a given record
* 
*/
    public BatchPowerBiExportDocument(map<id,string> mapOfRecordsForDownload,string typeOfRecord,boolean isBulkInvoicing){
        this.mapOfRecordsForDownload=mapOfRecordsForDownload;
        this.typeOfRecord=typeOfRecord;
        this.isBulkInvoicing=isBulkInvoicing;
    }
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Set<Id> SetIDs = mapOfRecordsForDownload.keySet();
        String query = 'SELECT id,name  FROM ' + typeOfRecord + ' WHERE Id in : SetIDs';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<sObject> lstRecords)
    {
        string recordId=lstRecords[0].id;
        try{
            
            string tokens=mapOfRecordsForDownload.get(recordId);
            string fileUrl=tokens.substringbefore('+');
            fileUrl=fileUrl.substringafter(':');
            string accesstoken=tokens.substringafter('+');
            accesstoken=accesstoken.substringafter(':');
            HttpRequest req = new HttpRequest();
            req.setEndpoint(fileUrl);
            req.setMethod('GET');
            req.setHeader('Authorization', 'Bearer ' + accessToken);
            Http http = new Http();
            HttpResponse res = http.send(req);
            system.debug(LoggingLevel.DEBUG,'response '+res.getbody());
            if (res.getStatusCode() != 200 || test.isrunningtest()) {
                PowerBIReportUtil.createExceptionLog('Error while Generating PowerBI Document for record Id'+recordId,'Export Request',string.valueof(res.getbody()),recordId);
                if(isBulkInvoicing){
                    PowerBIReportUtil.updateLineLog(recordID,string.valueof(res.getStatusCode())+' - '+res.getBody());
                    
                }
            }
            
            
            if(!isBulkInvoicing && typeOfRecord=='leaseworks__invoice__c'){
                leaseworks__invoice__c inv =new leaseworks__invoice__c();
                inv.id= recordId;
                //Update leaseworks__Y_Hidden_Asumd_Inv__c to true ,so that the line log is created when document is generated from Quick Action Button
                inv.leaseworks__Y_Hidden_Asumd_Inv__c =true;
                leaseworks.LWGlobalUtils.setTriggersAndWFsOff();
                update inv;
                leaseworks.LWGlobalUtils.setTriggersAndWFsOn();
                
                
                
                
            }
            
            
            string recordName=typeOfRecord+'-'+(String)lstRecords[0].get('Name');
            if(typeOfRecord=='leaseworks__invoice__c'){
                leaseworks__Invoice__c inv=[SELECT Id,name,leaseworks__For_Period_Ending_F__c,leaseworks__Lease__r.leaseworks__Aircraft__r.name from leaseworks__Invoice__c where id=:recordId];
               /////// String monthName =inv.leaseworks__For_Period_Ending_F__c.format('MMMM');                
               string monthyear=PowerBIReportUtil.convertMonth(inv.leaseworks__For_Period_Ending_F__c);
               recordName= inv.leaseworks__Lease__r.leaseworks__Aircraft__r.name==null?'':inv.leaseworks__Lease__r.leaseworks__Aircraft__r.name+' - '
                   +inv.name+' - '+monthyear;
            }
            if(typeOfRecord=='leaseworks__Credit_Memo__c'){
                
                leaseworks__Credit_Memo__c creditmemo=[ SELECT id,leaseworks__Asset__r.name,name,leaseworks__Credit_Memo_Date__c from leaseworks__Credit_Memo__c  where id=:recordId];
                
                recordName= creditmemo.leaseworks__Asset__r.name==null?'':creditmemo.leaseworks__Asset__r.name+' - '
                    +creditmemo.name;
            }
            if(typeOfRecord=='leaseworks__Aircraft__c'){
                leaseworks__Aircraft__c aircraft=[   SELECT id,name from leaseworks__Aircraft__c where id=:recordId];
                string monthyear=PowerBIReportUtil.convertMonth(Date.today());
                recordName= aircraft.name+' - '+monthyear;
            }
            if(typeOfRecord=='leaseworks__Lease__c'){
                leaseworks__Lease__c lease=[  SELECT id,name from leaseworks__Lease__c  where id=:recordId];
                string monthyear=PowerBIReportUtil.convertMonth(Date.today());
                recordName= lease.name+' - '+monthyear;
            }
            // Always create a NEW ContentVersion (new ContentDocument)
            ContentVersion cv = new ContentVersion();
            cv.PathOnClient = 'PowerBI_Report.pdf';
            cv.VersionData = res.getBodyAsBlob();
            cv.Title = recordName+'.pdf';
            insert cv;
            
            // Get the new ContentDocumentId
            ContentVersion contentDocId = [SELECT ContentDocumentId,ContentDocument.FileType FROM ContentVersion WHERE Id = :cv.Id];
            system.debug('doctype '+contentDocId.ContentDocument.FileType);
            // Link the new document to the record
            ContentDocumentLink link = new ContentDocumentLink();
            link.ContentDocumentId = contentDocId.ContentDocumentId;
            link.LinkedEntityId = recordId;
            link.ShareType = 'V';
            link.Visibility = 'AllUsers';
            insert link;
            System.debug(LoggingLevel.DEBUG,' Report saved and linked to ' + recordId);
            
        }
        catch(Exception e){
            PowerBIReportUtil.createExceptionLog('Error while Generating PowerBI Document for record Id'+recordId,'Export Request',string.valueof(e.getmessage()),recordId);  
            errorMessage+='Request to generate document for record with id  '+ recordId+' has failed with following error.'+'<br/>' +e.getmessage();
        }
        
    }
    public void finish(Database.BatchableContext BC){
        if(!(String.isBlank(errorMessage)) && !isBulkInvoicing){
            PowerBIReportUtil.sendEmailonError('Error while Invoking Power BI Polling Request to Generate Document',errorMessage );
        }
    }
    
    
}