force-app/main/default/objects/leaseworks__Aircraft__c/leaseworks__Aircraft__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageAircraft</customHelpPage>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Asset_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Asset_Type_GP__c</fullName>
    <label>Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Asset_Type_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Asset_Variant_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Asset_Variant_GP__c</fullName>
    <label>Asset Variant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Asset_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Asset_Variant_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__CSN__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__CSN__c</fullName>
    <description>Cycles since new - # of take offs and landing since the ac was new</description>
    <inlineHelpText>Cycles since new - # of take offs and landing since the ac was new</inlineHelpText>
    <label>CSN</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Date_of_Manufacture__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Date_of_Manufacture__c</fullName>
    <label>Date of Manufacture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Maintenance_Program__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Maintenance_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use &quot;MP Update&quot; button to change Maintenance Program assignment.</inlineHelpText>
    <label>Maintenance Program</label>
    <referenceTo>leaseworks__Maintenance_Program__c</referenceTo>
    <relationshipLabel>Assets (Maintenance Program)</relationshipLabel>
    <relationshipName>Aircraft</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__MSN_Number__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__MSN_Number__c</fullName>
    <externalId>true</externalId>
    <label>Serial Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Status__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Status__c</fullName>
    <description>Tells you if this aircraft is available to be lease out</description>
    <inlineHelpText>Available: can be linked to a Lease; Assigned: Linked to a Lease. Other values are self-explanatory.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <label>In Fleet - Lease Attached</label>
            </value>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>In Fleet - Available</label>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Consigned</fullName>
            </value>
            <value>
                <fullName>Not Purchased</fullName>
                <label>Asset created but purchase did not close</label>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__TSN__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__TSN__c</fullName>
    <description>Time since aircraft was new</description>
    <inlineHelpText>Time since aircraft was new</inlineHelpText>
    <label>TSN</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Assembly_Event_Info__c/leaseworks__Assembly_Event_Info__c.object-meta.xml
<CustomObject>
    <description>[MODULE: NA]
[LOAD: No]
[PREREQUISITES: NA]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Projected Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projected Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Assembly_Event_Info__c/fields/leaseworks__Maintenance_Program__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Maintenance_Program__c</fullName>
    <formula>leaseworks__Maintenance_Program_Event__r.leaseworks__Maintenance_Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Maintenance Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Assembly_Event_Info__c/fields/leaseworks__Status__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Status__c</fullName>
    <formula>if(leaseworks__Projection_Status__c == &quot;Error&quot;,
IMAGE(
    &quot;/resource/&quot; + $Setup.leaseworks__LeaseWorksSettings__c.leaseworks__Package_Prefix__c + &quot;RedeliveryStatusImages/Red.png&quot;,
    &quot;Error&quot;,
    18,
    18
  ),

if(
leaseworks__Projection_Status__c == &quot;Warning&quot;,
IMAGE(
        &quot;/resource/&quot; + $Setup.leaseworks__LeaseWorksSettings__c.leaseworks__Package_Prefix__c + &quot;RedeliveryStatusImages/Orange.png&quot;,
        &quot;Warning&quot;,
        18,
        18
      ),

if(
leaseworks__Projection_Status__c == &quot;Complete&quot;,

IMAGE(
      &quot;/resource/&quot; + $Setup.leaseworks__LeaseWorksSettings__c.leaseworks__Package_Prefix__c + &quot;RedeliveryStatusImages/Green.png&quot;,
      &quot;Complete&quot;,
      18,
      18
    ),

if(
AND(leaseworks__Projection_Status__c == &quot;&quot;, leaseworks__Event_Type__c ==&apos;LLP Replacement&apos;), 
   &apos;LLP&apos;,
if(
leaseworks__Projection_Status__c == &quot;&quot;,
&quot;&quot;,

if(
 OR(ISBLANK(leaseworks__Maintenance_Program_Event__c) , ISNULL(leaseworks__Maintenance_Program_Event__c)) , &apos;&apos; , &apos;LLP&apos;
))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/leaseworks__Constituent_Assembly__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageAircraft</customHelpPage>
    <label>Assembly</label>
    <nameField>
        <label>Assembly Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assemblies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__Asset_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Asset_Type_GP__c</fullName>
    <label>Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Asset_Type_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__CSN__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__CSN__c</fullName>
    <description>Cycles since new</description>
    <inlineHelpText>Cycles Since New</inlineHelpText>
    <label>CSN</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__Date_of_Manufacture__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Date_of_Manufacture__c</fullName>
    <inlineHelpText>Enter Date of Manufacture for calendar limitations calculation</inlineHelpText>
    <label>Date of Manufacture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__Engine_Thrust__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Thrust__c</fullName>
    <label>Z_Unused_2308 Engine Variant</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>122</fullName>
            </value>
            <value>
                <fullName>124</fullName>
            </value>
            <value>
                <fullName>3B1</fullName>
            </value>
            <value>
                <fullName>3B2</fullName>
            </value>
            <value>
                <fullName>3C1</fullName>
            </value>
            <value>
                <fullName>5A1</fullName>
            </value>
            <value>
                <fullName>5A3</fullName>
            </value>
            <value>
                <fullName>5A4</fullName>
            </value>
            <value>
                <fullName>5A5</fullName>
            </value>
            <value>
                <fullName>5B1</fullName>
            </value>
            <value>
                <fullName>5B2</fullName>
            </value>
            <value>
                <fullName>5B3</fullName>
            </value>
            <value>
                <fullName>5B4</fullName>
            </value>
            <value>
                <fullName>5B5</fullName>
            </value>
            <value>
                <fullName>5B6</fullName>
            </value>
            <value>
                <fullName>5B7</fullName>
            </value>
            <value>
                <fullName>5B8</fullName>
            </value>
            <value>
                <fullName>5B9</fullName>
            </value>
            <value>
                <fullName>5C2</fullName>
            </value>
            <value>
                <fullName>5C3</fullName>
            </value>
            <value>
                <fullName>5C4</fullName>
            </value>
            <value>
                <fullName>7B22</fullName>
            </value>
            <value>
                <fullName>7B24</fullName>
            </value>
            <value>
                <fullName>7B26</fullName>
            </value>
            <value>
                <fullName>7B27</fullName>
            </value>
            <value>
                <fullName>V2500-A1</fullName>
            </value>
            <value>
                <fullName>V2522-A5</fullName>
            </value>
            <value>
                <fullName>V2524-A5</fullName>
            </value>
            <value>
                <fullName>V2527-A5</fullName>
            </value>
            <value>
                <fullName>V2527E-A5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__Status__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Status__c</fullName>
    <description>Current status of the assembly</description>
    <inlineHelpText>This is the old status field, for admin reference only.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>On Ground</fullName>
            </value>
            <value>
                <fullName>On Aircarft</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>In Shop</fullName>
            </value>
            <value>
                <fullName>LOI</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Consigned</fullName>
            </value>
            <value>
                <fullName>TBC</fullName>
            </value>
            <value>
                <fullName>Pending Sale</fullName>
            </value>
            <value>
                <fullName>Stored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__TSN__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__TSN__c</fullName>
    <description>Time since new</description>
    <inlineHelpText>Time Since New</inlineHelpText>
    <label>TSN</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/leaseworks__Maintenance_Program__c/leaseworks__Maintenance_Program__c.object-meta.xml
<CustomObject>
    <description>The &quot;Maintenance Program&quot; table encompasses all maintenance programs that can be associated with different assets. Typically, a single maintenance program is established for each type of aircraft. However, users might prefer to set up unique programs for each operator or region to tailor maintenance intervals and the cost of shop visits. This can be uploaded either prior to configuring an aircraft or afterward. However, possessing a Maintenance Program is a prerequisite for projecting maintenance events.
[MODULE: Asset]
[LOAD: Optional]
[PREREQUISITES: NA]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Maintenance Program</label>
    <nameField>
        <label>Maintenance Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Program</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Maintenance_Program__c/fields/leaseworks__Asset_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Asset_Type_GP__c</fullName>
    <label>Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Asset_Type_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Maintenance_Program__c/fields/leaseworks__Asset_Variant_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Asset_Variant_GP__c</fullName>
    <label>Asset Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Asset_Variant_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Maintenance_Program__c/fields/leaseworks__Current_Catalog_Year__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Current_Catalog_Year__c</fullName>
    <description>Catalog year for which Maintenance Program Event is set.</description>
    <inlineHelpText>Catalog year for which Maintenance Program Event is set.</inlineHelpText>
    <label>Current Catalog Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/leaseworks__Asset_Type_Global.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A220</fullName>
    </customValue>
    <customValue>
        <fullName>A300 B4</fullName>
    </customValue>
    <customValue>
        <fullName>A310</fullName>
    </customValue>
    <customValue>
        <fullName>A318</fullName>
    </customValue>
    <customValue>
        <fullName>A319</fullName>
    </customValue>
    <customValue>
        <fullName>A320</fullName>
    </customValue>
    <customValue>
        <fullName>A320Neo</fullName>
    </customValue>
    <customValue>
        <fullName>A321</fullName>
    </customValue>
    <customValue>
        <fullName>A321Neo</fullName>
    </customValue>
    <customValue>
        <fullName>A330</fullName>
    </customValue>
    <customValue>
        <fullName>A340</fullName>
    </customValue>
    <customValue>
        <fullName>A350</fullName>
    </customValue>
    <customValue>
        <fullName>A380</fullName>
    </customValue>
    <customValue>
        <fullName>727</fullName>
        <label>B727</label>
    </customValue>
    <customValue>
        <fullName>737</fullName>
        <label>B737</label>
    </customValue>
    <customValue>
        <fullName>737MAX</fullName>
        <label>B737MAX</label>
    </customValue>
    <customValue>
        <fullName>B737NG</fullName>
    </customValue>
    <customValue>
        <fullName>747</fullName>
        <label>B747</label>
    </customValue>
    <customValue>
        <fullName>757</fullName>
        <label>B757</label>
    </customValue>
    <customValue>
        <fullName>767</fullName>
        <label>B767</label>
    </customValue>
    <customValue>
        <fullName>777</fullName>
        <label>B777</label>
    </customValue>
    <customValue>
        <fullName>787</fullName>
        <label>B787</label>
    </customValue>
    <customValue>
        <fullName>CRJ-200</fullName>
    </customValue>
    <customValue>
        <fullName>E190</fullName>
    </customValue>
    <customValue>
        <fullName>ERJ-135</fullName>
    </customValue>
    <customValue>
        <fullName>MD82</fullName>
    </customValue>
    <customValue>
        <fullName>Engine Assets</fullName>
    </customValue>
    <customValue>
        <fullName>CF34-3B1</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80A2</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80C2</fullName>
    </customValue>
    <masterLabel>Asset Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/leaseworks__Asset_Variant_Global.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A220-371</fullName>
    </customValue>
    <customValue>
        <fullName>A220-100</fullName>
    </customValue>
    <customValue>
        <fullName>A220-300</fullName>
    </customValue>
    <customValue>
        <fullName>A310-304</fullName>
    </customValue>
    <customValue>
        <fullName>A318-111</fullName>
    </customValue>
    <customValue>
        <fullName>A319-111</fullName>
    </customValue>
    <customValue>
        <fullName>A319-112</fullName>
    </customValue>
    <customValue>
        <fullName>A319-113</fullName>
    </customValue>
    <customValue>
        <fullName>A319-132</fullName>
    </customValue>
    <customValue>
        <fullName>A320-211</fullName>
    </customValue>
    <customValue>
        <fullName>A320-214</fullName>
    </customValue>
    <customValue>
        <fullName>A320-216</fullName>
    </customValue>
    <customValue>
        <fullName>A320-232</fullName>
    </customValue>
    <customValue>
        <fullName>A320-233</fullName>
    </customValue>
    <customValue>
        <fullName>A320-271N</fullName>
    </customValue>
    <customValue>
        <fullName>A321-131</fullName>
    </customValue>
    <customValue>
        <fullName>A321-200XLR</fullName>
    </customValue>
    <customValue>
        <fullName>A321-211</fullName>
    </customValue>
    <customValue>
        <fullName>A321-231</fullName>
    </customValue>
    <customValue>
        <fullName>A321-251NX</fullName>
    </customValue>
    <customValue>
        <fullName>A321-271NX</fullName>
    </customValue>
    <customValue>
        <fullName>A330-202</fullName>
    </customValue>
    <customValue>
        <fullName>A330-223</fullName>
    </customValue>
    <customValue>
        <fullName>A330-243</fullName>
    </customValue>
    <customValue>
        <fullName>A330-302</fullName>
    </customValue>
    <customValue>
        <fullName>A330-322</fullName>
    </customValue>
    <customValue>
        <fullName>A330-323</fullName>
    </customValue>
    <customValue>
        <fullName>A330-343</fullName>
    </customValue>
    <customValue>
        <fullName>A330-941</fullName>
    </customValue>
    <customValue>
        <fullName>A340-312</fullName>
    </customValue>
    <customValue>
        <fullName>737-9</fullName>
    </customValue>
    <masterLabel>Asset Variant</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestBatchUpdatePELocal.cls
@isTest
public class TestBatchUpdatePELocal {
    
           @testSetup
        static void createTestClassDataFirst(){
            leaseworks__Maintenance_Program__c maitenanceProgramRec = new leaseworks__Maintenance_Program__c(
                Name='Test_MP_1',leaseworks__Asset_Type_GP__c = '777', leaseworks__Asset_Variant_GP__c = null, 
                leaseworks__Current_Catalog_Year__c ='2010');
            insert maitenanceProgramRec;
            
            if(maitenanceProgramRec.Id != null){
				Date tempDate = Date.newInstance(2015, 1, 1);                
               leaseworks__Aircraft__c assetRecord = new leaseworks__Aircraft__c(
                	Name = 'Test_Asset_1', leaseworks__MSN_Number__c = 'Test_Asset_1', leaseworks__TSN__c = 0, leaseworks__CSN__c = 0,
                	leaseworks__Asset_Type_GP__c = '737MAX', leaseworks__Asset_Variant_GP__c = '737-9', 
                    leaseworks__Maintenance_Program__c = maitenanceProgramRec.Id,
                	leaseworks__Status__c='Available', leaseworks__Date_of_Manufacture__c = tempDate.toStartOfMonth()
            		);
                	LeaseWareUtilslocal.clearFromTrigger();
                	insert assetRecord;
                
                leaseworks__Engine_Thrust__c customLookupRecord = new leaseworks__Engine_Thrust__c(name = 'Default');
                	LeaseWareUtilslocal.clearFromTrigger();
                	insert customLookupRecord;
                
                if(assetRecord.Id != null && customLookupRecord.Id != null){ 
                    Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.leaseworks__Constituent_Assembly__c.getRecordTypeInfosByDeveloperName();
            		List<leaseworks__Constituent_Assembly__c> listAssemblies = new List<leaseworks__Constituent_Assembly__c>();
            		listAssemblies.add(new leaseworks__Constituent_Assembly__c(
                		Name = 'Test_AirFrame_1',leaseworks__Attached_Aircraft__c= assetRecord.Id,
                		leaseworks__TSN__c=10000, leaseworks__CSN__c=5000, leaseworks__Last_TSN_Utilization__c=0, leaseworks__Last_CSN_Utilization__c =0,
                		leaseworks__Date_of_Manufacture__c= tempDate, 
                		leaseworks__Type__c = 'Airframe', leaseworks__Serial_Number__c='Test_AirFrame_1', 
                		RecordTypeId=rtMapByName.get('Airframe').getRecordTypeId()));
            
            			System.debug('listAssemblies*** ' + listAssemblies);
                    	LeaseWareUtilsLocal.clearFromTrigger();
                    	insert listAssemblies;
                }
            }
        }
    
    @isTest
    public static void test1(){
        	
        leaseworks__Aircraft__c assetRecord = [Select id, leaseworks__Maintenance_Program__c from leaseworks__Aircraft__c
                                  Where leaseworks__MSN_Number__c = 'Test_Asset_1' 
                                  Limit 1];
        
        leaseworks__Constituent_Assembly__c assemblyRecord = [Select id, leaseworks__Type__c from leaseworks__Constituent_Assembly__c
                                                  Where leaseworks__Serial_Number__c = 'Test_AirFrame_1'
                                                  And leaseworks__Attached_Aircraft__c = :assetRecord.Id
                                                  Limit 1];
        
        //Creating first custom projected event record
        leaseworks__Assembly_Event_Info__c customProjectedEventRecord1  = new leaseworks__Assembly_Event_Info__c(
            leaseworks__Constituent_Assembly__c = assemblyRecord.Id
        );
        insert customProjectedEventRecord1;
        
        Test.startTest();
        Database.executeBatch(new BatchUpdatePELocal(),10);
        Test.stopTest();
    }
    
    @isTest
    public static void test2(){
        	
        leaseworks__Aircraft__c assetRecord = [Select id, leaseworks__Maintenance_Program__c from leaseworks__Aircraft__c
                                  Where leaseworks__MSN_Number__c = 'Test_Asset_1' 
                                  Limit 1];
        
        leaseworks__Constituent_Assembly__c assemblyRecord = [Select id, leaseworks__Type__c from leaseworks__Constituent_Assembly__c
                                                  Where leaseworks__Serial_Number__c = 'Test_AirFrame_1'
                                                  And leaseworks__Attached_Aircraft__c = :assetRecord.Id
                                                  Limit 1];
        
        //Creating first custom projected event record
        leaseworks__Assembly_Event_Info__c customProjectedEventRecord1  = new leaseworks__Assembly_Event_Info__c(
            leaseworks__Constituent_Assembly__c = assemblyRecord.Id
        );
        insert customProjectedEventRecord1;
        
        Test.startTest();
        Database.executeBatch(new BatchUpdatePELocal('error'),10);
        Test.stopTest();
    }
}