force-app/main/default/objects/leaseworks__Aircraft__c/leaseworks__Aircraft__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageAircraft</customHelpPage>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Lease__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field automatically fills with the current active Lease record linked to this Asset, identified by the &#39;Active&#39; field (leaseworks__Active__c) set to &#39;True&#39;. In the absence of an active Lease on this Asset (following the described logic), the system will clear this field. [This process is executed through a scheduled job that runs daily.]</description>
    <inlineHelpText>This field is automatically filled with the current active Lease record linked to this Asset, determined by the &#39;Active&#39; field being set to &#39;True&#39;. If there is no active Lease associated with this Asset (following the logic described), the system will clear this field.</inlineHelpText>
    <label>Lease</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Selected Lease has already different Asset assigned, please change the Lease before saving this Asset</errorMessage>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>leaseworks__Lease__c.leaseworks__Aircraft__c</valueField>
        </filterItems>
        <filterItems>
            <field>leaseworks__Lease__c.leaseworks__Aircraft__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Lease__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Aircrafts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft_Proposal__c/leaseworks__Aircraft_Proposal__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.
[MODULE: NA]
[LOAD: No]
[PREREQUISITES: NA]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Asset in Deal</label>
    <nameField>
        <label>Name (MSN)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets in Deal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Aircraft_Proposal__c/fields/leaseworks__Lease__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lease</label>
    <referenceTo>leaseworks__Lease__c</referenceTo>
    <relationshipLabel>Assets in Deal (Lease)</relationshipLabel>
    <relationshipName>Assets_in_Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft_Proposal__c/fields/LOI_Date__c.field-meta.xml
<CustomField>
    <fullName>LOI_Date__c</fullName>
    <description>The date at which Letter of Intent (LOI) is executed for a given Asset in Deal</description>
    <inlineHelpText>The date at which Letter of Intent (LOI) is executed for a given Asset in Deal</inlineHelpText>
    <label>LOI Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/leaseworks__Lease__c.object-meta.xml
<CustomObject>
    <description>Central table for Lease Agreement/contract headers, storing essential details like start/end dates, current status, and associated asset reference.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Active__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Active__c</fullName>
    <description>Active? Lease checkbox for reporting. Driven by Lease Start and Lease End/Redelivery date, based on Setup -&gt; Custom Settings -&gt; Leaseworks Settings -&gt; Active Lease logic. Active? Override field on the Lease page can override the calculation formula when selected by user</description>
    <formula>If(
        (ISPICKVAL( leaseworks__Active_Override__c ,&#39;Default&#39;) || ISBLANK(TEXT( leaseworks__Active_Override__c ))) , 
        AND(leaseworks__Lease_Start_Date_New__c &lt;= TODAY(),
        
        IF($Setup.leaseworks__LeaseWorksSettings__c.leaseworks__Active_Lease_Logic__c=&#39;Redelivery Date&#39;,
        true,
        leaseworks__Lease_End_Date_New__c&gt;= TODAY()
        ),
        
        (TEXT(leaseworks__Lease_Type_Status__c)==&#39;On Lease&#39;),
        !ISBLANK(leaseworks__Aircraft__c) ),If(ISPICKVAL( leaseworks__Active_Override__c ,&#39;Active&#39;),True,False))</formula>
    <inlineHelpText>Active? Lease checkbox for reporting. Driven by Lease Start and Lease End or Redelivery date based on the configuration. Active? Override field on the Lease page can override the calculation formula when selected by user</inlineHelpText>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Lease_Start_Date_New__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease_Start_Date_New__c</fullName>
    <label>Contract Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Lease_Type_Status__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease_Type_Status__c</fullName>
    <inlineHelpText>Select the appropriate status of the lease, and remember to update the dates section if necessary</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LOI</fullName>
                <default>true</default>
                <label>LOI</label>
            </value>
            <value>
                <fullName>Awaiting Delivery</fullName>
            </value>
            <value>
                <fullName>On Lease</fullName>
            </value>
            <value>
                <fullName>Redelivered</fullName>
            </value>
            <value>
                <fullName>Lease Expired/Terminated</fullName>
                <label>Terminated</label>
            </value>
            <value>
                <fullName>On Lease [R]</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Sold On Lease</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/pro_Asset_Target_Audit__c.object-meta.xml
<CustomObject>
    <description>This junction object contains lookups to the Asset, Contract, and Target objects.</description>
    <label>Asset Target Audit</label>
    <nameField>
        <displayFormat>Audit-{0000000}</displayFormat>
        <label>Asset Target Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Target Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_Asset__c.field-meta.xml
<CustomField>
    <fullName>pro_Asset__c</fullName>
    <description>The asset for which contract end dates are being tracked.</description>
    <label>Asset</label>
    <referenceTo>leaseworks__Aircraft__c</referenceTo>
    <relationshipLabel>Asset Target Audits</relationshipLabel>
    <relationshipName>Asset_Target_Audits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_Asset_in_Deal__c.field-meta.xml
<CustomField>
    <fullName>pro_Asset_in_Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The asset in deal which has the LOI Date field populated.</description>
    <label>Asset in Deal</label>
    <referenceTo>leaseworks__Aircraft_Proposal__c</referenceTo>
    <relationshipLabel>Asset Target Audits</relationshipLabel>
    <relationshipName>Asset_Target_Audits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_Contract__c.field-meta.xml
<CustomField>
    <fullName>pro_Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Contract whose end date defines the Target record to relate.</description>
    <label>Contract</label>
    <referenceTo>leaseworks__Lease__c</referenceTo>
    <relationshipLabel>Asset Target Audits</relationshipLabel>
    <relationshipName>Asset_Target_Audits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_Progress__c.field-meta.xml
<CustomField>
    <fullName>pro_Progress__c</fullName>
    <description>À formula that drives the Progress of a target based on actions taken to the target record itself or the associated Contract, or Asset in Deal</description>
    <formula>IF( 
    pro_Target_Readjusted__c = TRUE,
    &#39;Target Cancelled&#39;,

    /* CLOSED STATUSES */
    IF(
        AND(
            pro_LOId_Outside_Target_Year__c = TRUE,
            pro_Contract_Extended__c = FALSE
        ),
        &#39;Achieved - LOI Other&#39;,

        IF(
            AND(
                NOT(ISBLANK(pro_Asset_in_Deal__c)),
                NOT(ISBLANK(pro_Asset_in_Deal__r.LOI_Date__c)),
                pro_Contract_Extended__c = FALSE
            ),
            &#39;Achieved - LOI&#39;,

            IF(
                pro_New_Contract_Signed__c = TRUE,
                &#39;Achieved - No LOI&#39;,

                IF(
                    pro_Contract_Extended__c = TRUE,
                    &#39;Achieved - Contract Extended&#39;,

                    /* CANCELLED / EXPIRED STATUSES */
                    IF(
                        OR(
                            ISPICKVAL(
                                pro_Contract__r.leaseworks__Lease_Type_Status__c,
                                &#39;Cancelled&#39;
                            ),
                            ISPICKVAL(
                                pro_Contract__r.leaseworks__Lease_Type_Status__c,
                                &#39;Lease Expired/Terminated&#39;
                            ),
                            AND(
                                pro_Contract__r.leaseworks__Active__c = FALSE,
                                pro_Contract__r.leaseworks__Lease_Start_Date_New__c &lt;= TODAY()
                            )
                        ),
                        &#39;Target Cancelled&#39;,

                        /* MOVED TO TRADING (now checked after cancelled logic) */
                        IF(
                            pro_Moved_To_Trading__c = TRUE,
                            &#39;Moved To Trading&#39;,

                            /* OPEN STATUSES */
                            IF(
                                pro_Target_Forecast__r.pro_End_Date__c &lt; ADDMONTHS(TODAY(), 12),
                                &#39;Open - Target Date Exceeded&#39;,
                                &#39;Open&#39;
                            )
                        )
                    )
                )
            )
        )
    )
)</formula>
    <label>Progress</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_Progress_Picklist__c.field-meta.xml
<CustomField>
    <fullName>pro_Progress_Picklist__c</fullName>
    <description>Whenever an Asset Target Audit record is updated and it affects the Outcome formula field, this picklist gets  updated to the same value before save.</description>
    <label>Progress Picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Achieved - LOI Other</fullName>
            </value>
            <value>
                <fullName>Achieved - LOI</fullName>
            </value>
            <value>
                <fullName>Achieved - Contract Extended</fullName>
            </value>
            <value>
                <fullName>Achieved - No LOI</fullName>
            </value>
            <value>
                <fullName>Open - Target Date Exceeded</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Moved To Trading</fullName>
            </value>
            <value>
                <fullName>Target Cancelled</fullName>
            </value>
            <value>
                <fullName>Re-Opened</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_Target__c.field-meta.xml
<CustomField>
    <fullName>pro_Target__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The target record which matches the end date of the related Contract.</description>
    <label>Target</label>
    <referenceTo>pro_Target__c</referenceTo>
    <relationshipLabel>Asset Target Audits</relationshipLabel>
    <relationshipName>Asset_Target_Audits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_Target_Forecast__c.field-meta.xml
<CustomField>
    <fullName>pro_Target_Forecast__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The target record which matches the end date of the related Contract.</description>
    <label>Target Forecast</label>
    <referenceTo>pro_Target__c</referenceTo>
    <relationshipLabel>Asset Target Audits</relationshipLabel>
    <relationshipName>Asset_Target_Audits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pro_Target__c/pro_Target__c.object-meta.xml
<CustomObject>
    <label>Target</label>
    <nameField>
        <label>Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pro_Target__c/fields/pro_End_Date__c.field-meta.xml
<CustomField>
    <fullName>pro_End_Date__c</fullName>
    <inlineHelpText>Roll Offs End Date</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Pro_ProgressSyncHandler.cls
/**
 * Pro_ProgressSyncHandler
 *
 * Calculates the correct progress status for pro_Asset_Target_Audit__c records
 * and sets pro_Progress_Picklist__c to keep it in sync with the pro_Progress__c
 * formula field. Called from Pro_ProgressSyncTrigger (before insert/update).
 *
 * Replicates the full pro_Progress__c formula logic in Apex so that the picklist
 * value is set from queried source data rather than depending on formula
 * recalculation timing within the same transaction.
 *
 * @author  Developer Agent
 * @date    2026-03-05
 * @story   US-011
 */
public without sharing class Pro_ProgressSyncHandler {
  @TestVisible
  private static final String STATUS_TARGET_CANCELLED = 'Target Cancelled';
  @TestVisible
  private static final String STATUS_ACHIEVED_LOI_OTHER = 'Achieved - LOI Other';
  @TestVisible
  private static final String STATUS_ACHIEVED_LOI = 'Achieved - LOI';
  @TestVisible
  private static final String STATUS_ACHIEVED_NO_LOI = 'Achieved - No LOI';
  @TestVisible
  private static final String STATUS_ACHIEVED_CONTRACT_EXTENDED = 'Achieved - Contract Extended';
  @TestVisible
  private static final String STATUS_MOVED_TO_TRADING = 'Moved To Trading';
  @TestVisible
  private static final String STATUS_OPEN_EXCEEDED = 'Open - Target Date Exceeded';
  @TestVisible
  private static final String STATUS_OPEN = 'Open';

  private static final String CONTRACT_STATUS_CANCELLED = 'Cancelled';
  private static final String CONTRACT_STATUS_EXPIRED = 'Lease Expired/Terminated';

  /**
   * Entry point called from before-save trigger. Queries related records
   * in bulk, calculates progress for each ATA, and sets the picklist field.
   *
   * @param newRecords Trigger.new list of ATA records being inserted/updated
   * @param oldMap     Trigger.oldMap (null on insert)
   */
  public static void syncProgressPicklist(
    List<pro_Asset_Target_Audit__c> newRecords,
    Map<Id, pro_Asset_Target_Audit__c> oldMap
  ) {
    Set<Id> contractIds = new Set<Id>();
    Set<Id> aidIds = new Set<Id>();
    Set<Id> targetIds = new Set<Id>();
    Set<Id> assetIds = new Set<Id>();

    for (pro_Asset_Target_Audit__c ata : newRecords) {
      if (ata.pro_Contract__c != null) {
        contractIds.add(ata.pro_Contract__c);
      }
      if (ata.pro_Asset_in_Deal__c != null) {
        aidIds.add(ata.pro_Asset_in_Deal__c);
      }
      if (ata.pro_Target_Forecast__c != null) {
        targetIds.add(ata.pro_Target_Forecast__c);
      }
      if (ata.pro_Asset__c != null) {
        assetIds.add(ata.pro_Asset__c);
      }
    }

    Map<Id, leaseworks__Lease__c> contractMap = contractIds.isEmpty()
      ? new Map<Id, leaseworks__Lease__c>()
      : new Map<Id, leaseworks__Lease__c>(
          [
            SELECT
              Id,
              leaseworks__Lease_Type_Status__c,
              leaseworks__Active__c,
              leaseworks__Lease_Start_Date_New__c
            FROM leaseworks__Lease__c
            WHERE Id IN :contractIds
            /* No SECURITY_ENFORCED on any query in this handler — this is a
               system-level data-integrity mechanism. FLS/CRUD enforcement would
               break progress sync for system-context operations (e.g., Flow
               DML in SystemModeWithoutSharing). */
          ]
        );

    Map<Id, leaseworks__Aircraft_Proposal__c> aidMap = aidIds.isEmpty()
      ? new Map<Id, leaseworks__Aircraft_Proposal__c>()
      : new Map<Id, leaseworks__Aircraft_Proposal__c>(
          [
            SELECT Id, LOI_Date__c
            FROM leaseworks__Aircraft_Proposal__c
            WHERE Id IN :aidIds
          ]
        );

    Map<Id, pro_Target__c> targetMap = targetIds.isEmpty()
      ? new Map<Id, pro_Target__c>()
      : new Map<Id, pro_Target__c>(
          [
            SELECT Id, pro_End_Date__c
            FROM pro_Target__c
            WHERE Id IN :targetIds
          ]
        );

    Map<Id, leaseworks__Aircraft__c> assetMap = assetIds.isEmpty()
      ? new Map<Id, leaseworks__Aircraft__c>()
      : new Map<Id, leaseworks__Aircraft__c>(
          [
            SELECT Id, pro_Target_Moved_To_Trading__c
            FROM leaseworks__Aircraft__c
            WHERE Id IN :assetIds
          ]
        );

    for (pro_Asset_Target_Audit__c ata : newRecords) {
      String calculated = calculateProgress(
        ata,
        contractMap,
        aidMap,
        targetMap,
        assetMap
      );
      if (calculated != ata.pro_Progress_Picklist__c) {
        ata.pro_Progress_Picklist__c = calculated;
      }
    }
  }

  /**
   * Replicates the pro_Progress__c formula logic using queried related-record
   * values. Evaluates conditions in the same precedence order as the formula.
   *
   * Sub-formula replication:
   *   pro_LOId_Outside_Target_Year__c =
   *     YEAR(pro_LOI_Date__c) < YEAR(pro_Target_End_Date_1__c) - 1
   *     OR YEAR(pro_LOI_Date__c) >= YEAR(pro_Target_End_Date_1__c)
   *     (null dates cause condition to evaluate as false)
   *
   *   pro_Moved_To_Trading__c = pro_Asset__r.pro_Target_Moved_To_Trading__c
   *
   * @param ata         The ATA record (from Trigger.new, fields available)
   * @param contractMap Queried Contracts keyed by Id
   * @param aidMap      Queried AiD records keyed by Id
   * @param targetMap   Queried Targets keyed by Id
   * @param assetMap    Queried Assets keyed by Id
   * @return The calculated progress status string
   */
  @TestVisible
  private static String calculateProgress(
    pro_Asset_Target_Audit__c ata,
    Map<Id, leaseworks__Lease__c> contractMap,
    Map<Id, leaseworks__Aircraft_Proposal__c> aidMap,
    Map<Id, pro_Target__c> targetMap,
    Map<Id, leaseworks__Aircraft__c> assetMap
  ) {
    // 1. Target Readjusted -> Target Cancelled
    if (ata.pro_Target_Readjusted__c == true) {
      return STATUS_TARGET_CANCELLED;
    }

    // Replicate pro_LOId_Outside_Target_Year__c sub-formula
    // pro_LOI_Date__c and pro_Target_End_Date_1__c are formula fields on ATA
    // that are not available in before-save trigger context. Use queried values.
    Boolean loIdOutsideTargetYear = calculateLoIdOutsideTargetYear(
      ata,
      aidMap,
      targetMap
    );

    // 2. LOI'd outside target year and not contract extended -> Achieved - LOI Other
    if (loIdOutsideTargetYear && ata.pro_Contract_Extended__c != true) {
      return STATUS_ACHIEVED_LOI_OTHER;
    }

    // 3. AiD linked with LOI Date and not contract extended -> Achieved - LOI
    if (ata.pro_Asset_in_Deal__c != null) {
      leaseworks__Aircraft_Proposal__c aid = aidMap.get(
        ata.pro_Asset_in_Deal__c
      );
      if (
        aid != null &&
        aid.LOI_Date__c != null &&
        ata.pro_Contract_Extended__c != true
      ) {
        return STATUS_ACHIEVED_LOI;
      }
    }

    // 4. New Contract Signed -> Achieved - No LOI
    if (ata.pro_New_Contract_Signed__c == true) {
      return STATUS_ACHIEVED_NO_LOI;
    }

    // 5. Contract Extended -> Achieved - Contract Extended
    if (ata.pro_Contract_Extended__c == true) {
      return STATUS_ACHIEVED_CONTRACT_EXTENDED;
    }

    // 6. Contract status cancelled/expired or inactive with past start date -> Target Cancelled
    if (ata.pro_Contract__c != null) {
      leaseworks__Lease__c contract = contractMap.get(ata.pro_Contract__c);
      if (contract != null && isContractCancelledOrExpired(contract)) {
        return STATUS_TARGET_CANCELLED;
      }
    }

    // 7. Moved To Trading (from Asset) -> Moved To Trading
    Boolean movedToTrading = calculateMovedToTrading(ata, assetMap);
    if (movedToTrading) {
      return STATUS_MOVED_TO_TRADING;
    }

    // 8. Target end date < today + 12 months -> Open - Target Date Exceeded
    if (ata.pro_Target_Forecast__c != null) {
      pro_Target__c target = targetMap.get(ata.pro_Target_Forecast__c);
      if (
        target != null &&
        target.pro_End_Date__c != null &&
        target.pro_End_Date__c < Date.today().addMonths(12)
      ) {
        return STATUS_OPEN_EXCEEDED;
      }
    }

    // 9. Default -> Open
    return STATUS_OPEN;
  }

  /**
   * Replicates the pro_LOId_Outside_Target_Year__c formula.
   * Formula: OR(
   *   YEAR(pro_LOI_Date__c) < YEAR(pro_Target_End_Date_1__c) - 1,
   *   YEAR(pro_LOI_Date__c) >= YEAR(pro_Target_End_Date_1__c)
   * )
   * pro_LOI_Date__c is a formula = pro_Asset_in_Deal__r.LOI_Date__c
   * pro_Target_End_Date_1__c is a formula = pro_Target_Forecast__r.pro_End_Date__c
   * Neither is available in before-save context, so use queried related data.
   *
   * Note: The formula metadata specifies formulaTreatBlanksAs = BlankAsZero.
   * However, BlankAsZero only affects direct numeric field references, not
   * function return values. YEAR(null_date) returns null regardless of the
   * BlankAsZero setting, and null comparisons evaluate to false. If YEAR(null)
   * returned 0, every ATA without an AiD would evaluate as "Achieved - LOI
   * Other" — which does not happen in production. Verified against live org
   * data: null dates cause the condition to evaluate as false.
   */
  private static Boolean calculateLoIdOutsideTargetYear(
    pro_Asset_Target_Audit__c ata,
    Map<Id, leaseworks__Aircraft_Proposal__c> aidMap,
    Map<Id, pro_Target__c> targetMap
  ) {
    // Get LOI Date from queried AiD (replicates pro_LOI_Date__c formula)
    Date loiDate = null;
    if (ata.pro_Asset_in_Deal__c != null) {
      leaseworks__Aircraft_Proposal__c aid = aidMap.get(
        ata.pro_Asset_in_Deal__c
      );
      if (aid != null) {
        loiDate = aid.LOI_Date__c;
      }
    }

    // Get Target End Date from queried Target (replicates pro_Target_End_Date_1__c formula)
    Date targetEndDate = null;
    if (ata.pro_Target_Forecast__c != null) {
      pro_Target__c target = targetMap.get(ata.pro_Target_Forecast__c);
      if (target != null) {
        targetEndDate = target.pro_End_Date__c;
      }
    }

    // If either date is null, YEAR(null) in SF formula context causes the
    // comparison to evaluate as false (confirmed by live org data).
    if (loiDate == null || targetEndDate == null) {
      return false;
    }

    Integer loiYear = loiDate.year();
    Integer targetEndYear = targetEndDate.year();

    return (loiYear < targetEndYear - 1) || (loiYear >= targetEndYear);
  }

  /**
   * Replicates the pro_Moved_To_Trading__c formula.
   * Formula: pro_Asset__r.pro_Target_Moved_To_Trading__c
   * BlankAsZero: null -> false
   */
  private static Boolean calculateMovedToTrading(
    pro_Asset_Target_Audit__c ata,
    Map<Id, leaseworks__Aircraft__c> assetMap
  ) {
    if (ata.pro_Asset__c == null) {
      return false;
    }
    leaseworks__Aircraft__c asset = assetMap.get(ata.pro_Asset__c);
    if (asset == null) {
      return false;
    }
    return asset.pro_Target_Moved_To_Trading__c == true;
  }

  /**
   * Evaluates whether a Contract meets the cancelled/expired conditions from
   * the formula: Lease_Type_Status = 'Cancelled' or 'Lease Expired/Terminated',
   * or (Active = false AND Lease_Start_Date_New <= TODAY()).
   */
  private static Boolean isContractCancelledOrExpired(
    leaseworks__Lease__c contract
  ) {
    String status = contract.leaseworks__Lease_Type_Status__c;
    if (
      status == CONTRACT_STATUS_CANCELLED ||
      status == CONTRACT_STATUS_EXPIRED
    ) {
      return true;
    }
    if (
      contract.leaseworks__Active__c == false &&
      contract.leaseworks__Lease_Start_Date_New__c != null &&
      contract.leaseworks__Lease_Start_Date_New__c <= Date.today()
    ) {
      return true;
    }
    return false;
  }
}