force-app/main/default/objects/leaseworks__Aircraft__c/leaseworks__Aircraft__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageAircraft</customHelpPage>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Lease__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field automatically fills with the current active Lease record linked to this Asset, identified by the &#39;Active&#39; field (leaseworks__Active__c) set to &#39;True&#39;. In the absence of an active Lease on this Asset (following the described logic), the system will clear this field. [This process is executed through a scheduled job that runs daily.]</description>
    <inlineHelpText>This field is automatically filled with the current active Lease record linked to this Asset, determined by the &#39;Active&#39; field being set to &#39;True&#39;. If there is no active Lease associated with this Asset (following the logic described), the system will clear this field.</inlineHelpText>
    <label>Lease</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Selected Lease has already different Asset assigned, please change the Lease before saving this Asset</errorMessage>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>leaseworks__Lease__c.leaseworks__Aircraft__c</valueField>
        </filterItems>
        <filterItems>
            <field>leaseworks__Lease__c.leaseworks__Aircraft__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Lease__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Aircrafts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__MSN_Number__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__MSN_Number__c</fullName>
    <externalId>true</externalId>
    <label>Serial Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/pro_Target_Moved_To_Trading__c.field-meta.xml
<CustomField>
    <fullName>pro_Target_Moved_To_Trading__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Box can be manually checked within the Target Management Console to flag that the Asset has been included in the Trading team&apos;s RFP and allow this to be reflected in the Asset Target Audit&apos;s Progress field. (Field API name retained as pro_Target_Moved_To_Trading__c — only the label and downstream UI references have changed.)</description>
    <inlineHelpText>Tick when the Asset has been included in the Trading team&apos;s RFP. Drives the Asset Target Audit&apos;s Progress field.</inlineHelpText>
    <label>Included in Trading RFP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft_Proposal__c/leaseworks__Aircraft_Proposal__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.
[MODULE: NA]
[LOAD: No]
[PREREQUISITES: NA]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Asset in Deal</label>
    <nameField>
        <label>Name (MSN)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets in Deal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Aircraft_Proposal__c/fields/leaseworks__Aircraft__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Aircraft__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Select the asset from your fleet to be included in the deal.</inlineHelpText>
    <label>Asset</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>leaseworks__Aircraft__c.leaseworks__Sold__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Aircraft__c</referenceTo>
    <relationshipLabel>Related Deals</relationshipLabel>
    <relationshipName>Marketing_Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft_Proposal__c/fields/leaseworks__Lease__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lease</label>
    <referenceTo>leaseworks__Lease__c</referenceTo>
    <relationshipLabel>Assets in Deal (Lease)</relationshipLabel>
    <relationshipName>Assets_in_Deal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft_Proposal__c/fields/LOI_Date__c.field-meta.xml
<CustomField>
    <fullName>LOI_Date__c</fullName>
    <description>The date at which Letter of Intent (LOI) is executed for a given Asset in Deal</description>
    <inlineHelpText>The date at which Letter of Intent (LOI) is executed for a given Asset in Deal</inlineHelpText>
    <label>LOI Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/leaseworks__Lease__c.object-meta.xml
<CustomObject>
    <description>Central table for Lease Agreement/contract headers, storing essential details like start/end dates, current status, and associated asset reference.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Aircraft__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Aircraft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Specify the asset this lease is in relation to</inlineHelpText>
    <label>Asset</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>leaseworks__Aircraft__c.leaseworks__Status__c</field>
            <operation>equals</operation>
            <value>Available, Assigned</value>
        </filterItems>
        <filterItems>
            <field>$Source.leaseworks__Lease_Type_Status__c</field>
            <operation>equals</operation>
            <value>LOI</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non-Lease Agreement</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Aircraft__c</referenceTo>
    <relationshipLabel>Related Lease</relationshipLabel>
    <relationshipName>Leases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Lease_End_Date_New__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease_End_Date_New__c</fullName>
    <label>Contract End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Lease_Start_Date_New__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease_Start_Date_New__c</fullName>
    <label>Contract Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Lease_Type_Status__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease_Type_Status__c</fullName>
    <inlineHelpText>Select the appropriate status of the lease, and remember to update the dates section if necessary</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LOI</fullName>
                <default>true</default>
                <label>LOI</label>
            </value>
            <value>
                <fullName>Awaiting Delivery</fullName>
            </value>
            <value>
                <fullName>On Lease</fullName>
            </value>
            <value>
                <fullName>Redelivered</fullName>
            </value>
            <value>
                <fullName>Lease Expired/Terminated</fullName>
                <label>Terminated</label>
            </value>
            <value>
                <fullName>On Lease [R]</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Sold On Lease</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/pro_Asset_Target_Audit__c.object-meta.xml
<CustomObject>
    <description>This junction object contains lookups to the Asset, Contract, and Target objects.</description>
    <label>Asset Target Audit</label>
    <nameField>
        <displayFormat>Audit-{0000000}</displayFormat>
        <label>Asset Target Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Target Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_Asset__c.field-meta.xml
<CustomField>
    <fullName>pro_Asset__c</fullName>
    <description>The asset for which contract end dates are being tracked.</description>
    <label>Asset</label>
    <referenceTo>leaseworks__Aircraft__c</referenceTo>
    <relationshipLabel>Asset Target Audits</relationshipLabel>
    <relationshipName>Asset_Target_Audits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_LOI_Date__c.field-meta.xml
<CustomField>
    <fullName>pro_LOI_Date__c</fullName>
    <formula>pro_Asset_in_Deal__r.LOI_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LOI Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_LOId_Outside_Target_Year__c.field-meta.xml
<CustomField>
    <fullName>pro_LOId_Outside_Target_Year__c</fullName>
    <formula>OR(
    YEAR(pro_LOI_Date__c) &lt; YEAR( pro_Target_End_Date__c ) - 1,
    YEAR(pro_LOI_Date__c) &gt;= YEAR( pro_Target_End_Date__c )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LOId Outside Target Year?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_Moved_To_Trading__c.field-meta.xml
<CustomField>
    <fullName>pro_Moved_To_Trading__c</fullName>
    <description>Pulls in the value from the Moved To Trading field on the Asset</description>
    <formula>pro_Asset__r.pro_Target_Moved_To_Trading__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Moved To Trading</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_Progress_Picklist__c.field-meta.xml
<CustomField>
    <fullName>pro_Progress_Picklist__c</fullName>
    <description>Whenever an Asset Target Audit record is updated and it affects the Outcome formula field, this picklist gets  updated to the same value before save.</description>
    <label>Progress Picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Achieved - LOI Other</fullName>
            </value>
            <value>
                <fullName>Achieved - LOI</fullName>
            </value>
            <value>
                <fullName>Achieved - Contract Extended</fullName>
            </value>
            <value>
                <fullName>Achieved - No LOI</fullName>
            </value>
            <value>
                <fullName>Open - Target Date Exceeded</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Moved To Trading</fullName>
            </value>
            <value>
                <fullName>Target Cancelled</fullName>
            </value>
            <value>
                <fullName>Re-Opened</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_Target__c.field-meta.xml
<CustomField>
    <fullName>pro_Target__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The target record which matches the end date of the related Contract.</description>
    <label>Target</label>
    <referenceTo>pro_Target__c</referenceTo>
    <relationshipLabel>Asset Target Audits</relationshipLabel>
    <relationshipName>Asset_Target_Audits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_Target_End_Date_1__c.field-meta.xml
<CustomField>
    <fullName>pro_Target_End_Date_1__c</fullName>
    <description>The End Date from the associated Target record</description>
    <formula>DATE(YEAR(pro_Target_Forecast__r.pro_End_Date__c), MONTH(pro_Target_Forecast__r.pro_End_Date__c), DAY(pro_Target_Forecast__r.pro_End_Date__c))</formula>
    <label>Target End Date Formula</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_Target_Forecast__c.field-meta.xml
<CustomField>
    <fullName>pro_Target_Forecast__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The target record which matches the end date of the related Contract.</description>
    <label>Target Forecast</label>
    <referenceTo>pro_Target__c</referenceTo>
    <relationshipLabel>Asset Target Audits</relationshipLabel>
    <relationshipName>Asset_Target_Audits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/pro_Asset_Target_Audit__c/fields/pro_Target_Readjusted__c.field-meta.xml
<CustomField>
    <fullName>pro_Target_Readjusted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Target Readjusted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/pro_Target__c/pro_Target__c.object-meta.xml
<CustomObject>
    <label>Target</label>
    <nameField>
        <label>Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pro_Target__c/fields/pro_End_Date__c.field-meta.xml
<CustomField>
    <fullName>pro_End_Date__c</fullName>
    <inlineHelpText>Roll Offs End Date</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/pro_Target__c/fields/pro_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>pro_Start_Date__c</fullName>
    <inlineHelpText>Roll Offs Start Date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Pro_ProgressSyncHandler_Test.cls
/**
 * Pro_ProgressSyncHandler_Test
 *
 * Unit tests for Pro_ProgressSyncHandler -- verifies all 8 status paths,
 * bulk processing, no-op optimisation, and null-lookup handling.
 *
 * Coverage target: 90%+ on Pro_ProgressSyncHandler.
 *
 * Test data notes:
 *  - pro_Asset_Target_Audit__c has Master-Detail to pro_Asset__c and
 *    pro_Target_Forecast__c. Parent records created first.
 *  - pro_LOId_Outside_Target_Year__c is a formula:
 *    YEAR(pro_LOI_Date__c) < YEAR(pro_Target_End_Date_1__c) - 1
 *    OR YEAR(pro_LOI_Date__c) >= YEAR(pro_Target_End_Date_1__c)
 *  - pro_Moved_To_Trading__c is a formula:
 *    pro_Asset__r.pro_Target_Moved_To_Trading__c
 *  - Neither formula field can be set directly; source fields must be set.
 *
 * @author  Developer Agent
 * @date    2026-03-05
 * @story   US-011
 */
@isTest
private class Pro_ProgressSyncHandler_Test {
  private static final Integer BULK_SIZE = 200;

  // ================================================================
  // TEST DATA SETUP
  // ================================================================

  @TestSetup
  static void setupTestData() {
    // Asset records (Master-Detail parent)
    List<leaseworks__Aircraft__c> assets = new List<leaseworks__Aircraft__c>();
    for (Integer i = 1; i <= 5; i++) {
      assets.add(
        new leaseworks__Aircraft__c(
          Name = 'Sync Test Aircraft ' + i,
          leaseworks__MSN_Number__c = 'MSN-SYNC-' + i,
          pro_Target_Moved_To_Trading__c = false
        )
      );
    }
    insert assets;

    // Target with end date far in the future (> today + 12 months -> Open)
    pro_Target__c targetFuture = new pro_Target__c(
      Name = 'Future Target',
      pro_Start_Date__c = Date.today().addMonths(18),
      pro_End_Date__c = Date.today().addMonths(24)
    );
    insert targetFuture;

    // Target with end date in the past (< today + 12 months -> Open - Target Date Exceeded)
    pro_Target__c targetPast = new pro_Target__c(
      Name = 'Past Target',
      pro_Start_Date__c = Date.today().addMonths(-6),
      pro_End_Date__c = Date.today().addMonths(6)
    );
    insert targetPast;

    // Contract record with Cancelled status
    leaseworks__Lease__c cancelledContract = new leaseworks__Lease__c(
      Name = 'Cancelled Contract',
      leaseworks__Lease_Type_Status__c = 'Cancelled',
      leaseworks__Lease_Start_Date_New__c = Date.today().addYears(-2),
      leaseworks__Lease_End_Date_New__c = Date.today().addYears(-1)
    );
    insert cancelledContract;

    // Note: AiD/Deal creation intentionally omitted from @TestSetup.
    // Deal/AiD objects have complex validation rules (Deal Rep, Counter Party,
    // Asset Type). LOI-related status paths are tested via direct calculateProgress
    // calls with mock maps to isolate handler logic from Deal/AiD validations.
  }

  // ================================================================
  // HELPER METHODS
  // ================================================================

  private static leaseworks__Aircraft__c getAsset(String nameLike) {
    return [
      SELECT Id, pro_Target_Moved_To_Trading__c
      FROM leaseworks__Aircraft__c
      WHERE Name LIKE :nameLike
      LIMIT 1
    ];
  }

  private static pro_Target__c getTarget(String nameLike) {
    return [
      SELECT Id, pro_End_Date__c
      FROM pro_Target__c
      WHERE Name LIKE :nameLike
      LIMIT 1
    ];
  }

  private static leaseworks__Lease__c getContract(String status) {
    return [
      SELECT Id
      FROM leaseworks__Lease__c
      WHERE leaseworks__Lease_Type_Status__c = :status
      LIMIT 1
    ];
  }

  /**
   * Builds a mock AiD map with a single entry for calculateProgress tests.
   * Uses a fabricated Id to avoid actual Deal/AiD DML.
   */
  private static Id MOCK_AID_ID =
    leaseworks__Aircraft_Proposal__c.SObjectType.getDescribe().getKeyPrefix() +
    '000000000001';

  private static Map<Id, leaseworks__Aircraft_Proposal__c> buildAidMap(
    Date loiDate
  ) {
    leaseworks__Aircraft_Proposal__c mockAid = new leaseworks__Aircraft_Proposal__c(
      Id = MOCK_AID_ID,
      LOI_Date__c = loiDate
    );
    return new Map<Id, leaseworks__Aircraft_Proposal__c>{
      MOCK_AID_ID => mockAid
    };
  }

  // ================================================================
  // STATUS PATH TESTS
  // ================================================================

  @isTest
  static void testTargetCancelled_Readjusted() {
    leaseworks__Aircraft__c asset = getAsset('Sync Test Aircraft 1');
    pro_Target__c target = getTarget('Future Target');

    pro_Asset_Target_Audit__c ata = new pro_Asset_Target_Audit__c(
      pro_Asset__c = asset.Id,
      pro_Target_Forecast__c = target.Id,
      pro_Target_Readjusted__c = true
    );

    Test.startTest();
    insert ata;
    Test.stopTest();

    pro_Asset_Target_Audit__c result = [
      SELECT pro_Progress_Picklist__c
      FROM pro_Asset_Target_Audit__c
      WHERE Id = :ata.Id
    ];
    System.assertEquals(
      Pro_ProgressSyncHandler.STATUS_TARGET_CANCELLED,
      result.pro_Progress_Picklist__c,
      'Readjusted ATA should have Target Cancelled status'
    );
  }

  @isTest
  static void testAchievedLoiOther() {
    // Test via direct calculateProgress to avoid Deal/AiD validation complexity.
    // LOI Date year = current year, Target End year = current year + 2
    // YEAR(LOI) < YEAR(TargetEnd) - 1 => current < current+1 => TRUE
    // So LOI'd Outside Target Year = TRUE, Contract Extended = false
    // => Achieved - LOI Other
    leaseworks__Aircraft__c asset = getAsset('Sync Test Aircraft 1');
    pro_Target__c target = getTarget('Future Target');

    Map<Id, leaseworks__Aircraft_Proposal__c> aidMap = buildAidMap(
      Date.today().addMonths(-3)
    );
    Map<Id, pro_Target__c> targetMap = new Map<Id, pro_Target__c>{
      target.Id => target
    };
    Map<Id, leaseworks__Aircraft__c> assetMap = new Map<Id, leaseworks__Aircraft__c>{
      asset.Id => asset
    };
    Map<Id, leaseworks__Lease__c> contractMap = new Map<Id, leaseworks__Lease__c>();

    pro_Asset_Target_Audit__c ata = new pro_Asset_Target_Audit__c(
      pro_Asset__c = asset.Id,
      pro_Target_Forecast__c = target.Id,
      pro_Asset_in_Deal__c = MOCK_AID_ID,
      pro_Contract_Extended__c = false,
      pro_Target_Readjusted__c = false,
      pro_New_Contract_Signed__c = false
    );

    Test.startTest();
    String result = Pro_ProgressSyncHandler.calculateProgress(
      ata,
      contractMap,
      aidMap,
      targetMap,
      assetMap
    );
    Test.stopTest();

    System.assertEquals(
      Pro_ProgressSyncHandler.STATUS_ACHIEVED_LOI_OTHER,
      result,
      'ATA with LOI outside target year should be Achieved - LOI Other'
    );
  }

  @isTest
  static void testAchievedLoi() {
    // Test via direct calculateProgress to avoid Deal/AiD validation complexity.
    // LOI Date year = current year, Target End year = current year + 1
    // YEAR(LOI) < YEAR(TargetEnd) - 1 = current year => FALSE
    // YEAR(LOI) >= YEAR(TargetEnd) = current year + 1 => FALSE
    // So LOI'd Outside = FALSE. AiD has LOI Date => Achieved - LOI
    leaseworks__Aircraft__c asset = getAsset('Sync Test Aircraft 1');

    // Target end date 12 months from now (year = current year + 1)
    pro_Target__c mockTarget = new pro_Target__c(
      Id = pro_Target__c.SObjectType.getDescribe().getKeyPrefix() +
        '000000000099'
    );
    mockTarget.pro_End_Date__c = Date.today().addMonths(12);

    Map<Id, leaseworks__Aircraft_Proposal__c> aidMap = buildAidMap(
      Date.today()
    );
    Map<Id, pro_Target__c> targetMap = new Map<Id, pro_Target__c>{
      mockTarget.Id => mockTarget
    };
    Map<Id, leaseworks__Aircraft__c> assetMap = new Map<Id, leaseworks__Aircraft__c>{
      asset.Id => asset
    };
    Map<Id, leaseworks__Lease__c> contractMap = new Map<Id, leaseworks__Lease__c>();

    pro_Asset_Target_Audit__c ata = new pro_Asset_Target_Audit__c(
      pro_Asset__c = asset.Id,
      pro_Target_Forecast__c = mockTarget.Id,
      pro_Asset_in_Deal__c = MOCK_AID_ID,
      pro_Contract_Extended__c = false,
      pro_Target_Readjusted__c = false,
      pro_New_Contract_Signed__c = false
    );

    Test.startTest();
    String result = Pro_ProgressSyncHandler.calculateProgress(
      ata,
      contractMap,
      aidMap,
      targetMap,
      assetMap
    );
    Test.stopTest();

    System.assertEquals(
      Pro_ProgressSyncHandler.STATUS_ACHIEVED_LOI,
      result,
      'ATA with AiD LOI Date and LOI within target year should be Achieved - LOI'
    );
  }

  @isTest
  static void testAchievedNoLoi() {
    leaseworks__Aircraft__c asset = getAsset('Sync Test Aircraft 2');
    pro_Target__c target = getTarget('Future Target');

    pro_Asset_Target_Audit__c ata = new pro_Asset_Target_Audit__c(
      pro_Asset__c = asset.Id,
      pro_Target_Forecast__c = target.Id,
      pro_New_Contract_Signed__c = true
    );

    Test.startTest();
    insert ata;
    Test.stopTest();

    pro_Asset_Target_Audit__c result = [
      SELECT pro_Progress_Picklist__c
      FROM pro_Asset_Target_Audit__c
      WHERE Id = :ata.Id
    ];
    System.assertEquals(
      Pro_ProgressSyncHandler.STATUS_ACHIEVED_NO_LOI,
      result.pro_Progress_Picklist__c,
      'ATA with New Contract Signed should be Achieved - No LOI'
    );
  }

  @isTest
  static void testAchievedContractExtended() {
    leaseworks__Aircraft__c asset = getAsset('Sync Test Aircraft 2');
    pro_Target__c target = getTarget('Future Target');

    pro_Asset_Target_Audit__c ata = new pro_Asset_Target_Audit__c(
      pro_Asset__c = asset.Id,
      pro_Target_Forecast__c = target.Id,
      pro_Contract_Extended__c = true
    );

    Test.startTest();
    insert ata;
    Test.stopTest();

    pro_Asset_Target_Audit__c result = [
      SELECT pro_Progress_Picklist__c
      FROM pro_Asset_Target_Audit__c
      WHERE Id = :ata.Id
    ];
    System.assertEquals(
      Pro_ProgressSyncHandler.STATUS_ACHIEVED_CONTRACT_EXTENDED,
      result.pro_Progress_Picklist__c,
      'ATA with Contract Extended should be Achieved - Contract Extended'
    );
  }

  @isTest
  static void testTargetCancelled_ContractStatus() {
    leaseworks__Aircraft__c asset = getAsset('Sync Test Aircraft 3');
    pro_Target__c target = getTarget('Future Target');
    leaseworks__Lease__c contract = getContract('Cancelled');

    pro_Asset_Target_Audit__c ata = new pro_Asset_Target_Audit__c(
      pro_Asset__c = asset.Id,
      pro_Target_Forecast__c = target.Id,
      pro_Contract__c = contract.Id
    );

    Test.startTest();
    insert ata;
    Test.stopTest();

    pro_Asset_Target_Audit__c result = [
      SELECT pro_Progress_Picklist__c
      FROM pro_Asset_Target_Audit__c
      WHERE Id = :ata.Id
    ];
    System.assertEquals(
      Pro_ProgressSyncHandler.STATUS_TARGET_CANCELLED,
      result.pro_Progress_Picklist__c,
      'ATA with cancelled Contract should be Target Cancelled'
    );
  }

  @isTest
  static void testMovedToTrading() {
    leaseworks__Aircraft__c asset = getAsset('Sync Test Aircraft 4');
    asset.pro_Target_Moved_To_Trading__c = true;
    update asset;

    pro_Target__c target = getTarget('Future Target');

    pro_Asset_Target_Audit__c ata = new pro_Asset_Target_Audit__c(
      pro_Asset__c = asset.Id,
      pro_Target_Forecast__c = target.Id
    );

    Test.startTest();
    insert ata;
    Test.stopTest();

    pro_Asset_Target_Audit__c result = [
      SELECT pro_Progress_Picklist__c
      FROM pro_Asset_Target_Audit__c
      WHERE Id = :ata.Id
    ];
    System.assertEquals(
      Pro_ProgressSyncHandler.STATUS_MOVED_TO_TRADING,
      result.pro_Progress_Picklist__c,
      'ATA with Asset Moved To Trading should be Moved To Trading'
    );
  }

  @isTest
  static void testOpenTargetDateExceeded() {
    leaseworks__Aircraft__c asset = getAsset('Sync Test Aircraft 1');
    pro_Target__c target = getTarget('Past Target');

    pro_Asset_Target_Audit__c ata = new pro_Asset_Target_Audit__c(
      pro_Asset__c = asset.Id,
      pro_Target_Forecast__c = target.Id
    );

    Test.startTest();
    insert ata;
    Test.stopTest();

    pro_Asset_Target_Audit__c result = [
      SELECT pro_Progress_Picklist__c
      FROM pro_Asset_Target_Audit__c
      WHERE Id = :ata.Id
    ];
    System.assertEquals(
      Pro_ProgressSyncHandler.STATUS_OPEN_EXCEEDED,
      result.pro_Progress_Picklist__c,
      'ATA with target end date within 12 months should be Open - Target Date Exceeded'
    );
  }

  @isTest
  static void testOpen() {
    leaseworks__Aircraft__c asset = getAsset('Sync Test Aircraft 1');
    pro_Target__c target = getTarget('Future Target');

    pro_Asset_Target_Audit__c ata = new pro_Asset_Target_Audit__c(
      pro_Asset__c = asset.Id,
      pro_Target_Forecast__c = target.Id
    );

    Test.startTest();
    insert ata;
    Test.stopTest();

    pro_Asset_Target_Audit__c result = [
      SELECT pro_Progress_Picklist__c
      FROM pro_Asset_Target_Audit__c
      WHERE Id = :ata.Id
    ];
    System.assertEquals(
      Pro_ProgressSyncHandler.STATUS_OPEN,
      result.pro_Progress_Picklist__c,
      'ATA with future target end date should be Open'
    );
  }

  // ================================================================
  // BULK TEST
  // ================================================================

  @isTest
  static void testBulk200() {
    leaseworks__Aircraft__c asset = getAsset('Sync Test Aircraft 5');
    pro_Target__c target = getTarget('Future Target');

    List<pro_Asset_Target_Audit__c> atas = new List<pro_Asset_Target_Audit__c>();
    for (Integer i = 0; i < BULK_SIZE; i++) {
      atas.add(
        new pro_Asset_Target_Audit__c(
          pro_Asset__c = asset.Id,
          pro_Target_Forecast__c = target.Id
        )
      );
    }

    Test.startTest();
    insert atas;
    Test.stopTest();

    List<pro_Asset_Target_Audit__c> results = [
      SELECT pro_Progress_Picklist__c
      FROM pro_Asset_Target_Audit__c
      WHERE Id IN :atas
    ];
    System.assertEquals(
      BULK_SIZE,
      results.size(),
      'All 200 records should be inserted successfully'
    );
    for (pro_Asset_Target_Audit__c result : results) {
      System.assertEquals(
        Pro_ProgressSyncHandler.STATUS_OPEN,
        result.pro_Progress_Picklist__c,
        'All bulk records should be Open'
      );
    }
  }

  // ================================================================
  // NO-OP OPTIMISATION TEST
  // ================================================================

  @isTest
  static void testNoOp_PicklistAlreadyCorrect() {
    leaseworks__Aircraft__c asset = getAsset('Sync Test Aircraft 1');
    pro_Target__c target = getTarget('Future Target');

    pro_Asset_Target_Audit__c ata = new pro_Asset_Target_Audit__c(
      pro_Asset__c = asset.Id,
      pro_Target_Forecast__c = target.Id
    );
    insert ata;

    // Re-query to get the trigger-set value
    ata = [
      SELECT
        Id,
        pro_Progress_Picklist__c,
        pro_Target_Readjusted__c,
        pro_Asset__c,
        pro_Target_Forecast__c
      FROM pro_Asset_Target_Audit__c
      WHERE Id = :ata.Id
    ];
    System.assertEquals(
      Pro_ProgressSyncHandler.STATUS_OPEN,
      ata.pro_Progress_Picklist__c,
      'Precondition: picklist should be Open'
    );

    // Update a non-progress-affecting field; picklist should stay the same
    Test.startTest();
    update ata;
    Test.stopTest();

    pro_Asset_Target_Audit__c result = [
      SELECT pro_Progress_Picklist__c
      FROM pro_Asset_Target_Audit__c
      WHERE Id = :ata.Id
    ];
    System.assertEquals(
      Pro_ProgressSyncHandler.STATUS_OPEN,
      result.pro_Progress_Picklist__c,
      'Picklist should remain Open when no progress-affecting fields changed'
    );
  }

  // ================================================================
  // NULL LOOKUP TESTS
  // ================================================================

  @isTest
  static void testNullContract() {
    leaseworks__Aircraft__c asset = getAsset('Sync Test Aircraft 1');
    pro_Target__c target = getTarget('Future Target');

    pro_Asset_Target_Audit__c ata = new pro_Asset_Target_Audit__c(
      pro_Asset__c = asset.Id,
      pro_Target_Forecast__c = target.Id,
      pro_Contract__c = null
    );

    Test.startTest();
    insert ata;
    Test.stopTest();

    pro_Asset_Target_Audit__c result = [
      SELECT pro_Progress_Picklist__c
      FROM pro_Asset_Target_Audit__c
      WHERE Id = :ata.Id
    ];
    System.assertEquals(
      Pro_ProgressSyncHandler.STATUS_OPEN,
      result.pro_Progress_Picklist__c,
      'ATA with null Contract should default to Open'
    );
  }

  @isTest
  static void testNullAiD() {
    leaseworks__Aircraft__c asset = getAsset('Sync Test Aircraft 2');
    pro_Target__c target = getTarget('Future Target');

    pro_Asset_Target_Audit__c ata = new pro_Asset_Target_Audit__c(
      pro_Asset__c = asset.Id,
      pro_Target_Forecast__c = target.Id,
      pro_Asset_in_Deal__c = null
    );

    Test.startTest();
    insert ata;
    Test.stopTest();

    pro_Asset_Target_Audit__c result = [
      SELECT pro_Progress_Picklist__c
      FROM pro_Asset_Target_Audit__c
      WHERE Id = :ata.Id
    ];
    System.assertEquals(
      Pro_ProgressSyncHandler.STATUS_OPEN,
      result.pro_Progress_Picklist__c,
      'ATA with null AiD should default to Open'
    );
  }

  @isTest
  static void testNullTarget() {
    // pro_Target_Forecast__c is Master-Detail, so we cannot set it null.
    // Instead, test the calculateProgress logic directly with a null target map entry.
    leaseworks__Aircraft__c asset = getAsset('Sync Test Aircraft 3');

    // Build maps with empty entries to simulate null lookups
    Map<Id, leaseworks__Lease__c> emptyContractMap = new Map<Id, leaseworks__Lease__c>();
    Map<Id, leaseworks__Aircraft_Proposal__c> emptyAidMap = new Map<Id, leaseworks__Aircraft_Proposal__c>();
    Map<Id, pro_Target__c> emptyTargetMap = new Map<Id, pro_Target__c>();
    Map<Id, leaseworks__Aircraft__c> emptyAssetMap = new Map<Id, leaseworks__Aircraft__c>();

    // Create a minimal ATA-like record in memory (not inserted, for unit test of calculateProgress)
    pro_Asset_Target_Audit__c ata = new pro_Asset_Target_Audit__c(
      pro_Asset__c = asset.Id,
      pro_Target_Readjusted__c = false,
      pro_Contract_Extended__c = false,
      pro_New_Contract_Signed__c = false
    );

    Test.startTest();
    String result = Pro_ProgressSyncHandler.calculateProgress(
      ata,
      emptyContractMap,
      emptyAidMap,
      emptyTargetMap,
      emptyAssetMap
    );
    Test.stopTest();

    System.assertEquals(
      Pro_ProgressSyncHandler.STATUS_OPEN,
      result,
      'ATA with no related records in maps should default to Open'
    );
  }
}