force-app/main/default/objects/leaseworks__Aircraft__c/leaseworks__Aircraft__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageAircraft</customHelpPage>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Aircraft_Type__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Aircraft_Type__c</fullName>
    <description>Type of the asset</description>
    <label>Z_Unused_2308 Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>727</fullName>
            </value>
            <value>
                <fullName>737</fullName>
            </value>
            <value>
                <fullName>747</fullName>
            </value>
            <value>
                <fullName>757</fullName>
            </value>
            <value>
                <fullName>767</fullName>
            </value>
            <value>
                <fullName>777</fullName>
            </value>
            <value>
                <fullName>787</fullName>
            </value>
            <value>
                <fullName>A300</fullName>
            </value>
            <value>
                <fullName>A300 B4</fullName>
            </value>
            <value>
                <fullName>A310</fullName>
            </value>
            <value>
                <fullName>A319</fullName>
            </value>
            <value>
                <fullName>A320</fullName>
            </value>
            <value>
                <fullName>A321</fullName>
            </value>
            <value>
                <fullName>A330</fullName>
            </value>
            <value>
                <fullName>A340</fullName>
            </value>
            <value>
                <fullName>A380</fullName>
            </value>
            <value>
                <fullName>ATR</fullName>
            </value>
            <value>
                <fullName>BAe 146 / Avro RJ</fullName>
            </value>
            <value>
                <fullName>Bombardier CRJ</fullName>
            </value>
            <value>
                <fullName>Bombardier CSeries</fullName>
            </value>
            <value>
                <fullName>Bombardier Dash 8</fullName>
            </value>
            <value>
                <fullName>Bombardier Q400</fullName>
            </value>
            <value>
                <fullName>de Havilland Dash 7</fullName>
            </value>
            <value>
                <fullName>Embraer E</fullName>
            </value>
            <value>
                <fullName>Embraer ERJ</fullName>
            </value>
            <value>
                <fullName>Fokker</fullName>
            </value>
            <value>
                <fullName>Mitsubishi Regional Jet</fullName>
            </value>
            <value>
                <fullName>SAAB</fullName>
            </value>
            <value>
                <fullName>Shukhoi Superjet 100</fullName>
            </value>
            <value>
                <fullName>Embraer EMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Asset_Variant_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Asset_Variant_GP__c</fullName>
    <label>Asset Variant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Asset_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Asset_Variant_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Engine_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Type_GP__c</fullName>
    <label>Engine Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Asset_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Engine_Variant_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Variant_GP__c</fullName>
    <label>Engine Variant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Engine_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Variant_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft_Type__c/leaseworks__Aircraft_Type__c.object-meta.xml
<CustomObject>
    <description>Object that captures trends in aircraft types based on conversations that are happening across fleets and customers.</description>
    <label>Aircraft Type</label>
    <nameField>
        <label>Aircraft Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircraft Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Aircraft_Type__c/fields/leaseworks__Asset_Variant_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Asset_Variant_GP__c</fullName>
    <label>Asset Variant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Asset_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Asset_Variant_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft_Type__c/fields/leaseworks__Engine_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Type_GP__c</fullName>
    <label>Engine Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Asset_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft_Type__c/fields/leaseworks__Engine_Variant_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Variant_GP__c</fullName>
    <label>Engine Variant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Engine_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Variant_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/leaseworks__Constituent_Assembly__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageAircraft</customHelpPage>
    <label>Assembly</label>
    <nameField>
        <label>Assembly Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assemblies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__Engine_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Type_GP__c</fullName>
    <label>Engine Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Manufacturer_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Constituent_Assembly__c/fields/leaseworks__Engine_Variant_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Variant_GP__c</fullName>
    <label>Engine Variant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Engine_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Variant_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Customer_Interaction_Log__c/leaseworks__Customer_Interaction_Log__c.object-meta.xml
<CustomObject>
    <description>[MODULE: NA]
[LOAD: No]
[PREREQUISITES: NA]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Interaction Log</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interaction Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Customer_Interaction_Log__c/fields/leaseworks__Asset_Variant_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Asset_Variant_GP__c</fullName>
    <label>Asset Variant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Asset_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Asset_Variant_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Customer_Interaction_Log__c/fields/leaseworks__Engine_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Type_GP__c</fullName>
    <label>Engine Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Asset_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Engine_Template__c/leaseworks__Engine_Template__c.object-meta.xml
<CustomObject>
    <label>Engine Template</label>
    <nameField>
        <label>Engine Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engine Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Engine_Template__c/fields/leaseworks__Engine_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Type_GP__c</fullName>
    <label>Engine Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Manufacturer_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Engine_Template__c/fields/leaseworks__Engine_Variant_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Variant_GP__c</fullName>
    <label>Engine Variant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Engine_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Variant_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Market_Intelligence__c/leaseworks__Market_Intelligence__c.object-meta.xml
<CustomObject>
    <label>Market Intelligence</label>
    <nameField>
        <label>Market Intel Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Intelligence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Market_Intelligence__c/fields/leaseworks__Asset_Variant_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Asset_Variant_GP__c</fullName>
    <label>Asset Variant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Asset_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Asset_Variant_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Market_Intelligence__c/fields/leaseworks__Engine_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Type_GP__c</fullName>
    <label>Engine Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Asset_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Market_Intelligence__c/fields/leaseworks__Engine_Variant_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Variant_GP__c</fullName>
    <label>Engine Variant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Engine_Type_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Variant_Global</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/leaseworks__Pricing_Run_New__c/leaseworks__Pricing_Run_New__c.object-meta.xml
<CustomObject>
    <description>[MODULE: NA]
[LOAD: No]
[PREREQUISITES: NA]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Commercial Terms</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Pricing_Run_New__c/fields/leaseworks__Engine_Type_GP__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Engine_Type_GP__c</fullName>
    <label>Engine Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>leaseworks__Manufacturer_GP__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>leaseworks__Engine_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/leaseworks__Asset_Variant_Global.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A220-371</fullName>
    </customValue>
    <customValue>
        <fullName>A220-100</fullName>
    </customValue>
    <customValue>
        <fullName>A220-300</fullName>
    </customValue>
    <customValue>
        <fullName>A310-304</fullName>
    </customValue>
    <customValue>
        <fullName>A318-111</fullName>
    </customValue>
    <customValue>
        <fullName>A319-111</fullName>
    </customValue>
    <customValue>
        <fullName>A319-112</fullName>
    </customValue>
    <customValue>
        <fullName>A319-113</fullName>
    </customValue>
    <customValue>
        <fullName>A319-132</fullName>
    </customValue>
    <customValue>
        <fullName>A320-211</fullName>
    </customValue>
    <customValue>
        <fullName>A320-214</fullName>
    </customValue>
    <customValue>
        <fullName>A320-216</fullName>
    </customValue>
    <customValue>
        <fullName>A320-232</fullName>
    </customValue>
    <customValue>
        <fullName>A320-233</fullName>
    </customValue>
    <customValue>
        <fullName>A320-271N</fullName>
    </customValue>
    <customValue>
        <fullName>A321-131</fullName>
    </customValue>
    <customValue>
        <fullName>A321-200XLR</fullName>
    </customValue>
    <customValue>
        <fullName>A321-211</fullName>
    </customValue>
    <customValue>
        <fullName>A321-231</fullName>
    </customValue>
    <customValue>
        <fullName>A321-251NX</fullName>
    </customValue>
    <customValue>
        <fullName>A321-271NX</fullName>
    </customValue>
    <customValue>
        <fullName>A330-202</fullName>
    </customValue>
    <customValue>
        <fullName>A330-223</fullName>
    </customValue>
    <customValue>
        <fullName>A330-243</fullName>
    </customValue>
    <customValue>
        <fullName>A330-302</fullName>
    </customValue>
    <customValue>
        <fullName>A330-322</fullName>
    </customValue>
    <customValue>
        <fullName>A330-323</fullName>
    </customValue>
    <customValue>
        <fullName>A330-343</fullName>
    </customValue>
    <customValue>
        <fullName>A330-941</fullName>
    </customValue>
    <customValue>
        <fullName>A340-312</fullName>
    </customValue>
    <masterLabel>Asset Variant</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/leaseworks__Engine_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CF34</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80A</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80C2</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80E1</fullName>
    </customValue>
    <customValue>
        <fullName>CFM56-5A</fullName>
    </customValue>
    <customValue>
        <fullName>CFM56-5B</fullName>
    </customValue>
    <customValue>
        <fullName>CFM56-5C</fullName>
    </customValue>
    <customValue>
        <fullName>CFM56-7B</fullName>
    </customValue>
    <customValue>
        <fullName>GE90-100</fullName>
    </customValue>
    <customValue>
        <fullName>LEAP-1A</fullName>
    </customValue>
    <customValue>
        <fullName>LEAP-1B</fullName>
    </customValue>
    <customValue>
        <fullName>PW1000G</fullName>
    </customValue>
    <customValue>
        <fullName>PW1100G-JM</fullName>
    </customValue>
    <customValue>
        <fullName>PW1500</fullName>
    </customValue>
    <customValue>
        <fullName>PW2000</fullName>
    </customValue>
    <customValue>
        <fullName>PW4000</fullName>
    </customValue>
    <customValue>
        <fullName>PW4000-100</fullName>
    </customValue>
    <customValue>
        <fullName>PW4056</fullName>
    </customValue>
    <customValue>
        <fullName>Trent-700</fullName>
    </customValue>
    <customValue>
        <fullName>Trent-800</fullName>
    </customValue>
    <customValue>
        <fullName>Trent-1000</fullName>
    </customValue>
    <customValue>
        <fullName>Trent-7000</fullName>
    </customValue>
    <customValue>
        <fullName>Trent-XWB</fullName>
    </customValue>
    <customValue>
        <fullName>V2500-( )5</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>PW4162</fullName>
        <isActive>false</isActive>
        <label>PW4162</label>
    </customValue>
    <customValue>
        <fullName>PW4168A</fullName>
        <isActive>false</isActive>
        <label>PW4168A</label>
    </customValue>
    <customValue>
        <fullName>PW4462</fullName>
        <isActive>false</isActive>
        <label>PW4462</label>
    </customValue>
    <customValue>
        <fullName>RB211</fullName>
        <isActive>false</isActive>
        <label>RB211</label>
    </customValue>
    <customValue>
        <fullName>Trent 892B</fullName>
        <isActive>false</isActive>
        <label>Trent 892B</label>
    </customValue>
    <masterLabel>Engine Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/leaseworks__Engine_Variant_Global.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2500-A1bump</fullName>
    </customValue>
    <customValue>
        <fullName>2522-A5</fullName>
    </customValue>
    <customValue>
        <fullName>2524-A5SelectOne</fullName>
    </customValue>
    <customValue>
        <fullName>2527-A5SelectOne</fullName>
    </customValue>
    <customValue>
        <fullName>2527-A5SelectTwo</fullName>
    </customValue>
    <customValue>
        <fullName>2527E-A5SelectOne</fullName>
    </customValue>
    <customValue>
        <fullName>2527E-A5SelectTwo</fullName>
    </customValue>
    <customValue>
        <fullName>2527M-A5</fullName>
    </customValue>
    <customValue>
        <fullName>2527M-A5SelectOne</fullName>
    </customValue>
    <customValue>
        <fullName>2530-A5</fullName>
    </customValue>
    <customValue>
        <fullName>2530-A5SelectOne</fullName>
    </customValue>
    <customValue>
        <fullName>2530-A5SelectTwo</fullName>
    </customValue>
    <customValue>
        <fullName>2533-A5SelectOne</fullName>
    </customValue>
    <customValue>
        <fullName>2533-A5SelectTwo</fullName>
    </customValue>
    <customValue>
        <fullName>CF34-10E5A1</fullName>
    </customValue>
    <customValue>
        <fullName>CF34-10E6</fullName>
    </customValue>
    <customValue>
        <fullName>CF34-10E6A1</fullName>
    </customValue>
    <customValue>
        <fullName>CF34-10E7</fullName>
    </customValue>
    <customValue>
        <fullName>CF34-3B1</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80A2</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80C2A2</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80C2-A2/B2</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80C2-A3</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80C2A5</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80C2-A5</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80C2A8</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80C2-B1/B1F</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80C2B1F</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80C2B4</fullName>
    </customValue>
    <customValue>
        <fullName>CF6-80C2-B5F</fullName>
    </customValue>
    <masterLabel>Engine Variant</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchExportDependenciesLocal.cls
/**********
 * This batch class sends an email with the Global picklist dependencies
 * Ref Asana: https://app.asana.com/0/1150819886958569/1207229892284268/f
**********/ 
public class BatchExportDependenciesLocal implements Database.batchable <String>, Database.Stateful, Database.AllowsCallouts{
  
  String exceptionMessage; 
  String logMessage;
  String versionNumber;  
  public BatchExportDependenciesLocal(String versionNumber)
  {
     this.versionNumber = (versionNumber == ''? 'ALL': versionNumber);
     exceptionMessage = '';   
     logMessage = '';     
  }
     
  public  List<String> start(Database.BatchableContext bc) {
      List<string> lstNewGPFields = new List<string>();
      if(this.versionNumber == '34' || this.versionNumber == 'ALL'){
          lstNewGPFields.add('leaseworks__Engine_Template__c.leaseworks__Engine_Type_GP__c');
          lstNewGPFields.add('leaseworks__Engine_Template__c.leaseworks__Engine_Variant_GP__c');            
          
          lstNewGPFields.add('leaseworks__Market_Intelligence__c.leaseworks__Engine_Type_GP__c');            
          lstNewGPFields.add('leaseworks__Market_Intelligence__c.leaseworks__Asset_Variant_GP__c');            
          lstNewGPFields.add('leaseworks__Market_Intelligence__c.leaseworks__Engine_Variant_GP__c');            
          
          lstNewGPFields.add('leaseworks__Customer_Interaction_Log__c.leaseworks__Engine_Type_GP__c');            
          lstNewGPFields.add('leaseworks__Customer_Interaction_Log__c.leaseworks__Asset_Variant_GP__c');            
          lstNewGPFields.add('leaseworks__Customer_Interaction_Log__c.leaseworks__Engine_Variant_GP__c');            
          
          lstNewGPFields.add('leaseworks__Pricing_Run_New__c.leaseworks__Engine_Type_GP__c');          
      }
     	
     if(this.versionNumber == '37' || this.versionNumber == 'ALL'){
         lstNewGPFields.add('leaseworks__Aircraft_Type__c.leaseworks__Asset_Variant_GP__c');
         lstNewGPFields.add('leaseworks__Aircraft_Type__c.leaseworks__Engine_Type_GP__c');
         lstNewGPFields.add('leaseworks__Aircraft_Type__c.leaseworks__Engine_Variant_GP__c');
         
         lstNewGPFields.add('leaseworks__Constituent_Assembly__c.leaseworks__Engine_Type_GP__c');
         lstNewGPFields.add('leaseworks__Constituent_Assembly__c.leaseworks__Engine_Variant_GP__c');                  
         
         lstNewGPFields.add('leaseworks__Aircraft__c.leaseworks__Asset_Variant_GP__c');
         lstNewGPFields.add('leaseworks__Aircraft__c.leaseworks__Engine_Type_GP__c');                  
     }   
      system.debug('lstNewGPFields --' + lstNewGPFields);
     return lstNewGPFields;
 }
     
 public void execute(Database.BatchableContext BC, List<String> newGPField)
 {
   
    String objectName = newGPField[0].substringBefore('.');
    String fieldName = newGPField[0].substringAfter('.');
    logMessage += '<br/><br/>' + 'Processing ' + 'Object==' + objectName + ',  Field==' + fieldName + '<br/>';
    System.debug('Processing==' + 'Object=' + objectName + '==Field==' + fieldName); 
        
    try{
        
       Map<Object,List<String>> mapPicklistValues = getDependentPicklistValues
        (   Schema.getGlobalDescribe().get( objectName ).getDescribe().fields.getMap().get( fieldName )
        );
        
        for(Object controlVal: mapPicklistValues.keyset()){
            System.debug('control val==' + controlVal);
            logMessage += '<br/>' + 'Controlling Value==' + controlVal + ' (';
            for(String dependVal: mapPicklistValues.get(controlVal)){
                System.debug('depend val==' + dependVal);
                 logMessage += dependVal + ',';
            }
            String newlogMessage = logMessage.removeEnd(',');            
            logMessage = newlogMessage + ')';
        }

	}
	catch(Exception ex){
        logMessage += 'ERROR: Exception while fetching dependencies=='+ objectName 
            + '==' + fieldName +'==' + ex.getMessage() + '<br/>';
        exceptionMessage += 'ERROR: Exception while fetching dependencies=='+ objectName 
            + '==' + fieldName +'==' + ex.getMessage() + '<br/>';
		System.debug('ERROR: Exception while fetching dependencies=='+ ex.getMessage());
	}
}

private static Map<Object,List<String>> getDependentPicklistValues( Schema.sObjectField dependToken )
{
    Schema.DescribeFieldResult depend = dependToken.getDescribe();
    Schema.sObjectField controlToken = depend.getController();
    if ( controlToken == null ) return null;
    Schema.DescribeFieldResult control = controlToken.getDescribe();
    List<Schema.PicklistEntry> controlEntries =
    (   control.getType() == Schema.DisplayType.Boolean
    ?   null
    :   control.getPicklistValues()
    );
 	
    String base64map = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
    Map<Object,List<String>> dependentPicklistValues = new Map<Object,List<String>>();
    for ( Schema.PicklistEntry entry : depend.getPicklistValues() ) if ( entry.isActive() )
    {
        List<String> base64chars =
            String.valueOf
            (   ((Map<String,Object>) JSON.deserializeUntyped( JSON.serialize( entry ) )).get( 'validFor' )
            ).split( '' );
        for ( Integer index = 0; index < (controlEntries != null ? controlEntries.size() : 2); index++ )
        {
            Object controlValue =
            (   controlEntries == null
            ?   (Object) (index == 1)
            :   (Object) (controlEntries[ index ].isActive() ? controlEntries[ index ].getValue() : null)
            );
            Integer bitIndex = index / 6;
            if (bitIndex > base64chars.size()-1) { break; }
            Integer bitShift = 5 - Math.mod( index, 6 );
            
            if  (   controlValue == null
                ||  (base64map.indexOf( base64chars[ bitIndex ] ) & (1 << bitShift)) == 0
                ) continue;
            if ( !dependentPicklistValues.containsKey( controlValue ) )
            {
                dependentPicklistValues.put( controlValue, new List<String>() );
            }
            dependentPicklistValues.get( controlValue ).add( entry.getLabel() );
        }
    }
    return dependentPicklistValues;
}
public void finish(Database.BatchableContext BC) {
   	if(!String.isEmpty(exceptionMessage)){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setTargetObjectId( UserInfo.getUserId() );
		mail.setSaveAsActivity( false );
        
        String subjectName = 'Error while fetching dependencies';
        mail.setSubject( '[' + System.UserInfo.getOrganizationName() + '(' + System.UserInfo.getOrganizationId()  + ')] - ' + subjectName );        
        mail.setHtmlBody(exceptionMessage);
        Messaging.sendEmail( new Messaging.SingleEmailMessage[] { mail } );
    }
    if(!String.isEmpty(logMessage)){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setTargetObjectId( UserInfo.getUserId() );
		mail.setSaveAsActivity( false );
        
        String subjectName = 'Successfully retrieved list of dependencies';
        mail.setSubject( '[' + System.UserInfo.getOrganizationName() + '(' + System.UserInfo.getOrganizationId()  + ')] - ' + subjectName );        
        mail.setHtmlBody(logMessage);
        Messaging.sendEmail( new Messaging.SingleEmailMessage[] { mail } );
    }
 }
    
}