force-app/main/default/objects/leaseworks__Aircraft__c/leaseworks__Aircraft__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageAircraft</customHelpPage>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Manufacturer__c</fullName>
    <label>Z_Unused_2508 Manufacturer</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__MSN_Number__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__MSN_Number__c</fullName>
    <externalId>true</externalId>
    <label>Serial Number</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestBatchAssetManufNewValues.cls
@istest
public class TestBatchAssetManufNewValues {
	@isTest
    private static void testAssetManufMethod(){
        leaseworks__Aircraft__c aircraft = new leaseworks__Aircraft__c(Name='TestAircraft',leaseworks__MSN_Number__c='TestMSN1',leaseworks__Manufacturer__c='Airbus');
        insert aircraft;
        Test.setMock(WebServiceMock.class, new CallOutMockLocal());
        Id batchJobId = Database.executeBatch(new BatchAssetManufNewValuesToRecordTypes(false), 10);
        batchJobId = Database.executeBatch(new BatchAssetManufNewValuesToRecordTypes(false,'leaseworks__Manufacturer__c'), 10);
    }
}