force-app/main/default/objects/leaseworks__Aircraft__c/leaseworks__Aircraft__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageAircraft</customHelpPage>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Lease__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Lease__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field automatically fills with the current active Lease record linked to this Asset, identified by the &#39;Active&#39; field (leaseworks__Active__c) set to &#39;True&#39;. In the absence of an active Lease on this Asset (following the described logic), the system will clear this field. [This process is executed through a scheduled job that runs daily.]</description>
    <inlineHelpText>This field is automatically filled with the current active Lease record linked to this Asset, determined by the &#39;Active&#39; field being set to &#39;True&#39;. If there is no active Lease associated with this Asset (following the logic described), the system will clear this field.</inlineHelpText>
    <label>Lease</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Selected Lease has already different Asset assigned, please change the Lease before saving this Asset</errorMessage>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>leaseworks__Lease__c.leaseworks__Aircraft__c</valueField>
        </filterItems>
        <filterItems>
            <field>leaseworks__Lease__c.leaseworks__Aircraft__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Lease__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Aircrafts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/leaseworks__Lease__c.object-meta.xml
<CustomObject>
    <description>Central table for Lease Agreement/contract headers, storing essential details like start/end dates, current status, and associated asset reference.</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Active__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Active__c</fullName>
    <description>Active? Lease checkbox for reporting. Driven by Lease Start and Lease End/Redelivery date, based on Setup -&gt; Custom Settings -&gt; Leaseworks Settings -&gt; Active Lease logic. Active? Override field on the Lease page can override the calculation formula when selected by user</description>
    <formula>If(
        (ISPICKVAL( leaseworks__Active_Override__c ,&#39;Default&#39;) || ISBLANK(TEXT( leaseworks__Active_Override__c ))) , 
        AND(leaseworks__Lease_Start_Date_New__c &lt;= TODAY(),
        
        IF($Setup.leaseworks__LeaseWorksSettings__c.leaseworks__Active_Lease_Logic__c=&#39;Redelivery Date&#39;,
        true,
        leaseworks__Lease_End_Date_New__c&gt;= TODAY()
        ),
        
        (TEXT(leaseworks__Lease_Type_Status__c)==&#39;On Lease&#39;),
        !ISBLANK(leaseworks__Aircraft__c) ),If(ISPICKVAL( leaseworks__Active_Override__c ,&#39;Active&#39;),True,False))</formula>
    <inlineHelpText>Active? Lease checkbox for reporting. Driven by Lease Start and Lease End or Redelivery date based on the configuration. Active? Override field on the Lease page can override the calculation formula when selected by user</inlineHelpText>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/leaseworks__Lease__c/fields/leaseworks__Aircraft__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Aircraft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Specify the asset this lease is in relation to</inlineHelpText>
    <label>Asset</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>leaseworks__Aircraft__c.leaseworks__Status__c</field>
            <operation>equals</operation>
            <value>Available, Assigned</value>
        </filterItems>
        <filterItems>
            <field>$Source.leaseworks__Lease_Type_Status__c</field>
            <operation>equals</operation>
            <value>LOI</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non-Lease Agreement</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>leaseworks__Aircraft__c</referenceTo>
    <relationshipLabel>Related Lease</relationshipLabel>
    <relationshipName>Leases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LocalBatchCheckActiveLeaseOnAsset.cls
/*
Local Batch created for Testing
 *
 * Task Reference   : https://app.asana.com/1/7934919496419/project/1207699982244107/task/1211169694765350?focus=true
 * Description      : Batch process to update Asset records that are associated with Inactive Leases.
 *                    Ensures that only one active lease is linked to an Asset at any time.
 * Purpose          : This is a local version created for testing purposes only.
 * Actual Behavior  : In production, the packaged scheduler (UpdateRentOnLeaseScheduler) executes
 *                    the actual logic, not this local batch.
 *
 * Called From      : UpdateRentOnLeaseScheduler (for packaged logic)
*/
public class LocalBatchCheckActiveLeaseOnAsset  implements Database.Batchable<SObject>,Database.Stateful {
    
     string exceptionMessage='';
     string errorMessage='';
 
    public static void callBatchCheckActiveLeaseOnAsset() {
       
        Database.executeBatch(new LocalBatchCheckActiveLeaseOnAsset(),10);
    }
 	public Database.QueryLocator start(Database.BatchableContext BC){
        String strQuery='select id,leaseworks__Lease__c,leaseworks__lease__r.leaseworks__active__C,name,(select id,leaseworks__active__c from leaseworks__Leases__r where leaseworks__active__C=true  order by CreatedDate  ) from leaseworks__Aircraft__c  ';
        System.debug(strQuery);
        return Database.getQueryLocator(strQuery); 
    }
	public void execute(Database.BatchableContext BC, List<sObject> scope){
        System.debug('execute');
        try{
            
        	string duplicateRecord=setActiveLeaseonAsset(scope);
            errorMessage+=duplicateRecord;
            system.debug('error  '+errorMessage);
        }
        catch(Exception e){
            //leaseworks.leasewareUtils.TriggerDisabledFlag = false; 
            exceptionMessage= e.getmessage();
        }
     }
	public void finish(Database.BatchableContext BC){
        
        system.debug('final msg '+errorMessage);
        if(!string.isempty(errorMessage)){
            string emailbody='The below asset(s) have multiple active leases which is not expected. An asset can have only one active lease. Please review.'+'<br>'+'<br>';
            emailbody+='<table cellspacing="0" border="1"><tr>'+'<b>Asset Name</b></tr>'+ errorMessage+'</table>'+'<br>'+'<br>';
            LeaseWareUtilsLocal.sendEmailToLWAdmins('LeaseWorks: Multiple Active Leases on Asset', emailbody);
        }
        else{
            system.debug('records processed.!');
        }
         if(String.isEmpty(exceptionMessage)){
           System.debug('records processed.!');
        }
        else{
             LeaseWareUtilsLocal.sendEmail('Batch Update Active Lease on Asset', 'There was an unexpected error while updating active lease on asset. Please contact your LeaseWorks System Administrator. \n \n \n  <br/><br/>Reason :'+ exceptionMessage, UserInfo.getUserEmail(), 'Regular');
        }
        
    }
    
    public static string setActiveLeaseonAsset(list<leaseworks__aircraft__c> newList){
        string Emailmessage='';
        list<leaseworks__aircraft__c> listOfAircraft= new list<leaseworks__aircraft__c>();
        System.debug('Aircraft size'+newList.size());
        for(leaseworks__Aircraft__c aircraft :(leaseworks__Aircraft__c[])newList){
            Boolean Ischanged=false;
            if(aircraft.leaseworks__Lease__c !=null && !(aircraft.leaseworks__lease__r.leaseworks__active__C)){
                aircraft.leaseworks__Lease__c=null;
                Ischanged=true;
            }
            if(aircraft.leaseworks__leases__r.size()>1){
                Emailmessage+= '<tr>'+'<html><a href="'+URL.getOrgDomainUrl().toExternalForm()+'/'+aircraft.id+'">'+aircraft.name+'</a></html>'+'</tr>';
            }
            else{
            	for(leaseworks__lease__c lease:aircraft.leaseworks__leases__r){
              		if(aircraft.leaseworks__Lease__c!=lease.id ){
                  		aircraft.leaseworks__Lease__c=lease.id;
                  		Ischanged=true;
               	   }  
                }
            }
            if(Ischanged=true){
            	listOfAircraft.add(aircraft);
            }
         }
         if(listOfAircraft.size()>0){
        	leaseworks.LWGlobalUtils.setTriggersOff();
            update listOfAircraft;
            leaseworks.LWGlobalUtils.setTriggersOn();
         }
        return Emailmessage;
	}
}