force-app/main/default/objects/leaseworks__Aircraft__c/leaseworks__Aircraft__c.object-meta.xml
<CustomObject>
    <customHelpPage>leaseworks__DeskComHelpPageAircraft</customHelpPage>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/leaseworks__Aircraft__c/fields/leaseworks__Maintenance_Program__c.field-meta.xml
<CustomField>
    <fullName>leaseworks__Maintenance_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use &quot;MP Update&quot; button to change Maintenance Program assignment.</inlineHelpText>
    <label>Maintenance Program</label>
    <referenceTo>leaseworks__Maintenance_Program__c</referenceTo>
    <relationshipLabel>Assets (Maintenance Program)</relationshipLabel>
    <relationshipName>Aircraft</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/leaseworks__Maintenance_Program__c/leaseworks__Maintenance_Program__c.object-meta.xml
<CustomObject>
    <description>The &quot;Maintenance Program&quot; table encompasses all maintenance programs that can be associated with different assets. Typically, a single maintenance program is established for each type of aircraft. However, users might prefer to set up unique programs for each operator or region to tailor maintenance intervals and the cost of shop visits. This can be uploaded either prior to configuring an aircraft or afterward. However, possessing a Maintenance Program is a prerequisite for projecting maintenance events.
[MODULE: Asset]
[LOAD: Optional]
[PREREQUISITES: NA]
[REPLACEMENT OBJECT API: NA]
[COMMENTS: NA]</description>
    <label>Maintenance Program</label>
    <nameField>
        <label>Maintenance Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Program</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchTocreateProjectedEvents.cls
/*****
Description - This Batch class will help us to Create related Projected Events on Assembly 
*****/
public class BatchTocreateProjectedEvents implements Database.stateful,Database.Batchable<sObject>{
    string errorMsg='';
	String logMessage='';
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([Select Id, leaseworks__Maintenance_Program__c from leaseworks__Aircraft__c where leaseworks__Maintenance_Program__c !=null order by leaseworks__Maintenance_Program__c]);
    }
     
    public void execute(Database.BatchableContext BC, List<leaseworks__Aircraft__c> aircraftList)
    {       
        set<Id> setMPIds = new set<Id>();
        set<Id> setAssetIds = new set<Id>();
        
        for(leaseworks__Aircraft__c curRec : aircraftList ){
            setMPIds.add(curRec.leaseworks__Maintenance_Program__c);
            setAssetIds.add(curRec.Id);
        }
        system.debug(setMPIds);
        try{    
            String typeOfMethod = 'ProjectedEventUpdate';
            Integer batchSize = 200;
            Boolean updateMode = false;
            map<String,String> mapParams = new map<String,String>();
            mapParams.put('MPID',JSON.serialize(setMPIds));
            mapParams.put('ASSETID',JSON.serialize(setAssetIds));
            leaseworks.LWGlobalUtils.callGlobalScript(typeOfMethod,batchSize,updateMode,mapParams);
			logMessage += 'Assets Ids  :: '+setAssetIds+'\n' +'MP Ids :: '+setMPIds +'\n' ;
        }catch(Exception e){
             errorMsg += e.getMessage()+'---Assets Ids  :: '+setAssetIds+'\n' ;
			 
        }
    }
    public void finish(Database.BatchableContext BC) {
        if(string.isNotBlank(errorMsg)){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTargetObjectId( UserInfo.getUserId() );
            mail.setSaveAsActivity( false );
            
            String subjectName = 'Error while creating Projected Events';
            mail.setSubject( '[' + System.UserInfo.getOrganizationName() + '(' + System.UserInfo.getOrganizationId()  + ')] - ' + subjectName );        
            mail.setHtmlBody(errorMsg);
			Messaging.sendEmail( new Messaging.SingleEmailMessage[] { mail } );
        }else{
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTargetObjectId( UserInfo.getUserId() );
            mail.setSaveAsActivity( false );
            
            String subjectName = 'Successfully created Projected Events';
            mail.setSubject( '[' + System.UserInfo.getOrganizationName() + '(' + System.UserInfo.getOrganizationId()  + ')] - ' + subjectName );        
            mail.setHtmlBody(logMessage);
			Messaging.sendEmail( new Messaging.SingleEmailMessage[] { mail } );
        }
    
    }
}